### ISSUE TITLE
Switch audiosource from remote stream (multi audiostream support)

### ISSUE THREAD

**Issue by FlapperA** [Azure/Communication#101]
**Is your feature request related to a problem? Please describe.**
My remote stream has multiple audio streams for the various languages (and participants) it outputs. Currently I can only receive the default audio stream and the other available languages are not available for the local client.

**Describe the solution you'd like**
On the client side I want to be able to select the audio stream I want to listen to, belonging to a single video stream. Preferable, I can label the incoming audio streams so that user can choose the right one for him/her. 

**Describe alternatives you've considered**
~~Streaming the local client video stream to Azure Media Service as live event (RTMP-stream) and handle multi-audio there.  However, then I have to build a server platform that  will allow me to switch speakers quickly to simulate a videoconferencing experience.~~ => Latency (> 10s) of Media Services killed this idea

Currently looking if we can simulate this via rooms per language, but no progress yet

**Additional context**
--

**Comment by FlapperA** [comment]
Was hoping on some news on this. Is it possible to do this, maybe by switching audiostreams in the client?  If so, how would I do that?

**Comment by mariusu-msft** [comment]
Hi @FlapperA,

Currently this is not supported. We'll keep this feedback open and consider it as a feature request.

Thanks,
Marius

**Comment by ProbablePrime** [comment]
@mariusu-msft Is this logged in ADO? Can you provide a link so we can mark it as ADO Linked?
