### ISSUE TITLE
Video buffering issues on Safari when communicating with other browsers.

### ISSUE THREAD

**Issue by lanierc** [Azure/Communication#103]
**Describe the bug**
Video calls from Safari to other browsers (Chrome/Vivaldi/Edge/Brave) does not buffer properly, causing video freezes on the other side.

**To Reproduce**
1. Initiate a video call on one side using Safari
2. Receive the call from a Chromium-based browser
3. Both sides instantiate video

**Expected behavior**
Video should be clear on both sides.

**Screenshots**
Video remains smooth on Safari of bother sender and receiver, while received video from Chrome freezes, becomes pixelated or choppy, while local video remains smooth.

**Desktop (please complete the following information):**
 - OS: macos Catalina
 - Browser: Safari + Vivaldi
 - Version 14.0 (Safari), 3.4.2066.94 (Vivaldi)

**Additional context**
This was cross-tested using Chrome (86.0.4240.198) communicating with Vivaldi (same version as above), as well as Brave (1.16.76), and macos Edge(86.0.622.68). Also cross-tested with iOS Safari and this issue does occur on it as well.

**Comment by akania** [comment]
Hi @lanierc , you can find currently supported browsers in the documentation https://docs.microsoft.com/en-us/azure/communication-services/concepts/voice-video-calling/calling-sdk-features

We do not support all "chromium" based browsers, but rather focus on Chrome/Edge (on Windows/Linux.. ) and and limited support for Safari.

**Comment by lanierc** [comment]
Hello @akania,

Thanks for this. I understand that Vivaldi isn't support. Unfortunately, I tried to replicate this issue communicating between Chrome & Safari, and succeeded.

It seems that the limited support of Safari is the culprit, as there is definitely some sort of buffer or bottleneck issue in sending video from Safari in ACS, while receiving video appears to be fine.

**Comment by mariusu-msft** [comment]
Hi @lanierc,

Can you check if you see the same behavior using the groupId call concept?

Thanks,
Marius

**Comment by chriswhilar** [comment]
Just tried this out and is working fine on Safari Version 14.0.1 (16610.2.11.51.8) on macOS

**Comment by chriswhilar** [comment]
@mariusu-msft @akania I have also tried video group call with the web calling sample and im not seeing video freezes at all. 

For group call scenario i did:
1 participant is using safari (same version from my last comment) on macOS.
1 participant is using chrome (Version 86.0.4240.198) on windows 
1 participant is using safari (version 13.1.2) on iOS
All particpants do CallAgent.join() API with video on. I ran the group call for about 5 minutes. 

Everything seems to be working fine as expected, im not seeing any video freezes at all. I do notice that the incoming video stream from iOS safari is very pixelated at times throughout the call.

**Comment by lanierc** [comment]
@chriswhilar 

> I do notice that the incoming video stream from iOS safari is very pixelated at times throughout the call.

This is part of the issue that I see, is a lot of pixelation (compared to normal when going from chrome to chrome. This happens on both iOS and macos for me if that helps?

**Comment by lanierc** [comment]
> Hi @lanierc,
> 
> Can you check if you see the same behavior using the groupId call concept?
> 
> Thanks,
> Marius

Hi Marius, sorry to keep you waiting on this question.

We are using the groupId call concept in our project, so this behaviour does happen with this as well.

**Comment by akania** [comment]
Hi @lanierc , we've been working on quality fixes and published couple of versions that address various issues - can you please use latest ( https://www.npmjs.com/package/@azure/communication-calling/v/1.1.0-beta.2 ) and try again your scenario, please repro findings together with iOS(Safari) and Chrome versions
We're continuously testing on various versions and we don't see any issues currently

**Comment by mariusu-msft** [comment]
Closing issue. Please try latest BETA SDK which addresses various quality issues.
