### ISSUE TITLE
[Android] Can not increase/decrease group call volume

### ISSUE THREAD

**Issue by kdhuynh** [Azure/Communication#104]
While using the Android ACS SDK I encountered the following issue:
Once there is an ongoing group call, started by performing CallAgent#join, the volume of of the call does not seem controllable. Using the physical volume buttons to change the system's media/call volume did not effect the volume of the group call. This was consistently reproducible on my Pixel 3 test device.

Is this expected?

It seems there is no api provided by ACS to modify the call volume either, so currently I have not found any way to modify the volume of the call.

**Comment by mariusu-msft** [comment]
@kagbakpem can you take a look please?

**Comment by kagbakpem** [comment]
@kdhuynh, are all devices you're joining the call with using the Android SDK? I've tried reproducing the issue with a device on Android and 2 and 3 endpoints on web and increasing the volume on Android device worked fine. Can you please elaborate on this, share a call id and also send us logs of recent try when you can.
Thanks

**Comment by kdhuynh** [comment]
@kagbakpem That's correct, I'm using two pixel 3 devices and both are using the Android ACS SDK. I'm using the default device speakers on both devices. Adjusting volume with a bluetooth earpiece connected works as expected, it is only when trying to use the phone's own speakers that I encounter this issue

Steps I'm using to reproduce:
1) Set Device 1 volume to 0 for all volume channels (media, call, notification, alarm)
2) Join call using Device 1
3) Join call using Device 2
4) Speak into microphone on Device 2
5) I expect to hear no sound from Device 1 speakers, but I hear my voice coming from Device 1 speakers

Call ID: c2582de6-ca16-4274-8db6-8c85dcc51e25
I've attached all the logs files I could find after trying to alter the volume during an ongoing call.
[ACS Logs.zip](https://github.com/Azure/Communication/files/5556384/ACS.Logs.zip)

**Comment by kagbakpem** [comment]
@kdhuynh, apologies for not getting back earlier. We're in a middle of a release at the moment. I'll take a look at this tomorrow, Nov 18th, PST and will get back to you before EOD.
Thanks

**Comment by kdhuynh** [comment]
Sounds good, thanks for letting me know
Hope your release goes smoothly

Also I just want to emphasize that I'm only able to reproduce this issue using a google pixel 3 device, I was not able to reproduce with a samsung device

**Comment by kagbakpem** [comment]
Hello @kdhuynh, we do not have a Pixel 3 device readily available so won't be able to investigate this issue for a while. Just to make sure i got this right, this issue is only reproduceable on a Pixel 3 at the moment as far as you're aware?
Thanks

**Comment by kdhuynh** [comment]
Correct, when using a physical device, I was only able to reproduce using a physical Pixel 3
However, I can also reproduce using an Android Studio Emulator. I was able to reproduce using a Pixel 4 emulator running API 30 (Android 11.0, CPU x86_64).

**Comment by kagbakpem** [comment]
@kdhuynh, apologies for the delay. I was able to reproduce the issue on x86_64 simulator. We're currently looking into it and will keep you posted on our findings.

Thanks

**Comment by kdhuynh** [comment]
Hi @kagbakpem, has there been any update on this issue?

**Comment by kagbakpem** [comment]
Not yet, @kdhuynh. I've created a [WI](https://skype.visualstudio.com/SPOOL/_workitems/edit/2370936) for it and will be looking into it soon.

**Comment by kdhuynh** [comment]
Sounds good, thank you

**Comment by kagbakpem** [comment]
@kdhuynh, you can use the volume control API from Android to target the the voice call stream when the hardware volume controls being used. Take a look at references [here](https://developer.android.com/reference/android/app/Activity.html#setVolumeControlStream%28int%29).
A Code snippet like this in an Activity within your app should help out.
```java
        // Set Hardware volume controls to increase the call volume.
        setVolumeControlStream(AudioManager.STREAM_VOICE_CALL);
```
