### ISSUE TITLE
Video freeze issue on desktop client from mobile to desktop when mobile browser loses focus

### ISSUE THREAD

**Issue by lanierc** [Azure/Communication#105]
**Describe the bug**
When a mobile user navigates away from the browser (either to home screen or another app), when the browser regains focus, the desktop user sees a frozen frame of video from the mobile caller.

**To Reproduce**
1. Open a call between a mobile browser and a desktop browser
2. Return to home screen or move to another app on mobile.
3. Return to browser on mobile.

**Expected behavior**
Mobile camera should either still be broadcasting when browser loses focus (if possible with OS permissions) or disconnect webcam and reconnect upon refocus

**Desktop (please complete the following information):**
 - OS:  Desktop (macOS Catalina)
 - Browser Chrome (macOS/Android)/Safari (iOS)
 - Version Current

**Smartphone (please complete the following information):**
 - Device: iPhone XR + Pixel 3 XL
 - OS: iOS 14.1 + Android 11
 - Browser Chrome (Android) + Safari (iOS)
 - Version Current

**Additional context**
Current workaround we've used is to check if user is on a mobile platform and run a hangup function if the user leaves the browser. Ideally it would be better if the caller can be retained within the call and just return to normal usage upon return to browser focus.

**Comment by ProbablePrime** [comment]
Hey @RinaRish Could you take a look at this?

**Comment by RinaRish** [comment]
Hi @lanierc! Thanks for reporting the issue. The engineering team will take a look and will get back to you

**Comment by fizampou** [comment]
This is expected browser behavior.
