### ISSUE TITLE
[iOS] Join & Call needs delegate immediately

### ISSUE THREAD

**Issue by devgokhan** [Azure/Communication#107]
Hi.

I faced this problem one time. Joined to the session however  I couldn't get state because it was too late so I couldn't continue the next steps. I am doing something like starting local video stream and hiding welcome screen after state connected received but when I can't catch the state updates I am unable to doing it. And when I missed it, and press the join button which calls join call delegation returns .none state so all my business code unable to work..

Current code:
```
self.call = self.callAgent?.join(with: groupCallContext, joinCallOptions: options)
if let call = self.call {
    call.delegate = self
     ...
```

I think above code should change like this;
 ```
self.call = self.callAgent?.join(with: groupCallContext, joinCallOptions: options, delegate: self)
```

I suggest delegate the call object immediately before too late. I think it should be delegated when call object is initialized and delegate should set before call other features like joining/connecting etc.
Note: I am newly using this framework, just one time I saw call delegation couldn't not catched the connected state. I think this is happened because my user connected very fast before call delegation has been set.

**Comment by mariusu-msft** [comment]
This is good feedback, we'll take this into consideration. @rorezende @sankum-msft 

That being said - we currently expect that after stetting any delegate, developers check the current state of the object model:

Your call above would become:
```swift
self.call = self.callAgent?.join(with: groupCallContext, joinCallOptions: options)
if let call = self.call {
    call.delegate = self
    // Process call.state here to inform UI changes
    }
```

Can you please let us know if this works as expected?

**Comment by devgokhan** [comment]
Hi @mariusu-msft 

Thank you for solution. Yes it resolves any this kind of problems. If you do my suggestion next release users will not need do same things twice.  I changed the code: 
```
 self.call = self.callAgent?.join(with: groupCallContext, joinCallOptions: options)
 if let call = self.call {
      call.delegate = self
      if call.state == .connected {
            self.connectedContinue()
       }
   ...

    func onCallStateChanged(_ call: Call!, args: PropertyChangedEventArgs!) {
        switch call.state {
        case .connected:
            self.connectedContinue()
            break
     ...

func connectedContinue() {
       // Below "if" code important for prevent working twice.
        if self.startView.isHidden == false {
            self.startView.isHidden = true
            ...

```
 I was also did before this for remote participant video check. Same thing happened here too.  Problem was when I delegate remote participant in some cases onVideoStreamsUpdated called before remoteParticipant delegation has been set on onRemoteParticipantsUpdated. So my solution was (remoteVideStreamsJob method does the job for showing remote person video on view) :
```
func onRemoteParticipantsUpdated(_ call: Call!, args: ParticipantsUpdatedEventArgs!) {
        if call.remoteParticipants.count > 0 {
            for item in self.remoteParticipants {
                item.delegate = nil
            }
            self.remoteParticipants.removeAll()
            for item in call.remoteParticipants {
                self.remoteParticipants.append(item)
                item.delegate = self
                self.remoteVideoStreamsJob(remoteParticipant: item)
            }
        }
}

func onVideoStreamsUpdated(_ remoteParticipant: RemoteParticipant!, args: RemoteVideoStreamsEventArgs!) {
        self.remoteVideoStreamsJob(remoteParticipant: remoteParticipant)
}
```

Your suggestion resolves my issue. You can close this if you want or if you will do something about that this issue can stay open.  Thanks again.

**Comment by sankum-msft** [comment]
Created enhancement work item AB#2319476
