### ISSUE TITLE
How to send SMS and Email

### ISSUE THREAD

**Issue by shaijut** [Azure/Communication#11]
May I know when and how I can send SMS and Email using Azure communication services ? 

Can anyone show me a simple demo in C# or Javascript ?

**Comment by NMuravlyannikov** [comment]
@shaijut  we are targeting availability of the Phone numbers (required to send an SMS) in October.

**Comment by shaijut** [comment]
Nice, May I know the date please,  I am planning to use it in a Azure Hackathon project ? Or I will be using Twilio.

**Comment by NMuravlyannikov** [comment]
For email we don't have the timeline now

**Comment by NMuravlyannikov** [comment]
@shaijut  beginning of October, we can onboard you to the private preview of the feature. Please send me email if you are interested to onboard to private preview

**Comment by shaijut** [comment]
Yes I am interested if i can use it with Azure free trial account, Which email id to send  ?

**Comment by NMuravlyannikov** [comment]
Please send to phone@microsoft.com @Prakulka  will be your onboarding buddy

**Comment by shaijut** [comment]
> For email we don't have the timeline now

Glad to hear that you have Email also in your Plan. Normally I use Mailgun for sending emails, It would be good if you could provide a options to send email easily using any Programming language.

Is there any other Azure services to send email ?

**Comment by Prakulka** [comment]
Hello,

Thank you for your email.

Here are some resources to help you get started with Azure Communication Services SMS:

  1.  SMS Overview - https://docs.microsoft.com/en-us/azure/communication-services/concepts/telephony-sms/concepts
  2.  SMS Quickstart - https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/telephony-sms/send?pivots=programming-language-csharp
  3.  Azure Communication Services Capabilities - https://azure.microsoft.com/en-us/services/communication-services/#security

Please note that, the Preview for availability of SMS SDKs and Phone numbers is targeted for early October. Please fill this form to be a part of our preview and try out the SMS functionality - preview access to Azure Communication Services<https://aka.ms/ACS-EarlyAdopter>. You should be able to access these features with your Azure Free trial.

Regarding Email capability, we do not have a timeline at the moment but please keep checking this page for current and upcoming features https://docs.microsoft.com/en-us/azure/communication-services/.

Please let me know if you have any questions.

Thank you,
Pranita

**Comment by Prakulka** [comment]
@shaijut sorry for my earlier comment about free trials. That is an upcoming functionality for the next year. As part of public preview, you will not be able to access SMS using Azure free trial. If you have requested access for private preview here https://aka.ms/ACS-EarlyAdopter you can try out the functionality for free.

**Comment by tophpalmer** [comment]
@shaijut I'm closing this issue. Please re-open as appropriate.
