### ISSUE TITLE
[iOS] `ACSRendererView` Issues when joining a call with a reused `groupId` 

### ISSUE THREAD

**Issue by ryanespiritu** [Azure/Communication#111]
**Describe the bug**
When joining a call with a `groupId` that was previously used, the `ACSRendererView` for a remote participant that was also previously in the call will be blank.

**To Reproduce**
1. On two separate devices, join a call using a given `groupId` (make sure you join with video)
2. Create `ACSRendererView`s for each participant and add them to the view hierarchy 
3. Remove `ACSRendererView`s from the view hierarchy, dispose their respective renderers, and hang up the call on both devices
4. Repeat steps 1-2
5. **Observe:** That the `ACSRendererView` will be blank for remote participants 

**Expected behavior**
The `ACSRendererView`s should be rendered properly.

**Smartphone (please complete the following information):**
 - Devices: iPhone X iOS14.1, iPhone 11 Pro iOS13.2.3

**Comment by mariusu-msft** [comment]
This is an odd issue, since if you hangup on 3) it's considered a new call when you do 4.

@sankum-msft can you investigate please?

**Comment by terrychen1122** [comment]
@mariusu-msft by "old issue", did you mean this is a known issue to the team?

**Comment by mariusu-msft** [comment]
@terrychen1122 "odd" issue. 

This is not expected, between two call instances there's nothing being reused internally in respect of video stream state.

@sankum-msft will be investigating next week

**Comment by sankum-msft** [comment]
Hi @terrychen1122, I was not able to repro this issue using iPhone XS or simulator.

From the description, it seems like the `Renderer` wasn't disposed off properly. Please note that you need to dispose `Renderer`s for both incoming video and preview of local video, if you have one. After hangup, if you still see the green dot in iPhone's status bar (which indicates camera is in use), that would mean that the `Renderer` corresponding to `LocalVideoStream` was not disposed.

If the above is not helpful in your case, please share logs from your device. You can follow [this guide](https://docs.microsoft.com/en-us/azure/communication-services/concepts/troubleshooting-info?tabs=csharp%2Cios%2Cdotnet#tabpanel_CeZOj-G++Q-3_ios) to collect logs.

**Comment by ryanespiritu** [comment]
Hi @sankum-msft, thank you for your response. I just double checked and we are indeed disposing both the local and remote participant video renderers upon hangup of a call. The green dot also disappears once we exit the call.

I wasn't sure which `.blog` file would be the most helpful, so I've attached all of the ones in my app container: 
[ACS_logs.zip](https://github.com/Azure/Communication/files/5598920/ACS_logs.zip)

**Comment by sankum-msft** [comment]
In your app, you are sharing a `LocalVideoStream` object between multiple calls. There is a bug in `LocalVideoStream` where it doesn't start properly in this re-use case. I've opened an internal bug ( AB#2325309 ) to get this fixed. For now, workaround is to create/destroy LocalVideoStream when you start/end a call.

Please confirm that the workaround works for you.

**Comment by ryanespiritu** [comment]
Hi @sankum-msft thanks for your help, I've verified that this workaround fixes the issue for us

**Comment by sankum-msft** [comment]
Fix has been merged for this issue and will be included in the next release.

**Comment by sankum-msft** [comment]
Closing this issue as the fix is included in [1.0.0-beta.8](https://github.com/Azure/Communication/releases/tag/v1.0.0-beta.8) release of the ACS iOS SDK. Please re-open if issue persists for you after the upgrade.
