### ISSUE TITLE
[iOS] Bundle invalid error during upload to the App Store

### ISSUE THREAD

**Issue by devgokhan** [Azure/Communication#113]
Hi. I am tried to upload a new test package to TestFlight. To do this I was uploading to App Store. Then this message occurred:

ERROR ITMS-90058: "This bundle is invalid. The value for key CFBundleVersion [1.0.0-beta.5] in the Info.plist file must be a period-separated list of at most three non-negative integers. Please find more information about CFBundleVersion at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleversion"

![Screen Shot 2020-11-19 at 17 52 09](https://user-images.githubusercontent.com/8233432/99682434-3eab4100-2a90-11eb-95f2-a53be4f89e1b.png)

My application informations are correct and doesn't includes 1.0.0-beta.5.. 
This problem occurs because of Azure frameworks. I am sharing Podfile.lock below:

```
  - AzureCommunication (1.0.0-beta.5):
    - AzureCore (~> 1.0.0-beta.5)
  - AzureCommunicationCalling (1.0.0-beta.5):
    - AzureCommunication (~> 1.0.0-beta.5)
  - AzureCore (1.0.0-beta.5)
```

My pod file:
```
platform :ios, '12.0'
use_frameworks!
...
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Azure/azure-sdk-for-ios.git'
  pod 'AzureCommunicationCalling', :podspec => 'https://raw.githubusercontent.com/Azure/azure-sdk-for-ios/master/AzureCommunicationCalling.podspec'
  pod 'AzureCommunication', :git => 'https://github.com/Azure/azure-sdk-for-ios.git', :branch => "master"
  pod 'AzureCore', :git => 'https://github.com/Azure/azure-sdk-for-ios.git', :branch => "master" 
...
```

Could you please release fast fix for this? We are unable to test our app and unable to upload new app currently...

**Comment by tophpalmer** [comment]
Hey @devgokhan , @raosanat from our team is investigating this issue now, thank you for reporting.

**Comment by mariusu-msft** [comment]
Hi,

@devgokhan we will be releasing a fix for this today.

Thanks for your report.

-Marius

**Comment by mariusu-msft** [comment]
@devgokhan please give the latest release a try and let us know if it fixes your issue.

**Comment by devgokhan** [comment]
Hi @mariusu-msft how can I download latest release. I can't see any information anywhere?
https://github.com/Azure/Communication/tree/master/releasenotes
https://github.com/Azure/Communication/tags

I saw beta 6 4 days ago.. Do you mean this?

**Comment by mariusu-msft** [comment]
@devgokhan, beta.6 was published today. Yes that's the latest.

You can grab it from https://github.com/Azure/Communication/releases/tag/v1.0.0-beta.6 or from Cocoapods with the spec you used. The podspec has been updated .6, so `pod update` should download .6 for you.

```
Azure Communication Calling iOS SDK version 1.0.0-beta.6
@raosanat raosanat released this 11 hours ago
```

Note the bug fix in the release notes:
`Info.plist has version following semantic version schema for CFBundleVersion and CFBundleShortVersionString entries (#113).`

**Comment by devgokhan** [comment]
Hi @mariusu-msft. Latest release fixed this problem. We successfully uploaded to the App Store. Thank you
