### ISSUE TITLE
Call end reason=NoNgcEndpoint

### ISSUE THREAD

**Issue by rdweaver** [Azure/Communication#114]
**Describe the bug**
I am having intermittent trouble with my calls to an acs user not going through, and getting two error messages in response.

> [CallClient][ACSCall{e8d39bfa-05e1-492c-9b7d-bf0f2b336d89}{Disconnected}] Call end reason=NoNgcEndpoint, code=480, subCode=10037
> [CallClient][ACSCall{341b74c8-5977-4020-8030-680e7b5d117a}{Disconnected}] Failed to start the call,[object Object]

**To Reproduce**
1. create callClient
`      const tokenCredential = new AzureCommunicationUserCredential(userToken);`
       `let callAgent: CallAgent = await callClient.createCallAgent(tokenCredential);`
2. Set callOptions `       const callOptions = {
        videoOptions: {
            localVideoStreams: undefined
        },
        audioOptions: {
            muted: false
        }` 
3. Call the user. userIdent.Id is a valid acs user id like '8:acs:b4361611-4228-4645-b585-ac5f8acb6556_00000006-811d-ae1e-e1ae-1d3a0d0000e8' 
`callAgent.call([{communicationUserId: userIdent.id}], callOptions);` 
4. Get the two error messages above in the console.
**Expected behavior**
I would expect the call to go through to the other user

**Comment by mariusu-msft** [comment]
@rdweaver to make this easier to debug, we are in the process to document the error codes, will have something published soon. cc: @RinaRish 

Regarding your error,`Call end reason=NoNgcEndpoint, code=480, subCode=10037` this means the remote user was not online.

Do you have another browser tab with the other user logged in?

Thanks,
Marius

**Comment by rdweaver** [comment]
yes I do have another browser window open with the user logged in.

**Comment by mariusu-msft** [comment]
It should not go automatically offline. Can you share logs from the endpoint that is not ringing?

This is how you can gather logs:
https://docs.microsoft.com/en-us/azure/communication-services/concepts/troubleshooting-info?tabs=csharp%2Cjavascript%2Cdotnet#enable-and-access-call-logs

Please make sure you capture logs (open console) before the time you do `callClient.createCallAgent`.

This should tell us why the user does not appear online.

**Comment by rdweaver** [comment]
@mariusu-msft Do you have a way that I can submit the logs privately?

**Comment by tophpalmer** [comment]
Hi @rdweaver , you can submit logs as part of a support ticket [using these instructions](https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request). If you don't have an eligible support plan please let us know and we'll scrum on another method.

**Comment by rdweaver** [comment]
Here are the logs for the us
[user627 localhost-1605822382566.log](https://github.com/Azure/Communication/files/5569935/user627.localhost-1605822382566.log)
er that does not appear online.

**Comment by mariusu-msft** [comment]
```
index.js:1 Error: A Call Agent instance has already been created.Please dispose of it before creating a new Call Client instance
    at f.<anonymous> (sdk.bundle.js:247)
    at Generator.next (<anonymous>)
    at sdk.bundle.js:247
    at new Promise (<anonymous>)
    at o (sdk.bundle.js:247)
    at f.createCallAgent (sdk.bundle.js:247)
    at f.<anonymous> (sdk.bundle.js:4)
    at Generator.next (<anonymous>)
    at sdk.bundle.js:4
    at new Promise (<anonymous>)
    at i (sdk.bundle.js:4)
    at f.o.value (sdk.bundle.js:4)
    at sideEffects.ts:155
```

This looks suspicious. Are you trying to run within the same browser window? Or create multiple CallAgent instances? We currently do not support multiple CallAgent instances.

The current limitation is 1 active CallAgent\browser page.

Can you try same setup with this restriction in place please?

**Comment by rdweaver** [comment]
Yes that error was the culprit. When I resolved that, it is working fine.
Thanks for your help! I am going to close this issue.

**Comment by mariusu-msft** [comment]
Great to hear.

@rdweaver did the error get bubbled up to console regardless of having logs enabled? I believe for fatal errors as such we should be bubbling up exceptions.

**Comment by rdweaver** [comment]
Yes the "A Call Agent instance has already been created" error was showing in console regardless of logs. I had ignored/not paid attention to it... :(
