### ISSUE TITLE
When i use hangup method ,i have some problem.

### ISSUE THREAD

**Issue by ozanurkn** [Azure/Communication#115]
My problem is when i want to close meeting for when i  press to end button, call backpressed() method or in my onDestroy() method i killed my activity in there. when i try to same logic, my local camera isn't work like before. 

Step by step my behavior like this.

- First of all i was join meeting with my group id and comminicate with other person.
- After i closed the meeting with my stopCall() method.
stopCall() method's content;
     remoteRenderer.dispose();
     localRenderer.dispose();
     call.stopVideo(localVideoStream).get();
     call.hangup(new HangupOptions());
- After i turned my MainActivity. I try same behavior, i didn't see myself on my localView but other person saw to me on realtime meeting but i didn't see other person in my remoteView.

I don't understand what is the wrong.
Thanks.

**Comment by mariusu-msft** [comment]
@kagbakpem, @sankum-msft can you take a look please?

@ozanurkn can you share how you open and render the localVideoStream?

Thanks,
Marius

**Comment by ozanurkn** [comment]
Sure,

```
`private void previewCamera() {
        desiredCamera = deviceManager.getCameraList().get(0);
        Log.i("DEBUG:", "previewCamera Method runnnig");
        previewVideoStream = new LocalVideoStream(desiredCamera, this);
        VideoOptions videoOptions = new VideoOptions(previewVideoStream);
        previewRenderer = new Renderer(previewVideoStream, this);
        View uiView = previewRenderer.createView(new RenderingOptions(ScalingMode.Crop));
        getBinding().clPreMeetingVideoView.removeAllViews();
        getBinding().clPreMeetingVideoView.addView(uiView);

    }`
```
this code just for preview and i determinated some feature for meeting like open cam ,close mic. It didn't share anything. Screen Shot at below.

![Screenshot_2020-11-19-20-28-41-216_preview_call](https://user-images.githubusercontent.com/11214217/99704248-2b589f80-2aa9-11eb-9655-aaf864103e3a.png)

'KATIL' mean join . When i press the join button. 

```
previewRenderDispose();
GroupCallContext groupCallContext = new GroupCallContext(UUID.fromString("e6e81c00-2327-11eb-b62f-bd0bd57616dd"));
JoinCallOptions joinCallOptions = new JoinCallOptions();
call = agent.join(this, groupCallContext, joinCallOptions);
getViewModel().setmIsLoading(true);
call.addOnCallStateChangedListener(p -> callStateChanged(call.getState()));
```
When the callState is be Connected, I show the meeting Ui. I was set the all feature like preview screen. (is cam open? or is mic open etc..)

I got remote participant stream like this.

 ```
private void getRemoteCamera() {
        Log.i("DEBUG:", "getRemoteCamera method running.");
        RemoteParticipant remoteParticipant = call.getRemoteParticipants().get(0);
        RemoteVideoStream remoteParticipantStream = remoteParticipant.getVideoStreams().get(0);

        remoteRenderer = new Renderer(remoteParticipantStream, this);
        View mView = remoteRenderer.createView(new RenderingOptions(ScalingMode.Fit));
        getBinding().clCurrentMeetingRemoteView.removeAllViews();
        getBinding().clCurrentMeetingRemoteView.addView(mView);
    }
```
i did localVideoStream like this.

```
private void callWithCamera() {
        desiredCamera = deviceManager.getCameraList().get(0);
        currentVideoStream = new LocalVideoStream(desiredCamera, this);
        VideoOptions videoOptions = new VideoOptions(currentVideoStream);
        localRenderer = new Renderer(currentVideoStream, this);
        View mView = localRenderer.createView(new RenderingOptions(ScalingMode.Crop));

        getBinding().clCurrentMeetingLocaleView.removeAllViews();
        getBinding().clCurrentMeetingLocaleView.addView(mView);
        StartCallOptions startCallOptions = new StartCallOptions();
        startCallOptions.setVideoOptions(videoOptions);
        try {
            videoOptions = new VideoOptions(currentVideoStream);
            Future startVideoFuture = call.startVideo(currentVideoStream);
            startVideoFuture.get();

        } catch (ExecutionException | InterruptedException e) {
            e.printStackTrace();
        }
    }
```
thanks.

**Comment by sankum-msft** [comment]
I will investigate this next week.

**Comment by ozanurkn** [comment]
Hi, my code is working now with beta.2. I will check all think and approve beta.4 version.

Thanks.
Ozan

**Comment by sankum-msft** [comment]
Happy to know that you are unblocked. If possible, please share what you were doing wrong for future reference.

I'm closing this issue as you are unblocked now. Feel free to re-open if issue persists.
