### ISSUE TITLE
[Mobile] Sending user display name

### ISSUE THREAD

**Issue by devgokhan** [Azure/Communication#116]
Hi. How can we send our display user name to the meeting? 
When I join a meeting my display name will be empty in web. But I can see web users display name.
How we can send it? If this feature not available can will it be added?

**Comment by mariusu-msft** [comment]
Adding @akania 

This feature should be available on our December release. We will update this thread after release.

Note, that while Display Name will be there, we will generally recommend that applications do user lookups if such information is available.

Thanks,
Marius

**Comment by devgokhan** [comment]
Hi @mariusu-msft thank you. We will be waiting next release to use this feature then.

**Comment by ashishvirani7** [comment]
Hey @devgokhan,
This feature is available in latest release for mobile! Below is version number which has this feature:
Android: 1.0.0-beta.5
iOS: 1.0.0-beta.7

Thanks,
Ashish

**Comment by devgokhan** [comment]
Yes it is resolved in beta 7. To add displayName needs to set CallAgentOptions. 
```
self.callAgentOptions = CallAgentOptions()
self.callAgentOptions?.displayName = self.userFullName
self.callClient?.createCallAgent(userCredential: self.userCredential, options: callAgentOptions)
```
