### ISSUE TITLE
[iOS] About CocoaPods

### ISSUE THREAD

**Issue by terrychen1122** [Azure/Communication#117]
I saw from the release note that the lates release is now available for cocoapods. When I looked for the SDK on https://cocoapods.org/, I didn't see it. Any reasons why I am not seeing it

**Comment by mariusu-msft** [comment]
We are waiting for Azure SDK to publish multiple Specs to Trunk. That should happen Monday or Tuesday next week.

**Comment by terrychen1122** [comment]
awesome, thank you. Will keep an eye on that.

**Comment by mariusu-msft** [comment]
https://github.com/CocoaPods/Specs/blob/a3d59f7f97f398a5196e039bd71f9c2eb0394143/Specs/f/c/c/AzureCommunicationCalling/1.0.0-beta.6/AzureCommunicationCalling.podspec.json

This has been published to CocoaPods Specs repo. It may take a couple of days to show up on https://cocoapods.org/

Closing issue
