### ISSUE TITLE
[Typescript] "Window undefined" error on server when calling both CallClient + LocalVideoStream

### ISSUE THREAD

**Issue by lanierc** [Azure/Communication#118]
**Describe the bug**
If you import `CallClient` and `LocalVideoStream` of `@azure/communication-calling` package and write the code, a window undefined error occurs on the server side when running.

**To Reproduce**
In React:
```
import { CallClient, LocalVideoStream  } from '@azure/communication-calling'
```

**Expected behavior**
Importing both should not cause error.

**Additional context**
In order to avoid this currently, `CallClient` and `LocalVideoStream` should be lazy loaded when needed.

```
const createLocalVideoStream = async (videoDeviceInfo: VideoDeviceInfo) => {
  const azureCommunicationCallingModule = await import('@azure/communication-calling')
  const { LocalVideoStream } = azureCommunicationCallingModule
  return new LocalVideoStream(videoDeviceInfo)
}
```

```
const initCallAgent = async () => {
  const AzureCommunicationCallingModule = await import('@azure/communication-calling')
  const { CallClient } = AzureCommunicationCallingModule
  callClient = new CallClient(options)
  //
}
```

**Comment by mariusu-msft** [comment]
Hi,

Currently the library only works in browser environments, and window is required to access WebRTC browser APIs.

Can you describe what functionality you are looking for from a Node.JS SDK?

Thanks,
Marius

**Comment by lanierc** [comment]
Hi Marius,

Sorry for the late reply. Currently we are using React with SSR to load into the component that contains the video call. This above import behaviour causes this `Window undefined` issue, which, as you said, is required for ACS to run properly. The only way currently we've found to circumvent this issue is to lazy load each import into functions where they are needed. It would of course be more DRY for us to just import them both globally across the entire component rather than lazy loading them in each function the would need to be called.

**Comment by mariusu-msft** [comment]
I believe you will have to decouple the rendering from SDK functions which require window, and ensure you load those directly into the Web App as dependencies that are not included into the React SSR project.

**Comment by mariusu-msft** [comment]
I am closing this for the moment. Please reopen if you have more questions on this subject
