### ISSUE TITLE
Provide Chat and Video Calling Examples In JavaScript or C#

### ISSUE THREAD

**Issue by shaijut** [Azure/Communication#12]
I can see below examples in React , Can anyone give same demos In JavaScript or C# ?

- Chat Hero Sample - Demonstrates rich text chat
- Calling Hero Sample - Demonstrates voice and video calling

**Comment by ddematheu2** [comment]
Take a look at quickstarts for Javascript  in our official documentation: https://aka.ms/communication-services-docs.

**Comment by RinaRish** [comment]
Hi! C# sample is not available yet

**Comment by bashan-git** [comment]
Please see Calling Client Libraries  Here.
https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/voice-video-calling/calling-client-samples

Please Chat Here
https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/chat/get-started?pivots=programming-language-csharp

**Comment by shaijut** [comment]
Nice 👍 I Just heard about Azure communication services today at Ignite by Satya, Thank you guys for quick response, JavaScript example will do. Excited to use Azure communication services. :)

**Comment by shaijut** [comment]
> Take a look at quickstarts for Javascript in our official documentation: https://aka.ms/communication-services-docs.

Can I get a sample for Group video call between 2 people in Javascript , Current example is in React. its better give examples in main Programming languages like Javascript, C# etc because  any Javascript frameworks will be outdated in long run.

**Comment by tophpalmer** [comment]
Hey @shaijut thank you for the feedback. We're talking about this within the team and will bounce back here with direction on a pure JavaScript sample tomorrow. FYI @ddematheu , @chriswhilar

**Comment by sphenry** [comment]
@shaijut group call is almost exactly the same as 1:1 call in the quickstart, instead of 'call' use 'join':

``` javascript
    //create call options and group call context
    const placeCallOptions = {videoOptions: {camera: videoDeviceInfo}, audioOptions: { muted: false}};
    const groupContext = {groupId: "INSERT-GROUP-NAME-HERE"};

    //Join call
    call = callClient.join(groupContext, placeCallOptions);
```

**Comment by tophpalmer** [comment]
@shaijut I'm closing this, I think we got to a good spot but please re-open if appropriate.

**Comment by AnsariNaushad** [comment]
**Provide Chat and Video Calling Examples In JavaScript or C#**
Hi Team,
Azure communication service for call and chat is available in "React based user interface which uses Redux".
https://docs.microsoft.com/en-us/azure/communication-services/samples/chat-hero-sample

I want to use this in my .net core application.
When I can expect C#, Java Script code for communication service.
