### ISSUE TITLE
I can't choice my meeting output voice.

### ISSUE THREAD

**Issue by ozanurkn** [Azure/Communication#121]
Hi, 

When i join a meeting, i can't choice speaker from output. It has just default output. I tried with headphone. It is working but i need to change output voice like speaker. Is it possible?

`deviceManager.getSpeakerList().size` equal 1. this is default option.

thanks.

**Comment by mariusu-msft** [comment]
Hi @ozanurkn,

On which platform is this? Android?

Thanks,
Marius

**Comment by ozanurkn** [comment]
Hi @mariusu-msft , my platform is Android. 

Thanks.
Ozan

**Comment by kagbakpem** [comment]
Hello @ozanurkn, thanks for reporting this. We unfortunately do not support Audio devices enumeration and setup for Android through the Calling SDK. This needs to be managed by the app using the OS APIs. Apologies for the delay in responding here.
Thanks
