### ISSUE TITLE
[iOS] Remote Participant Count Unable To Updated Sometimes

### ISSUE THREAD

**Issue by devgokhan** [Azure/Communication#123]
We are testing Beta 6. When we tried, at the beginning we saw that we could't see anybody (no remote video available and remote participant count was zero) in a meeting, but our voices was available and we could hear each others. We couldn't do anything until it is fixed, we were unable to see eachothers, couldn't see the display names and also we could not understand how many people in the meeting..

I was debugging the code and I was watching the logs. And I said to second tester that leave the meeting and rejoin again. She did that however remote participant never changed. To understood situation I entered the web demo, with this way we became 3 person in a meeting however onRemoteParticipantsUpdated still didn't called and also participant count was zero. **In web even we are 3 person, 2 person was available and also web demo was strange as well. I am sure that 3 device works however people see 2 participant in web demo, zero participant in mobile** Anyway, I couldn't understand how it fixed after we tried with leaving and rejoining the meeting, it fixed and remote participant count update started working correctly.

Somethings wrong here. Seems not working correctly. Because it is not works correct, I am unable to see remote participant video and hide "no user available" text.. 

I think it happened in beginning of meeting. At first nobody was in meeting we entered but framework couldn't updated. After some people around sdk stared working correctly. This was strange experience but it is important, if remote participant update listeners will not works correct all the business codes unable to work. 

```
          ....
               self.call = self.callAgent?.join(with: groupCallContext, joinCallOptions: options)
                    if let call = self.call {
                        call.delegate = self
                        print("Meeting -> startCall() - call initialized so it must be joined.")
                        if call.state == .connected {
                            print("Meeting -> startCall() - startCall() state is currently connected so calling coonectedContinue")
                            self.hideLoading()
                            self.connectedContinue()
                        }
         ...

func onCallStateChanged(_ call: Call!, args: PropertyChangedEventArgs!) {
        switch call.state {
       ...
        case .connected:
            Utils.log("Meeting -> State Change: Connected")
            self.connectedContinue()
            break
        ...
    }

private func connectedContinue() {
      ...
            print("Meeting -> connectedContinue() Connected so Start View will be hidden and meeting page action starting..")
            self.startView.isHidden = true
       ...
            if let c = self.call {
                self.remoteParticipantUpdate(call: c)
            }
        }
    }

func onRemoteParticipantsUpdated(_ call: Call!, args: ParticipantsUpdatedEventArgs!) {
        self.remoteParticipantUpdate(call: call)
    }
    
    func remoteParticipantUpdate(call: Call) {
        print("Meeting -> remoteParticipantUpdate() remoteParticipants count: \(call.remoteParticipants.count)")
        if call.remoteParticipants.count > 0 {
            for item in self.remoteParticipants {
                item.delegate = nil
            }
            self.remoteParticipants.removeAll()
            self.findAndSetCameraInAllCallParticipants(call) // videoAlreadyFound = true and others will calls here - this metod setups remote video however because of participant count is always zero in this case, it cannot works
        } else {
            self.activeCameraShownRemoteParticipant = nil
            self.cleanRemoteParticipantView()
            self.noUserView.isHidden = false
            self.remoteParticipantMuteFieldView.isHidden = true
            self.shortUserNameField.isHidden = true
            self.userNameFieldView.isHidden = true
        }
    }
```

**Comment by devgokhan** [comment]
I can share group id if you need. We started meeting around 11:48 GMT +3 (26.11.2020)

**Comment by devgokhan** [comment]
We did new test today. Started at 13:40 GMT 3.. My friends started testing. There was 2 person was testing however they couldn't see each others. They were hear each other but remote participant was not updated and cameras disabled. Then I joined some minutes after.  Then remote participant seems fixed we were see some people camera videos. Anyway I also joined in web demo with this way 4 person was in meeting however in web demo it was 3 people available, in mobile there is 2 remote participant available so in mobile 3 people reference was active. But we were 4 people. Then we understand that we are unable to see 2. participant - but second participant could see us. So this means except second participant everybody sees each other correctly and even nobody see second participant we were hear her and also she was hear us and see us.

**Comment by devgokhan** [comment]
I was testing with simulator and device together before. Then we could start releasing testing packages in test flight. Then my other colleagues started testing. Anyway we were testing with same token, because we hadn't token changer api. Then oapi developers created one and started testing with different tokens per device. Seems it is fixed. Problem must e causing because using same token. We are still testing, after I am sure of this I will close this. But probably this problem causes because of same token usage.

**Comment by RinaRish** [comment]
Hi @devgokhan! I am closing this but feel free to reopen if the issue persists.
