### ISSUE TITLE
Fatal Exception: java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by ozanurkn** [Azure/Communication#124]
Hi,

I published my application apk from Firebase App Distribution. I saw a crash a device from firebase crashlytics.
This crash;

`Fatal Exception: java.lang.UnsatisfiedLinkError
No implementation found for com.azure.communication.calling.status com.azure.communication.calling.NativeLibrary.sam_call_client_create(com.azure.communication.calling.Out) (tried Java_com_azure_communication_calling_NativeLibrary_sam_1call_1client_1create and Java_com_azure_communication_calling_NativeLibrary_sam_1call_1client_1create__Lcom_azure_communication_calling_Out_2)`

You have idea about that issue.

Thanks.
Ozan

**Comment by kagbakpem** [comment]
hello @ozanurkn,

Our SDK currently supports x86_64 and arm64-v8a ABIs. Is it possible you're trying to use the SDK on a non supported ABI, like x86 or armeabi-v7a?

Thanks

**Comment by tompi** [comment]
This seems like the exact issue reported here:

https://github.com/Laerdal/Xamarin.AzureCommunicationCalling/issues/10

He got this on a galaxy note 8, LG Q5 and emulator, and I havent been able to repro or figure out whats happening...

**Comment by ozanurkn** [comment]
I found that issue. He got LG Q6 and it's android sdk version is 24. ACS support min sdk 26. I am thinking about that. 

Thanks.
Ozan

**Comment by kagbakpem** [comment]
@ozanurkn, ACS Calling SDK support Android SDL level 21 as minimum. So that shouldn't be the issue. Are you saying you solved the issue? If so, how? Please share your findings.

Thanks

**Comment by ozanurkn** [comment]
@kagbakpem i read doc. I saw there. I was thinking about min sdk version.

https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/voice-video-calling/getting-started-with-calling?pivots=platform-android

"Select Minimum client library of "API 26: Android 8.0 (Oreo)" or greater."

thanks.
Ozan

**Comment by kagbakpem** [comment]
Thanks, @ozanurkn. Will close this as its resolved now. If you have further questions, feel free to reach out.
