### ISSUE TITLE
[iOS] ACSRendererView layout is off after a device rotation

### ISSUE THREAD

**Issue by ryanespiritu** [Azure/Communication#127]
**Describe the bug**
Using autolayout to update the constraints of an `ACSRendererView` after a device rotation seems to update the `frame` correctly (verified this by checking to see if the `height` and `width` values were what I expected). However, visually, the `ACSRendererView` is not adhering to the new frame/constraint values; it overflows and looks off after a device rotation.

**To Reproduce**
1. Add `ACSRendererView` to view hierarchy and set constraints via autolayout
2. Rotate device/simulator
3. Observe that the `frame` is updated correctly by the autolayout constraints you set, but the visual appearance of the view is not reflecting the updated frame

**Expected behavior**
After a rotation, the updated `frame` values of the `ACSRendererView` should be accurately reflected in the visual appearance of the view.

EDIT: attaching a video for reference of the issue

![ACSRendererView](https://user-images.githubusercontent.com/71148942/100682902-fb708e00-332b-11eb-8212-8e76f1e2b7f4.gif)

**Comment by terrychen1122** [comment]
From my testing, this issue also exists with manually changing the frame when rotation happened (regardless auto-layout)

**Comment by sankum-msft** [comment]
Thanks for reporting the issue @terrychen1122 !

I was able to repro this in a more general form - resizing `RendererView` doesn't actually resize/reposition the drawing area. I have opened a bug (AB#2325318) on our board to get this fixed.

**Comment by sankum-msft** [comment]
Fix has been merged for this issue and will be included in the next release.

**Comment by sankum-msft** [comment]
Closing this issue as the fix is included in [1.0.0-beta.8](https://github.com/Azure/Communication/releases/tag/v1.0.0-beta.8) release of the ACS iOS SDK. Please re-open if issue persists for you after the upgrade.

**Comment by ryanespiritu** [comment]
Hey @sankum-msft, after bumping to the latest release the issue is fixed for physical devices but I still see some layout issues on simulator. 

Looks like the `ACSRenderView`'s frame is correct but the frame of the inner "gif" is off. See attached video:

https://user-images.githubusercontent.com/71148942/108439957-1f46c000-7207-11eb-9b7e-52f4516e38f8.mov
