### ISSUE TITLE
[iOS] Video freezing in landscape mode

### ISSUE THREAD

**Issue by devgokhan** [Azure/Communication#128]
Hi. My app orientation settings is Portrait only. When I rotate my phone 90 degree (to landscape orientation) my video is freezing in other participants. After rotate 90 degree again (to portrait orientation) my video is back and continues normally.  My local video still works in portrait and landscape orientation however other people can't see me, in their remote participant view my video is freezing. 

Extra note: Before join to the meeting if I use device in landscape orientation then I join the meeting, my video is not shown until rotate the device to portrait orientation.

-  In my local video it is changes to both orientation, however I want to use portrait mode only. How can I force the orientations as portrait only?
- Maybe it will be better if never tries to change orientation if app is portrait only..

I tried iOS to iOS meeting and also iOS to Web (Mac Safari).. Results same. In web, remote participant video is freezing if remote participant using their iPhone in landscape orientation

**Comment by sankum-msft** [comment]
Thanks for reporting this issue @devgokhan . I was able to repro this and have opened an bug (AB#2325411) to get this fixed.

**Comment by sankum-msft** [comment]
Fix has been merged for this issue and will be included in the next release.

**Comment by devgokhan** [comment]
Thank you. I think it is fixed in Beta 7. I checked seems like it is fixed however I will check it in 2 person meeting after I release test package.

**Comment by devgokhan** [comment]
Not fixed in Beta 7. My local video works correct. That is ok. However if my device in landscape mode,  remote participant can't see me because my video is frozen in their remote participant view.  When I back to portrait mode freeze stoping and video continues to work correctly...

**Comment by mariusu-msft** [comment]
@sankum-msft can you please try to reproduce this?

**Comment by hyounoo** [comment]
Same here
Video freezes on landscape and resume when back to portrait

**Comment by sankum-msft** [comment]
Beta 7 is the latest iOS SDK that was released in December. We are still working on the next release with this fix.

**Comment by tompi** [comment]
@sankum-msft This is still a problem in beta-8 for calls initiated from landscape mode. (rotation in-call seems to work now)

**Comment by sankum-msft** [comment]
I see. So your issue is a variation of what was reported here.

[1.0.0-beta.8](https://github.com/Azure/Communication/releases/tag/v1.0.0-beta.8) fixes the original issue reported here but doesn't address #178. So I'm going to close this one as resolved and reopen #178.
