### ISSUE TITLE
[iOS] Bitcode error in architecture arm64

### ISSUE THREAD

**Issue by devgokhan** [Azure/Communication#129]
I am able to build the code with bitcode when debugging in simulator. However if I archive the project to upload new package to the App Store or debug in device, then this error occurs:

`.../Pods/AzureCommunicationCalling/AzureCommunicationCalling.framework/AzureCommunicationCalling' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '.../Pods/AzureCommunicationCalling/AzureCommunicationCalling.framework/AzureCommunicationCalling' for architecture arm64`

If I disable bitcode in project settings, then I am able to debug in device, archive and upload to the App Store. 

Will you support bitcode soon? Do you have any plan for that or is it bug? It will be better if we can use this SDK with bitcode enabled mode.

**Comment by raosanat** [comment]
We do not support Bitcode at the moment. But we do have plans to support Bitcode in the future. But it may be post-GA. We will keep you posted. @RinaRish can you please create a card for this ?
