### ISSUE TITLE
(Android)When i lost my internet connection nothing happen

### ISSUE THREAD

**Issue by ozanurkn** [Azure/Communication#130]
Hi,
When i click to open the airplane mode, all video streamming was stopped. thats fine but i know nothing. cause ACS not response to me like CallState. I am thinking disconnected state will be call or maybe can add a new state in callstate for connecting loss state.

After that when i click to close airplane mode, video streamming not resume again. Is this possible provide to resume again.

Thanks.
Ozan

**Comment by mariusu-msft** [comment]
How long are you waiting for to get the call state change?

It may take upwards to 30s to 1minute.

When you disconnect from network we continue trying to send/receive media and reconnect you back for about a minute.

We’ll try to reproduce this and see what is happening. Can you let us know what you are after 30+ seconds?

Thanks,
Marius

**Comment by ozanurkn** [comment]
hi, when i open airplane almost after 30sec state changed as None.

Thanks.
Ozan

**Comment by mariusu-msft** [comment]
@ozanurkn for more than 30s this would be expected. It means that the call has forcefully disconnected.

We have the bug in the backlog we'll update you once we finish the investigation.

Thanks for your report!

**Comment by ankiarora** [comment]
@mariusu-msft Is there an update on this bug?

**Comment by kagbakpem** [comment]
With the latest version of the Android SDK (1.1.0-beta.1), the call state event indicating that the Call is disconnected is raised after some time (30-120s) in which case it's the responsibility of the App developer to tera down the call and UI appropriately.
