### ISSUE TITLE
[iOS] Everything getting weird after weird hang up/disconnect

### ISSUE THREAD

**Issue by devgokhan** [Azure/Communication#135]
I tried too much ACS meeting these days and I am still in development. In my some tries when I press hang up after that somethings getting weird. Normally if I press hang up, then app closes in a second and then I can rejoin again. However sometimes when I press hang up, I it takes more longer to do this (maybe 2-3 seconds) and everything started getting weird. If it happens I can't rejoin again until I close the app and reopen it again. It will never allows me to that. Rejoin group meeting will be unavailable and call back returns nothing it just waits. And also remote client sees that this user is still in meeting and this user video is frozen.  

This is the code when I press hang up or disconnected: 
 ```
private func close() {
       print("Meeting -> Closing..")
        if self.remoteParticipants.count > 0 {
            for item in self.remoteParticipants {
                item.delegate = nil
            }
        }
        self.remoteParticipants.removeAll()
        self.call?.delegate = nil
        self.timer?.invalidate()
        self.timer = nil
        self.targetRemoteParticipantView?.dispose()
        self.localVRendererView?.dispose()
        self.localRenderer?.dispose()
        self.remoteRenderer?.dispose()
        
        if let call = self.call {
            print("Meeting -> Hangup starting..")
            call.hangup(options: HangupOptions(), completionHandler: { [weak self] (error) in
                if let error = error {
                    Utils.log("Meeting -> Hangup error: \(error.localizedDescription)")
                }
                Utils.log("Meeting -> Hangup completed!")
                Utils.log("Meeting -> Will dismiss..")
                self?.dismiss()
            })
        } else {
            print("Meeting -> Will dismiss - there is no call avaible")
            self.dismiss()
        }
    }
```

**Comment by mariusu-msft** [comment]
@devgokhan does this issue persist after our GA releases? Please let us know if you can repro this on latest SDKs. I will close this, please re-open as needed. Thanks for your report!
