### ISSUE TITLE
Participant tile is visible for 2 minutes after patients leave from the call

### ISSUE THREAD

**Issue by vscherban** [Azure/Communication#136]
1.Join to the call with 3 patients
2.Join as a provider
3.1 patient leaves the call by closing the browser.
Expected result: Patient's video disappears with the related tile, after short time duration
Actual result: Patient's video is gone but tile remains for almost 2 minutes

![image](https://user-images.githubusercontent.com/19576040/101349578-905b1600-385b-11eb-80bd-d8fd6de45a43.png)

So here you can see tile named "Mikolaj Rys" It was me, I left the call, my camera video was cut, but tile remained for almost 2 minutes.

**Comment by akania** [comment]
@vscherban thank you for reporting, can you please repro and gather 'call id' ( https://docs.microsoft.com/en-us/azure/communication-services/concepts/troubleshooting-info?tabs=csharp%2Cjavascript%2Cdotnet#access-your-call-id )

I couldn't repro - I've tested locally with ACS user in a meeting with 2 other Teams users, ACS user closed the browser and he was immediately removed from Teams meeting

**Comment by akania** [comment]
I was able to repro - by closing the browser, patient prevents our SDK to send last terminating request to our platform, without that we'll keep user as part of the call roster for full 2minutes - only after that service will remove user from the roster.
Currently this is desired behavior on ACS side and can't be changed.

As a workaround I'd suggest to try and utilize onunload and/or onbeforeunload JavaScript events to control UX when user wants to leave the app? if user wants to do it - you can then invoke call.hangUp.

We'll work on our side to improve this, I'll update this thread with details once we'll have a solution in place
