### ISSUE TITLE
Hangup completionHandler not executed if State == ringing

### ISSUE THREAD

**Issue by nielscup** [Azure/Communication#137]
**Describe the bug**
If you hangup a call that is ringing, Hangup completionHandler is not executed

**To Reproduce**
1. Start call
2. Hangup call while ringing
3. **Result:** Hangup completionHandler is not executed

**Expected behavior**
Hangup completionHandler should be executed in order to cleanup and dispose the call, video, etc. 
**Additionally:** If I make a video call a second time (after Hangup completionHandler is not executed), **call.StartVideo hangs.**  

**Desktop (please complete the following information):**
 - OS: iOS
 - Xamarin.iOS

**Smartphone (please complete the following information):**
 - Device: iPhone/iPad

**Additional context**

**Comment by raosanat** [comment]
@nielscup Are you calling the `Reject` or `Hangup`  in this case?
If call hasn't been answered you should call `Reject` instead of `Hangup`.

**Comment by nielscup** [comment]
I am calling `Hangup` call in this case because I am ending an outbound call. According to [this documentation](https://docs.microsoft.com/en-us/objectivec/communication-services/calling/acscall) `Reject` is for an incoming call. And `Ringing` is the state of an outbound call, according to [this documentation](https://docs.microsoft.com/en-us/objectivec/communication-services/calling/acscallstate). Also, rejecting an outbound call does not make any sense to me, so I never would have guessed using `Reject` in this case. 

Having said this, I just tested using `Reject` instead of `Hangup` and this actually works...

**Comment by sankum-msft** [comment]
Hey @nielscup! Latest release of the SDK fixes this issue with `Hangup()`. Please try again and let us know if you have issues.
