### ISSUE TITLE
[iOS] ACSRendererView is blank after returning from background

### ISSUE THREAD

**Issue by ryanespiritu** [Azure/Communication#138]
**Describe the bug**
The `ACSRendererView` of a remote participant is blank after returning from background. 

**To Reproduce**
1. Join a call with another participant
2. Add the remote participant's `ACSRendererView` to the window/view hierarchy
3. Background the app
4. Once `UIApplicationWillResignActiveNotification` is received, dispose and release the `ACSRenderer`s for the remote participant, and remove the `ACSRendererView` from the window
5. Foreground the app and observe the the `ACSRendererView` is blank for the remote participant

**Expected behavior**
The `ACSRendererView` of the remote participant should not be blank after returning from background. 

**Smartphone (please complete the following information):**
iPhone 11 Pro, iOS 13.2.3

**Comment by sankum-msft** [comment]
> remove the ACSRendererView from the window

Are you creating a new `Renderer` and `RendererView` for the `RemoteParticipant` when app comes to foreground?

**Comment by ryanespiritu** [comment]
Hi @sankum-msft, yes we are creating new `ACSRenderer`s and `ACSRendererView`s via the array of `ACSRemoteVideoStream`s owned by each `ACSRemoteParticipant`

**Comment by ryanespiritu** [comment]
Hi @sankum-msft, was wondering if you had any updates for this ticket or if you needed any additional info from my side? Thanks

**Comment by sankum-msft** [comment]
I was not able to repro this issue. I am using `UIApplication.willResignActiveNotification` and `UIApplication.willResignActiveNotification` events to dispose and recreate `Renderer` and `RendererView`.

I tried couple of approaches - 1. read `RemoteVideoStream` info from SDK when app comes back to foreground, and 2. app using `RemoteVideoStream` info that was cached before app went to background. Both scenarios worked as expected for me. As per your last comment, you are using first approach.

Can you please share your logic for removing/re-adding video to the UI? If possible, please attach logs for one of the calls.

**Comment by ryanespiritu** [comment]
Sure, my logic is as follows:
1. When `UIApplicationWillResignActiveNotification` is received, dispose and release remote participant renderers
2. When `UIApplicationDidBecomeActiveNotification` is received, re-create renderers for each remote participant using their internally managed array of `ACSRemoteVideoStreams`

FWIW, this is not reproducible 100% of the time and I only see it when the remote participants are using a physical device.

Here are the logs: [acs_blobs.zip](https://github.com/Azure/Communication/files/5783322/acs_blobs.zip)

**Comment by ryanespiritu** [comment]
Hey @sankum-msft any luck with the logs I supplied? Happy to provide further info if necessary.

**Comment by ryanespiritu** [comment]
I'm seeing the following in the console when this issue occurs:
`[ACSRenderer] onBindingFailed`
`<SKPPullVideoRendererSource:0x600000e2a5a0>: binding failed, releasing source`

**Comment by sankum-msft** [comment]
@ryanespiritu , logs indicate app going to background-foreground-background-foreground in under a second. Can you please tell if that's what you are doing?

**Comment by ryanespiritu** [comment]
@RinaRish no I haven't experienced this recently, I'll close this issue. Will let you know if I come across it again in the future, thanks!
