### ISSUE TITLE
ACSCall.IsIncoming = false for an incoming call

### ISSUE THREAD

**Issue by nielscup** [Azure/Communication#139]
**Describe the bug**

ACSCall.IsIncoming is only true when ACSCall.State = Incoming. I would expect IsIncoming to be true for an incoming call regardless of the ACSCall.State, what is otherwise the purpose of the IsIncoming property?

**Comment by mariusu-msft** [comment]
Hi,

This is a bug, we’ll fix in a future release.

Thanks,
Marius

**Comment by kagbakpem** [comment]
@nielscup, this how been fixed in release [1.0.0-beta.8](https://search.maven.org/artifact/com.azure.android/azure-communication-calling/1.0.0-beta.8/aar). Please take a look at release notes [here](https://github.com/Azure/Communication/blob/master/releasenotes/2021-February-19.md) to integrate.
