### ISSUE TITLE
localhost is currently unable to handle this request.

### ISSUE THREAD

**Issue by NandaCodeBox** [Azure/Communication#14]
Build successful but facing below issue.

https://localhost:44316/
This page isn’t workinglocalhost is currently unable to handle this request.
HTTP ERROR 500

node -v        v14.8.0
VS 2019

**Comment by NMuravlyannikov** [comment]
Which quickstart do you use @NandaCodeBox ?

**Comment by NandaCodeBox** [comment]
@NMuravlyannikov from 
Readme.md

**Comment by tophpalmer** [comment]
Hey @NandaCodeBox , there are several samples in this repo, can you please point to the specific one you're having trouble with?

**Comment by NandaCodeBox** [comment]
@tophpalmer "Group Calling Hero Sample"

**Comment by ddematheu2** [comment]
Make sure to run the correct project on visual studio.

![image](https://user-images.githubusercontent.com/43075365/93935231-278ee380-fcd9-11ea-9e91-6bb793101314.png)

**Comment by NandaCodeBox** [comment]
@ddematheu2 thanks tht works...can u help me out why the microphone and video are not enabled .. though the browser allowing it ?

![image](https://user-images.githubusercontent.com/17465542/93937649-bfc2b200-fd45-11ea-95d7-4d80cb0b31d6.png)

**Comment by ddematheu2** [comment]
The camera and mic can be configured on the configuration page:
![image](https://user-images.githubusercontent.com/43075365/93946274-aa219e00-fced-11ea-8e0f-e01cb8025fa8.png)

Once on the call, you can click them to enable them. (They are not enabled by default)

**Comment by NandaCodeBox** [comment]
it worked after enabling the microphone for apps in windows 10. Thanks for the support.
