### ISSUE TITLE
SMS support in Japan

### ISSUE THREAD

**Issue by miyamam** [Azure/Communication#141]
Our customer in Japan would like to use SMS feature in Japan. Their system is IoT. When their system detects connected devices (NC lathe and other working machinery in factories) failure or something emergency case need to action, they would like to send SMS. __From the system architecture view, they would like to send SMS from LogicApps and Functions.__

But currently Communication Services is only supported U.S.

If it is possible to support SMS feature in Japan, our customer would be happy.

**Comment by Prakulka** [comment]
Hi @miyamam, thank you for sharing your use case with us. We do have plans for expansion next year and more info on this will be available on this [page](https://microsoft.sharepoint-df.com/:w:/t/SpoolSMS/EQc8CJFY2lxHkJOu4rQsPSIBdRD1lUZxvdTRGsxYFgDUcA?e=gj82Jh).
