### ISSUE TITLE
[iOS] Volume is very low

### ISSUE THREAD

**Issue by terrychen1122** [Azure/Communication#143]
We've been playing around with the SDK for a while and we notice that in a group call, the sound volume of the remote participants on my phone is very low. Even though I change my device's volume to highest, I need to move my ears next to the speaker in order to hear the other participants' speaking. Is this a known issue? It seems it has been for a while.

Device:
iPhone 11 Pro

**Comment by tompi** [comment]
I’m with you in calling this a bug. It’s not actually adjusting the volume, it’s switching which speaker is used from loudspeaker to ear speaker. Not logical for a video call if you ask me... my code waits for the call to be established and then switches back to loudspeaker...

**Comment by mariusu-msft** [comment]
@terrychen1122 is your issue the same as @tompi is highlighting? By default the library only uses the ear speaker, you need to route audio to loudspeaker if you want to use loudspeaker.

You can do that by using `overrideOutputAudioPort`

https://developer.apple.com/documentation/avfoundation/avaudiosession/1616443-overrideoutputaudioport?language=objc

**Comment by terrychen1122** [comment]
@mariusu-msft let me verify and report back here.

**Comment by mariusu-msft** [comment]
@tompi I agree that for group calls this behavior is not ideal, but the earpiece is the smallest common denominator and hence we default to it for all audio.

For the time being we expect applications to route audio correctly, to speaker or bluetooth, and in the future we will revisit the device manager once more and see if we can make the experience better, abstracting the OS primitives

**Comment by tompi** [comment]
@mariusu-msft its the same for a one to one videocall isn’t it? Not a big deal to compensate for once you realize what’s happening, but I suspect you will get a lot of these issues

**Comment by mariusu-msft** [comment]
Correct. For 1:1 audio or video call we always start with earpiece and leave it up to customers to decide if bluetooth or loudspeaker must be used

**Comment by terrychen1122** [comment]
@mariusu-msft Yes, this is the same issue (Thank you @tompi). It works when I did this override before joining a call but it doesn't work after I've joined the call. But we will probably go with setting the `playAndRecord` category with `defaultToSpeaker` and `allowBluetooth` options since I don't think we would use earspeaker in our use case.

**Comment by terrychen1122** [comment]
@mariusu-msft Another question for you is we found when the phone was connected to AirPods, the `speakerList` from acs device manager only shows the airpods device but not the built-in speaker. Is it expected? And are the speakerList and microphoneList in device manager useful at all?

**Comment by mariusu-msft** [comment]
@terrychen1122 Yes, at this time it's expected, since that becomes the OS default.

We will actually be removing Device Manager support for Audio devices to reduce confusion here. For both iOS and Android, we expect audio routing and device management to happen via OS primitives.
