### ISSUE TITLE
Web: deviceManager.getSpeakerList() return empty list.

### ISSUE THREAD

**Issue by afshinalizadeh** [Azure/Communication#144]
The getSpeakerList return empty list. But getMicrophoneList and getCameraList return correct devices.

Device: Xiaomi Redmi 8
OS: Android 10
Browser: Chrome
Version: 87.0.4280.101

**Comment by afshinalizadeh** [comment]
I saw setOutputDevice use setSinkId for set Speaker. But in "Android Chrome"  setSinkId is undefined.

**Comment by afshinalizadeh** [comment]
I found this bug in javascript sdk.
@kagbakpem

**Comment by kagbakpem** [comment]
Thanks @afshinalizadeh, re-assigning appropriately.

**Comment by mariusu-msft** [comment]
@afshinalizadeh thanks for you report.

Can you please follow this guideline and provide us with full verbose logs? We need to see some details about your devices.

https://docs.microsoft.com/en-us/azure/communication-services/concepts/troubleshooting-info?tabs=csharp%2Cjavascript%2Cdotnet#enable-and-access-call-logs

**Comment by chriswhilar** [comment]
@mariusu-msft this is also an issue on safari iOS

**Comment by cwhil2492** [comment]
Speaker enumeration is not supported in andoird chrome nor ios safari

**Comment by mariusu-msft** [comment]
Closing. Per @cwhil2492 this is expected on Android Chrome
