### ISSUE TITLE
Web: Camera problem in case of internet connection loss

### ISSUE THREAD

**Issue by burhanugur** [Azure/Communication#145]
Hello,

While the camera is on, the internet connection is disconnected and when the camera is turned on, the camera image of the other party seems to be closed, although the camera is on on both sides. When I turn the camera off and on again, it writes the following warning to the console

"azure: ACS: warning 12/23/2020, 9: 52: 23: 446 [CallClient] [JS.TsCalling.MediaAgentUnsafe] ffffffff: MA / webrtc2-14 / SSM Sender with media type Video does not exist, do not update media stream "

Since there is no problem with short-term internet disconnections, you can try it with an interruption of over 30 seconds.

**Comment by RinaRish** [comment]
Hi @burhanugur! Very sorry for the late reply. Is this issue still reproducible on the latest version of SDK?

**Comment by akania** [comment]
Closing as inactive @burhanugur if you're able to repro with latest SDK version ( 1.2.0 + ) please reopen and provide a call id and full log
