### ISSUE TITLE
callState changes to 'Hold' for both participants on a two party call

### ISSUE THREAD

**Issue by rdweaver** [Azure/Communication#146]
**Describe the bug**
On a two party call (acs User1 calls acs User2), when either user puts the call on hold, the callState for both users changes to 'Hold'. Also both users are receiving a participantStateChanged event for the callState of the other user changing.

**To Reproduce**
1. acs user1 calls acs user2
2. user1 places the call on hold. then user1 and user2 callState change to 'Hold'
3. the same is true if user2 places the call on hold. both users callState change to 'Hold'

**Expected behavior**
I would expect that when user1 places the call on hold, user1 callState would change to 'Hold' and user2 call state would remain 'Connected'. I would also expect that user2 would get a participantStateChanged event for user1 and that user1 would not get any participantStateChanged event for user2 because user2 callstate didn't change.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: [chrome or edge]
 - Version [1.0.0-beta.3]

**Additional context**
When there are more than two participants, it works as expected. So when user1, user2, and user3 are in a call, and user one places the call on hold. Only user1 callState changes to 'Hold'. The other two users callState stays 'Connected'.

**Comment by mariusu-msft** [comment]
@rdweaver thanks for the report.

This is currently by design.

Do you have a scenario where it would be useful for user2 to show Connected?

**Comment by rdweaver** [comment]
I think it should work consistently whether there are two users or three users or more on a call.

**Comment by rdweaver** [comment]
Version 1.0.0-beta.8 has this change in: CallState Enum: Hold state was splitted into LocalHold and RemoteHold.
This resolves this issue, so I am closing it.
