### ISSUE TITLE
[iOS] Unable to get latest release

### ISSUE THREAD

**Issue by devgokhan** [Azure/Communication#147]
Hi. Unable to get latest version beta 7 according the link: https://github.com/Azure/Communication/releases

I was tried with first method: 
```
pod 'AzureCommunicationCalling', :podspec => 'https://raw.githubusercontent.com/Azure/azure-sdk-for-ios/master/AzureCommunicationCalling.podspec'
pod 'AzureCommunication', :git => 'https://github.com/Azure/azure-sdk-for-ios.git', :branch => "master"
pod 'AzureCore', :git => 'https://github.com/Azure/azure-sdk-for-ios.git', :branch => "master"
```

then gave this error: 
```
[!] Failed to fetch podspec for `AzureCommunicationCalling` at `https://raw.githubusercontent.com/Azure/azure-sdk-for-ios/master/AzureCommunicationCalling.podspec`.
 Error: 404 Not Found
```

Then I tried with second way which recommended in tutorials:
```
pod 'AzureCommunicationCalling', '~> 1.0.0-beta.7'
pod 'AzureCommunication', '~> 1.0.0-beta.7'
pod 'AzureCore', '~> 1.0.0-beta.7'
```

it gives error: 
```
[!] Unable to find a specification for `AzureCommunicationCalling (~> 1.0.0-beta.7)`

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

We are unable to download it with this way too. There is nothing about beta.7. Cocoapods page (https://cocoapods.org/) show beta.6 currently.

<img width="1212" alt="Screen Shot 2020-12-30 at 15 20 04" src="https://user-images.githubusercontent.com/8233432/103350906-8fac4d00-4ab2-11eb-9385-9e8560639b27.png">

Anyway please update the documents after release. Documents still shows beta.5. In some way I think downloading way is changed but I couldn't understand how we install it with looking the docs and release notes.

**Comment by tompi** [comment]
+1 for cocoapods release. I made some scripts for pulling from cocoapod when building my xamarin bindings, so Im still waiting for the cocoapod release for updating it...

**Comment by mariusu-msft** [comment]
Today or tomorrow the Azure SDK team will be publishing to CocoaPods.
