### ISSUE TITLE
Azure Communication Service calling/chat web application to electron app

### ISSUE THREAD

**Issue by syamkp1986** [Azure/Communication#148]
I have created an angular application for group calling purpose and it is working fine. I would like to convert this application to electron app which supported in multiple OS(Linux, windows and mac). As we know, the device controls (deviceManager) handled in azure communication service calling sdk itself , so we cannot handle it with normal electron js properties/functions. I know, we cannot create the desktop application for calling. Do we have any solution for handle this device control access in electron js?

**Comment by syamkp1986** [comment]
I would like to create zoom or teams kind of application using ACS. In web, we can create an application like that and I have already done that. Using electron, we can convert our web application to desktop. But our deviceManager in sdk will not support in electron. It would be great, if you can modify the product which support in electronjs.

**Comment by RinaRish** [comment]
Hi @syamkp1986! Thanks for your feedback.

**Comment by cwhil2492** [comment]
Hi @syamkp1986, we currently do not officially support electron.

Can you please describe what is your electron setup/environment and how your trying to use the web sdk in your electron app?
Can you maybe upload your code to a repo and we can clone it and try it out?
