### ISSUE TITLE
[Web] CallAgent problem with multiple calls

### ISSUE THREAD

**Issue by btmpn** [Azure/Communication#150]
**Describe the bug**
I wanted to disable the possibility of having multiple active calls in my application, so I decided to try to automatically reject new incoming calls while being in an active / connected ongoing call.

The callAgent.calls array should show all calls in the users session, but there seems to be a problem:
At the moment when there should be 2 calls in callAgent.calls because there is an active call (state=connected), and another incoming call (state=incoming) the callAgent.calls array says that there is only 1 call item. I think it should have 2 call items at this moment.
When the incoming call gets rejected, then callAgent.calls suddenly decreases to 0 items.

That state causes another problem: When the furthermore active call ends due to the remote user, the callsUpdated-event is not triggered anymore.

**To Reproduce**
1. Create three azure communication user identities (User1, User2, User3)
2. Start a call (User1 -> User2)
3. User2 accepts the incoming call to have an active connected call with User1
4. Start a Call (User3 -> User2)
5. Client of User2 rejects the incoming call

After this User2's callAgent instance has 0 calls although it should still have 1 active call with User1 (which is still ongoing and working!).
When now User1 hangs up the call with User2 the callsUpdated-event is not getting triggered anymore in User2's client.

**System information**
 - User1 with Chrome-Browser
 - User2 with another Chrome-Browser (private mode)
 - User3 with Edge
 - Version ACS Calling JS SDK [1.0.0-beta.3]

Can't find any problems or errors in the log output.

Can someone reproduce this problem?

P.S.:
If there would be another method to find out if the user i'm trying to call is already in another call it would be even better.

Thanks in advance!
Patrick

**Comment by akania** [comment]
@btmpn Thank you for reporting this issue, we're able to reproduce. We'll fix it in upcoming release.
Regarding your question - our SDK doesn't provide an information if a callee ( user you're trying to call ) is currently in another call.
We'll evaluate this requirement.

**Comment by btmpn** [comment]
@akania thank you. Is there any plan, when the next release is coming?

**Comment by akania** [comment]
@btmpn 
`there's no possibility to recognize an incoming call, when the client / callAgent was not connected while the call was initiated by the caller?`
correct - there's no possibility for CallAgent to know about the calls that were placed to given identity if it wasn't active (online) at the time call was placed

`callAgent only know about calls which occured while he was connected`

Above captures how callAgent handles incoming call and describes requirement around CallAgent lifecycle.

What you're looking for probably is a `missed call` functionality - so an ability to know if there were calls issued for given identity while it was 'offline'

We'll improve documentation to describe this concept better

**Comment by akania** [comment]
@btmpn we're targeting for the next release in Feb

**Comment by btmpn** [comment]
Hi @akania, thank you for your reply.
I see.

> What you're looking for probably is a missed call functionality - so an ability to know if there were calls issued for given identity while it was 'offline'

No, that was not my intent, but this would also be awesome.
My intent for the question was the following szenario:

User1 calls / rings User2 while User2 has his browser closed.
While still User1 is calling (ringing) User2, User2 starts the application and my thought was to show that there is an incoming call, which can be answered by User2. But with current version User2 is not able to answer the incoming call since it's callAgent does not know anything about the incoming call.

But it may not be that important. The probability, that a User starts the application within a short time after the call was initiated, seems to be very low.

**Comment by mariusu-msft** [comment]
@btmpn indeed User2 has no way to find out if it missed the notification. There are timeouts involved too, so eventually ringing would stop, so even if we had such capability, if User2 didn't come online within a very narrow time margin, User2 wouldn't be able to "ring"

Eventually if we support WebPush or a generic push channel to be used on Web, you may enable the scenario by notifying User2 to process the incomingCallNotification right away, similar to how it works on iOS or Android. Right now we don't have any concrete plans for this.

**Comment by btmpn** [comment]
Thank you! Good to know that.

**Comment by RinaRish** [comment]
@btmpn do you have any other questions? or we can close this issue?

**Comment by btmpn** [comment]
Hi, thank you - I think we can close this for now.
