### ISSUE TITLE
[iOS] ACSRendererView for local video flashes blank after call reaches connected state

### ISSUE THREAD

**Issue by ryanespiritu** [Azure/Communication#151]
**Describe the bug**
The `ACSRendererView` for the local video stream will flash "blank" for a second and then refresh when the call moves from a state of `connecting` to `connected`.

**To Reproduce**

_Note: I've only observed this while using a physical device_
1. Create an `ACSRendererView` from the local video stream
2. Add the view to the view hierarchy and window
3. Join a call
4. Observe that the video rendering will flash "blank" for a second and then refresh after the call reaches the `connected` state.

**Expected behavior**
The rendering of the local video stream should not be affected when the the call state changes to `connected`.

**Smartphone (please complete the following information):**
 iPhone 11 Pro, iOS 13.2.3

**Additional context**
I've only observed this while using a physical device.

**Logs**
[acs_blog_files.zip](https://github.com/Azure/Communication/files/5778613/acs_blog_files.zip)

**Comment by ryanespiritu** [comment]
Attaching video:
https://user-images.githubusercontent.com/71148942/103832341-ec6bb280-5032-11eb-8309-fee95f68e0e7.mov

**Comment by sankum-msft** [comment]
I have a local repro and opened an internal work item (AB#2345324) to get to this root cause and fixed.

**Comment by terrychen1122** [comment]
@sankum-msft any updates on this?

**Comment by sankum-msft** [comment]
We are trying out a potential fix for this but don't have anything concrete to provide as of now.

**Comment by sankum-msft** [comment]
@ryanespiritu This should be fixed now. Can you please run your test and confirm?

**Comment by ryanespiritu** [comment]
Thanks @sankum-msft, verified the issue is fixed for me now. Closing this ticket
