### ISSUE TITLE
[Web] CallAgent.dispose() does not work

### ISSUE THREAD

**Issue by btmpn** [Azure/Communication#153]
**Describe the bug**
To provide a change user function in our application i tried, as described in the documentation, to dispose the callAgent using `callAgent.dispose();`.

Afterwards when trying to create a new callAgent it fails with the following message:
**Uncaught (in promise) Error: A Call Agent instance has already been created.Please dispose of it before creating a new Call Client instance.**

**To Reproduce**
1. create a callAgent with a user identity token
2. use it for a while
3. call callAgent.dispose();
4. immediately try to create a new callAgent instance.

**Expected behavior**
I would expect that the callAgent object is disposed to be able to create a new callAgent instance afterwards.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 1.0.0-beta3

**Additional context**
i tried it already different ways, both caused the same exception.:
method1:
```javascript
callAgent.dispose();
const callClient = new azureCommunicationService.CallClient();
const tokenCredential = new azureCommunicationService.AzureCommunicationUserCredential(acsUserToken);
callAgent = await callClient.createCallAgent(tokenCredential, { displayName: userDisplayName }); // this line causes the crash
```
method2:
```javascript
callAgent.dispose().then(initializeCallAgent(acsUserToken, userDisplayName));

function initializeCallAgent(acsUserToken, userDisplayName) {
  const callClient = new azureCommunicationService.CallClient();
  const tokenCredential = new azureCommunicationService.AzureCommunicationUserCredential(acsUserToken);
  callAgent = await callClient.createCallAgent(tokenCredential, { displayName: userDisplayName }); // this line causes the crash
}
```

Is there anything I'm doing wrong?

Thanks in advance
Patrick

**Comment by mariusu-msft** [comment]
@btmpn thanks for your report!

We are actively making some changes around this space, so this issue should get fixed then.

We'll release the re-worked flow in week of 18th or 25th.

**Comment by akania** [comment]
Hi @btmpn 
this bug was fixed, we'll close this issue - please update to latest version of library ( 1.1.0-beta.1 as of 6/6/2021 )
