### ISSUE TITLE
What is the "proprietary signalling package" mentioned in the chat documentation?

### ISSUE THREAD

**Issue by zane-woodard-drc** [Azure/Communication#154]
**Is your feature request related to a problem? Please describe.**
Certain enterprise customers have very restrictive network policies for workstations and don't allow all protocols. There's no real information on what this "proprietary signaling package" is other than that it's real-time, which makes it difficult to confirm if this is a viable solution for those enterprise customers.

I'm assuming it's not SignalR since the package is called proprietary, so what is it or what is it based on? Is it built on websockets? Is there fallback if websockets are blocked a la SignalR?

**Describe the solution you'd like**
More information on what the proprietary signaling package is or at least what underlying protocols are used.

**Comment by mariusu-msft** [comment]
Hi @zane-woodard-drc,

Thanks for your report.

In regards to which solution is your question? Chat or Calling?

Thanks,
Marius

**Comment by zane-woodard-drc** [comment]
Sorry, put it in the title but forgot to mention it in the body: this is in regards to chat.

**Comment by juancamilor** [comment]
Hi @zane-woodard-drc 
We will be adding some details on our docs for GA. In the meantime, I will try to address your questions :
Is it built on websockets? **Correct.** It uses websockets
Is there fallback if websockets are blocked ? If websockets are not supported, it will fallback to long polling.

Let me know if you have any other questions. 
Thanks
Camilo

**Comment by zane-woodard-drc** [comment]
That answers my questions, thank you.
