### ISSUE TITLE
Can't compile with beta 7 from Cocoapods. Can't use SPM either. Can't roll back to beta 6.

### ISSUE THREAD

**Issue by smartcat32** [Azure/Communication#156]
**Describe the bug**
Today when I updated to beta 7 (via Cocoapods) my app no longer compiles due to some missing declarations in AzureCommunicationCalling.  AzureCommunicationCalling.h references PhoneNumber and CommunicationUserCredential, yet neither of these classes/structs/types are in the library per a search in Xcode.

The first compile error is in line 405 of AzureCommunicationCalling.h, saying "Unknown type name 'PhoneNumber'.

Also, I tried to roll back to beta 6 but Cocoapods pulls in beta 7 regardless, even when starting fresh (deleting Pods directory, Podfile.lock, and DerivedData, changing podfile to point to beta 6, then doing "pod install").  Is beta 6 now blocked from working with Cocoapods?

I tried clearing out Azure from my Cocoapods and moving over to SPM but your SPM support still has the problem of not pulling down AzureCommunicationCalling (just the other two libraries).  I'm using Xcode 12.1.

So I'm rather stuck with no way to compile my iOS app at moment.  I wish I had saved a local copy of beta 6 Pods directory.

**To Reproduce**
Use a podfile such as the below, replacing "MyAppTarget".

```
platform :ios, '13.0'

target 'MyAppTarget' do
   use_frameworks!

   pod 'AzureCommunicationCalling', '~> 1.0.0-beta.7'
   pod 'AzureCommunication', '~> 1.0.0-beta.7'
   pod 'AzureCore', '~> 1.0.0-beta.7'
end
```

In your app, import and make use of AzureCommunicationCalling.

Or try SPM, using this URL for repository:  https://github.com/Azure/azure-sdk-for-ios.git
And choose Exact version with:  "1.0.0-beta.7".

**Expected behavior**
1) Be able to compile/link AzureCommunicationCalling with beta 7.
2) Be able to roll back to beta 6 using Cocoapods.
3) Use SPM with AzureCommunicationCalling.

**Desktop (please complete the following information):**
 - Xcode 12.1, MacOS 10.15.7.

**Comment by devgokhan** [comment]
Hi same for me. Unable to build the project with latest beta 7

<img width="236" alt="Screen Shot 2021-01-14 at 13 54 02" src="https://user-images.githubusercontent.com/8233432/104581840-2f9bd600-5670-11eb-9162-6c2786f6dda8.png">


Extra note to download Azure SDK I am adding Azure's source
```
source 'https://github.com/Azure/azure-sdk-for-ios.git'
```

**Comment by NicuLupu** [comment]
@devgokhan @smartcat32 to roll back you need to modify your pod file like this 
"pod 'AzureCommunicationCalling', '1.0.0-beta.6'
    pod 'AzureCommunication', '1.0.0-beta.6'
    pod 'AzureCore', '1.0.0-beta.6'"

This is from the release page of beta 7 "Latest XCode 12.3 does not support frameworks where lipo was used to combine simulator and arm builds, we will address this issue in the next release."

**Comment by raosanat** [comment]
We are aware of the issue and we will update the zip file attached in the release tomorrow. Sorry for the inconvenience.

**Comment by smartcat32** [comment]
@NicuLupu Thanks! That change to my Podfile got me back to beta 6 just fine.

**Comment by raosanat** [comment]
We have now fixed the issue. Please run `pod cache clean` and `pod install` so that CocoaPods downloads the latest zip file. Please let us know if you still face any issues. Thanks.

**Comment by devgokhan** [comment]
Hi, did you remove/change CommunicationUserCredential or is it unavailable in pod?

```
Analyzing dependencies
Downloading dependencies
Installing AzureCommunication 1.0.0-beta.7 (was 1.0.0-beta.6)
Installing AzureCommunicationCalling 1.0.0-beta.7 (was 1.0.0-beta.6)
Installing AzureCore 1.0.0-beta.7 (was 1.0.0-beta.6)
Generating Pods project
Integrating client project
Pod installation complete! There are ... dependencies from the Podfile and ... total pods installed.
```

![Screen Shot 2021-01-19 at 10 32 19](https://user-images.githubusercontent.com/8233432/105002043-bcb0a780-5a41-11eb-99c1-723f16750f11.png)

**Comment by raosanat** [comment]
Can you confirm if you ran `pod cache clean --all` , if not CocoaPods will still re-fetching zip from cache instead of from GitHub?

**Comment by devgokhan** [comment]
Hi. It works thank you.  
Note to community: CommunicationUserCredential is changed with CommunicationTokenCredential

**Comment by raosanat** [comment]
Yes, we will update the documentation this week. Thanks.

**Comment by smartcat32** [comment]
Yes, is working now for me too. I can bring down beta 7 now via Cocoapods.  

Note to community:  Don't add the source line to your Podfile, as for some reason it causes beta 7 to still not be found.  (The source line isn't a problem on beta 6).
