### ISSUE TITLE
[Web] Unexpected behavior around VideoDeviceInfo and AudioDeviceInfo being instantiated classes/prototypes instead of POJOs

### ISSUE THREAD

**Issue by lazerwalker** [Azure/Communication#157]
**Is your feature request related to a problem? Please describe.**
I'm building a React/Flux architecture app where, as part of my app's flow, the list of available audio and video devices (read: the results of `deviceManager.getCameraList()` and `getMicrophoneList()`) are stored in an app-wide state object that frequently gets deep-cloned / copied.

As an end-user, the API documentation and TS types for VideoDeviceInfo and AudioDeviceInfo make it sound like these are data objects with no logic. My assumption as an experienced JS user is that, if I see an API definition for an object interface that's just properties with no methods or constructor, I can take a `VideoDeviceInfo` object and do whatever I want with it (`JSON.stringify`/`JSON.parse`, Lodash's `_.clone`, `Object.assign({}, obj)`, whatever) and I'll still be able to access all of the public fields listed in the documentation, such as `name`, `id`, etc, and also be able to pass that resulting object into a `LocalVideoStream` constructor or whatever other ACS constructs I want.

This isn't the case in practice, since `getCameraList()` return arrays of instantiated `t.VideoDeviceInfoImpl` objects, where the publicly exposed fields are computed getters on top of private properties. This means that whenever I deep clone the object myself, unless I manually reinstantiate a `t.VideoDeviceInfoImpl` object (which sounds like a Very Bad Idea), I cannot access `someVideoDeviceInfoObj.name`, and I also can't pass this into e.g. a `LocalVideoStream` constructor. (I _can_ access `someVideoDeviceInfoObj._name`, but naturally this private field access is undesirable for a number of reasons)

To put a clear failing test on this, I would expect the following code to return true:

```js
// assume everything's been properly set up that this returns a valid VideoDeviceInfo object
const camera = deviceManager.getCameraList()[0] 
const clonedCamera = Object.assign({}, camera)
return clonedCamera.name === camera.name
```

The current behavior would return false, as `clonedCamera.name` will be undefined.

I don't think this is an odd request -- this data pattern for deep cloning an app-wide (or semi-app-wide) state object is very common in modern JS web apps, and it seems eminently reasonable that someone would want to store device availability data in a data structure like that to e.g. render a camera selection interface. 

**Describe the solution you'd like**
Ideally, the example I gave above would return true, meaning that `VideoDeviceInfo` and `AudioDeviceInfo` objects are pure data objects instead of instantiated classes with computed getters.

Alternatively, if there are valid reasons to not make this change (I'm aware that I lack context here!), this should ideally be documented. As I mentioned, it's a reasonable assumption in JS that an object interface API definition that contains only properties with no methods or constructors is describing a plain old JS object that API consumers can do whatever they want with. Calling out that this is not the case would save some debugging headaches.

**Describe alternatives you've considered**
My personal use case for wanting to store this data in a way that causes it to be naively deep-cloned is presenting a config UI that lets users select their preferred AV inputs, and storing those preferences for later use.

It would be _fantastic_ if ACS provided a UI like this, especially since this functionality is a core building block that most complex communication apps integrating ACS will likely want to provide anyway. I recognize this is a wholly separate feature request, but mentioning it as something that would at least solve my specific use case.

I expect I will currently be able to work around this by storing device names and IDs in my data store, and refetching the camera/microphone list at the moment I want to construct a stream. This won't be too clunky, but feels like an odd workaround.

**Additional context**

Let me know if it's helpful to see my entire project/ACS integration. This is an open-source project, but the ACS work lives on a branch that hasn't yet been pushed to public GitHub.

I'm also a corp employee, feel free to ping me internally on Teams or email (I'm `emwalker`).

**Comment by akania** [comment]
@lazerwalker Thank you for your feedback, it's a fair point that when library returns structures that are pure data objects these should be effectively just POJOs, one of the reasons we've decided to go with classes & instances is that as as our feature set grows we may add in the future new functionality into these objects, at this point using plain objects wouldn't work because of the reasons you've mentioned above.
We'll improve our documentation,

**Comment by akania** [comment]
Documentation  - tracking under #2413808

**Comment by akania** [comment]
closing - [documentation](https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/voice-video-calling/calling-client-samples) was updated, 
Going forward ACS will provide an data layer that will make it easier to bind to
