### ISSUE TITLE
Which one is android latest version ?

### ISSUE THREAD

**Issue by ozanurkn** [Azure/Communication#158]
Hi,

İ am using Azure/Communication in our android project. I follow github channel for every new version but i don't understand which one latest version for android. I was looking tags, and every version is write for IOS. 1.0.7 is latest version now. Can we use this version  for android?

Thanks.
Ozan

**Comment by kagbakpem** [comment]
Android latest version is 1.0.0-beta.5 @ozanurkn. See [here](https://github.com/Azure/Communication/blob/master/releasenotes/2020-December-17.md).
