### ISSUE TITLE
XAML: UWP and/or WPF SDK Clients

### ISSUE THREAD

**Issue by keithnicholson** [Azure/Communication#16]
**Is your feature request related to a problem? Please describe.**
We are needing to implement with an existing UWP solution which is used in a large number of field locations.  We were just assigned this a research user story with the goal of implementing probably in the next sprint.  

**Describe the solution you'd like**
Integrate with a Teams meeting created by district, division, or corporate management that can be used within an existing UWP solution.

**Describe alternatives you've considered**
We have been looking at integrating with the WebEx Browser SDK and we have tried to see how to do it with the MS Graph Communication APIs.  We could also figure out how to use the ACS Web SDK inside the WebView control.

**Comment by RinaRish** [comment]
Hi @keithnicholson! Could you please send us an email to acsfeedback@microsoft.com and we will get in touch with you regarding your particular situation?

**Comment by tophpalmer** [comment]
AB#2211519

**Comment by tophpalmer** [comment]
Tracked on the roadmap 
https://github.com/Azure/Communication/projects/1
