### ISSUE TITLE
User Token generation RestError The HTTP resource that matches the request URI https://52.168.169.1/identities

### ISSUE THREAD

**Issue by xtianus79** [Azure/Communication#160]
**Describe the bug**

When running the generate user token using the const { CommunicationIdentityClient } = require('@azure/communication-administration'); package the following error occurs and all of my applications are broken because I cannot generate a user token. 

The call below is particularly failing at this point:

let userResponse = await identityClient.createUser(); 
Engountered an error  RestError: The HTTP resource that matches the request URI 'https://52.168.169.1/identities' does not support the API version '2020-07-20-preview2'. 

**Expected behavior**
a token to be generated. 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Logs**
<br/>Please attach the logs or share the callId. Instructions could be found [here](https://docs.microsoft.com/en-us/azure/communication-services/concepts/troubleshooting-info?tabs=csharp%2Cjavascript%2Cdotnet)

**Comment by smartcat32** [comment]
I'm having the same problem today.  I tried a rebuild of the access-tokens-quickstart directory by following the instructions here:  https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/access-tokens?pivots=programming-language-javascript but it didn't help or change the error at all.

**Comment by smartcat32** [comment]
Here's a workaround that's solved it for me:  Just build the C# app instead of the JS app.  Follow the instructions here:  https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/access-tokens?pivots=programming-language-csharp     I could build & run this right from within my Mac Terminal command line, just like the JS.

**Comment by isoldea** [comment]
Also experiencing this issue today, but can't use the C# workaround as I need to use JavaScript for my application.

**Comment by ddematheu2** [comment]
We are currently investigating the issue, will provide an update soon.

**Comment by RezaJooyandeh** [comment]
The issue is resolved now  and the JS library should be back to working 😊. Thank you for your patience while we were investigating. 🙏🏻

**Comment by smartcat32** [comment]
It's not fixed for me.  Just a different error code now:

```
Azure Communication Services - Access Tokens Quickstart
Encountered and error
RestError: Denied by the resource provider. 
 {
  "name": "RestError",
  "code": "Denied",
  "statusCode": 401,
```
