### ISSUE TITLE
Push message callId is different than the one from callAgent callback

### ISSUE THREAD

**Issue by paulmarcsqr** [Azure/Communication#164]
I am integrating the ACS SDK with the CallKit and I encounter the following issue: Following the flow in order to respond to calls while application is in background or closed, i receive a push notification from ACS notification hub with a "callId" that i'm linking with the CallKit implementation in order to respond to acs call state changes. The problem is that after initialising the CallAgent from ACS SDK, and i call the handlePushNotification method, the call that i receive on callback have a different callID than the one that came on the push message. From various tests that i did, the IDs were the same in like 2-3 tests out of 15, so my question is why do we receive different callID in notification than in the Call object we retrieve from CallAgent.

**Comment by raosanat** [comment]
Hi, thanks we will look into the issue. Btw just for your information we are working on CallKit integration within the SDK itself. In on of the next 2 upcoming release we will complete the work.

**Comment by paulmarcsqr** [comment]
Fixed with beta 8

**Comment by raosanat** [comment]
Thanks for verifying.
