### ISSUE TITLE
Question: About the 350 participants

### ISSUE THREAD

**Issue by cngeru** [Azure/Communication#168]
I saw that ACS can handle 350 concurrent users. Will all the 350 be able to talk in the call simultaneously. Or is it still limited to like 6 in call in webrtc ?
if limited to 6. How can one push to like 50 in call

**Comment by nmurav** [comment]
Hi @cngeru  you can have 350 users in a call simultaneously. Note limitations on Calling client library streaming support https://docs.microsoft.com/en-us/azure/communication-services/concepts/voice-video-calling/calling-sdk-features#calling-client-library-streaming-support

**Comment by cngeru** [comment]
@nmurav What does no of incoming streams in this link mean [https://docs.microsoft.com/en-us/azure/communication-services/concepts/voice-video-calling/calling-sdk-features#calling-client-library-streaming-support](url)
