### ISSUE TITLE
[Android] Calling: Not compatible with latest Common library (CommunicationUserCredential removed)

### ISSUE THREAD

**Issue by tompi** [Azure/Communication#169]
Latest version of https://search.maven.org/artifact/com.azure.android/azure-communication-common/1.0.0-beta.4/aar
seems to have removed CommunicationUserCredential which is a parameter to CreateCallAgent...

I hope you have a new release in the pipeline ;-)

**Comment by tompi** [comment]
Nevermind, beta 6 was just released, and solved my problem :)

**Comment by kagbakpem** [comment]
@tompi, please use [beta.7](https://search.maven.org/artifact/com.azure.android/azure-communication-calling/1.0.0-beta.7/aar) instead. There are slight issues with beta.6

**Comment by tompi** [comment]
@kagbakpem Thnx, updated now.
