### ISSUE TITLE
iOS SDK: stopVideo is not working

### ISSUE THREAD

**Issue by terrychen1122** [Azure/Communication#17]
When we called `stopVideo` on the call, it did nothing.

On our demo app, joined an existing call with video and audio enabled. Once connected, we called `stopVideo` on the existing call object. However, the remote participants were still able to see my local stream. Also, the `stopVideo` completion handler did tell me no error so I assume stopping sharing the local video has been performed successfully.

Expected:
Once `stopVideo` call is complete, the other participants should no longer see my local stream.

Code snippet:
```
ACSVideoDeviceInfo *camera = [[self.deviceManager getCameraList] firstObject];
if (!camera) {
  return;
}
[self.activeCall stopVideo:[[ACSLocalVideoStream alloc] init:camera] withCompletionHandler:^(NSError *error) {
  if (error) {
    NSLog(@"Failed to stop video");
  } else {
    NSLog(@"successfully stopped video");
  }
}];
```

 - Device: iPhone X
 - OS: iOS 13.1

**Comment by NMuravlyannikov** [comment]
@mariusu-msft  can you please help here?

**Comment by mariusu-msft** [comment]
Thanks for the report @terrychen1122.

As a parameter to `stopVideo` can you pass the `localVideoStream` instance that you used to start video with?

From your snippet it seems you are allocating a new localVideoStream, and while that stream might have the same camera as before, it's is not the same localVideoStream instance which is attached to the call for sending video to remote participants.

**Comment by terrychen1122** [comment]
@mariusu-msft I also tried to use the same `localVideoStream` when the device manager is setup. Will try using the same when joining the call and update the thread.

**Comment by terrychen1122** [comment]
@mariusu-msft now it works by passing the local video stream that was used to join the call. Thanks for the help. I'd recommend documenting this in the api so it becomes clearer.
