### ISSUE TITLE
Occur unhandled runtime error when callee could not find or callee rejected an incoming call

### ISSUE THREAD

**Issue by bbonkr** [Azure/Communication#174]
**Describe the bug**

Occur unhandled runtime error below condition.
* Callee could not find.
* Callee rejected an incoming call.

**To Reproduce**

When callee jejected an incoming call:
1. Make a call with azure communication service identifier like 8:aaa
2. Callee rejected an incoming call.
3. Caller got unhandled runtime error on caller' web browser console

When callee could not find:
1. Make a call with azure communication service identifier like 8:aaa
2. Callee does not find such as callee does not sign in our service.
3. Caller got unhandled runtime error on caller' web browser console

**Expected behavior**
Error does not occur.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Browser Microsoft Edge, Google Chrome
 - Version 88.0.705.56 (Official build) (64-bit), 88.0.4324.104(Official build) (64-bit)

```
PS> node -v
v14.15.1
```

```
PS> npm -v
6.14.11
```

dependent packages: 
* @azure/communication-calling: ^1.0.0-beta.4
* @azure/communication-common: ^1.0.0-beta.4
* react: ^16.13.0
* react-dom: ^16.13.0
* next: ^10.0.3

**Additional context**
It was not case with @azure/communication-calling 1.0.0-beta 3

When callee rejected an incoming call.

![caller-error](https://user-images.githubusercontent.com/3590545/106991535-c7956700-67b9-11eb-8533-79546a857694.png)
![caller-error-2](https://user-images.githubusercontent.com/3590545/106991545-ccf2b180-67b9-11eb-8e95-bbd64eb8873e.png)

When call could not find.

![caller-error-3](https://user-images.githubusercontent.com/3590545/106991595-ec89da00-67b9-11eb-8b7d-e147916d068c.png)
![caller-error-4](https://user-images.githubusercontent.com/3590545/106991602-ef84ca80-67b9-11eb-812c-cb4a1401a6d3.png)

**Logs**

Web browser console log 

```
Uncaught (in promise) 47
setTimeout (async)
handleIncomingNotification @ sdk.bundle.js:131
e.handleMessage @ sdk.bundle.js:77
e.safeExecuteHandle @ sdk.bundle.js:141
e.handleMessage @ sdk.bundle.js:141
e.tryMessageHandlers @ sdk.bundle.js:149
e.onTrouterRequest @ sdk.bundle.js:149
e.onDownstreamRequest @ sdk.bundle.js:141
e.dispatchDownstreamRequest @ sdk.bundle.js:149
e.onDownstreamRequest @ sdk.bundle.js:149
e.onSocketMessage @ sdk.bundle.js:149
(anonymous) @ sdk.bundle.js:149
n.emit @ sdk.bundle.js:141
n.onPacket @ sdk.bundle.js:141
i.onPacket @ sdk.bundle.js:141
n.onPacket @ sdk.bundle.js:141
n.onData @ sdk.bundle.js:141
websocket.onmessage @ sdk.bundle.js:141
```

```
sdk.bundle.js:4 
Uncaught (in promise) Error: Failed to start the call
    at CallImpl.<anonymous> (sdk.bundle.js:149)
    at Generator.throw (<anonymous>)
    at s (sdk.bundle.js:149)
CommunicationErrorImpl @ sdk.bundle.js:4
(anonymous) @ sdk.bundle.js:149
s @ sdk.bundle.js:149
Promise.then (async)
c @ sdk.bundle.js:149
(anonymous) @ sdk.bundle.js:149
__awaiter$6 @ sdk.bundle.js:149
startCallInternal @ sdk.bundle.js:149
createCall @ sdk.bundle.js:149
call @ sdk.bundle.js:149
i.value @ sdk.bundle.js:4
_callee13$ @ useAzureCommunicationService.ts:685
tryCatch @ runtime.js:63
invoke @ runtime.js:293
(anonymous) @ runtime.js:118
asyncGeneratorStep @ asyncToGenerator.js:3
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
makeCall @ useAzureCommunicationService.ts:680
(anonymous) @ GroupCall.tsx:53
commitHookEffectListMount @ react-dom.development.js:19731
commitPassiveHookEffects @ react-dom.development.js:19769
callCallback @ react-dom.development.js:188
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
flushPassiveEffectsImpl @ react-dom.development.js:22853
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushPassiveEffects @ react-dom.development.js:22820
(anonymous) @ react-dom.development.js:22699
workLoop @ scheduler.development.js:597
flushWork @ scheduler.development.js:552
performWorkUntilDeadline @ scheduler.development.js:164
```

**Comment by akania** [comment]
@bbonkr Thank you for reporting this issue, we'll provide fix in the next release

**Comment by ProbablePrime** [comment]
@akania This bug deals with beta.4 I see beta.9 is the latest(https://www.npmjs.com/package/@azure/communication-calling)

Is this bug fixed in Beta 9?

**Comment by akania** [comment]
Hi all, this bug was fixed, we'll close this issues - please update to latest version of library ( 1.1.0-beta.1 as of 6/6/2021 )
