### ISSUE TITLE
Phone lookup and validate number

### ISSUE THREAD

**Issue by danlaunchcontrol** [Azure/Communication#177]
I couldn't find any issue from this topic, on the docs here: https://docs.microsoft.com/en-us/answers/questions/182005/azure-communication-services-validate-existing-pho.html

But basically, we need a lookup to check phone number is mobile and what carrier it is

**Comment by ProbablePrime** [comment]
Thanks for your request, as Mary Anne said on Microsoft Q&A we don't currently have this feature. I will mark this as a feature request and alert the team behind this area of ACS.
