### ISSUE TITLE
[iOS] Video feed is not showing on remote if local device orientation is landscape

### ISSUE THREAD

**Issue by tompi** [Azure/Communication#178]
**Describe the bug**
When iPad Pro is used, the ipad camera feed is not shown(blank view) on the remote clients(tested iphone and android phones). There are the expected events for the remoteVideo, and "isAvailable=true", but when I create a renderer it is not showing anything...

The reason Im filing this as an Ipad bug is  I assume its related to this since video feed doesnt show up on either other ios(phone) or android(tried 2 different devices)...

**Screenshots**
![IMG_20210208_091250](https://user-images.githubusercontent.com/231717/107193034-ae293080-69ee-11eb-968a-d681d87250fa.jpg)

**Smartphone (please complete the following information):**
 - Device: iPad Pro 3rd gen, MTEL2KN/A
 - OS: iOS 14.4

**Additional context**
Using ACS beta 7 on both ios and android. 

**Logs**
From visual studio
[vs-log.txt](https://github.com/Azure/Communication/files/5942245/vs-log.txt)
Device log extracted with xCode
[xcappdata.zip](https://github.com/Azure/Communication/files/5942266/xcappdata.zip)

**Comment by tompi** [comment]
Okay, I feel a little bit stupid(just a little bit since this is obviously a bug...):

Once I rotated ipad to portrait, video feed from this showed just fine...

**Comment by tompi** [comment]
Probably duplicate of https://github.com/Azure/Communication/issues/128

In the future: please dont close tickets until you actually release a fix for them! Will save some time for others experiencing same issue

**Comment by sankum-msft** [comment]
Yes, this is a duplicate of #128. Closing as such.

**Comment by tompi** [comment]
@sankum-msft This is fixed for rotation(as was mentioned in #128) in beta-8, but is still a bug when initiating a call in landscape mode... AFTER rotating to portrait, I can rotate back again and video is then working, but if I initiate call in landscape, no remote video...

Do you want me to open a new bug, doesnt seem like I have permission to reopen?

**Comment by sankum-msft** [comment]
Reopening this as #128 tracks issue caused by device rotation. We should use this one to track video setup issue while initiating a call in landscape mode.

**Comment by sankum-msft** [comment]
Created AB#2378908 to get this fixed.

**Comment by sankum-msft** [comment]
We have a fix for this which will be included in the next release.

**Comment by tompi** [comment]
@sankum-msft Good to hear, hope it is not far away. Also: my workaround now has been to just tell people to rotate their ios devices if they dont get a picture, but just discovered that this doesnt work if the orientation lock is turned on...

**Comment by tompi** [comment]
Can confirm this works fine on beta-9.

P.S. @sankum-msft  Seems there is a regresseion with info.plist missing cfbundleversion in beta-9. I wont bother creating a new issue, just FYI (I just work around it by adding it myself...) As you know this prevents consumers of lib to publish to appstore...
