### ISSUE TITLE
Question ANH for both voip and standard notification

### ISSUE THREAD

**Issue by hyounoo** [Azure/Communication#179]
So I can only receive voip notification with ANH handle set to {budleIdentifier}.voip
This makes my normal notification throws error on ANH as below.
![image](https://user-images.githubusercontent.com/9585318/107239898-ab6d2080-6a6c-11eb-85e0-c3c70550ecbd.png)

Does this mean that I have to configure two ANH for each notification?

If so, does my app will end up with two MSNotificationHub instances?

like below?
MSNotificationHub.start(connectionString: connectionStringForVoIP, hubName: hubNameForVoIP)

and 

MSNotificationHub.start(connectionString: connectionStringForStandard, hubName: hubNameForStandard)

**Comment by razvansalajan** [comment]
Hello @hyounoo,

What is the scenario that you are trying to do ?
Are you trying to link an ANH hub to an ACS resource (like mentioned in [Notification Hub provisioning](https://docs.microsoft.com/en-us/azure/communication-services/concepts/notifications#notification-hub-provisioning)) ? 

ACS for APNS platform sends only VOIP (no [user notifications](https://developer.apple.com/documentation/usernotifications/)) push notifications at the moment through the linked ANH hub. When configuring the APNS credentials for the ANH hub that was linked to the ACS resource, the bundleId no longer needs the `.voip` suffix.

**Comment by hyounoo** [comment]
Yeah, I figured it out by accident.
Thanks for the info.

**Comment by mariusu-msft** [comment]
This issue seems resolved. Closing.
