### ISSUE TITLE
[Android] RendererView for local video freezes/flickers when call reaches connected state

### ISSUE THREAD

**Issue by kdhuynh** [Azure/Communication#180]
**Describe the bug**
The RendererView for a local video stream will freeze up and/or flicker for a moment when an associated call moves from a state of connecting to connected.

**To Reproduce**

1. Create a RendererView using a local video stream
2. Add the view to the view hierarchy and window so that the video stream is visible.
3. Join a call, with JoinCallOptions configured to use the same video stream
4. Observe that the RendererView will freeze/flicker for a second and then refresh after the call reaches the connected state.

**Expected behavior**
The rendering of the local video stream should not be effected when connecting to a call using that video stream.

**Screenshots/Video**
https://user-images.githubusercontent.com/1747789/107414706-3aa72200-6ac7-11eb-86ac-6102d3f0d86b.mp4

**Smartphone (please complete the following information):**
 - Device: Pixel 3 and Samsung Galaxy S20
 - OS: Android 11.0

**Comment by sankum-msft** [comment]
This is the same as #151 but for Android. So keeping it open while we figure out the right fix.

**Comment by sankum-msft** [comment]
@kdhuynh It should be fixed now. Can you please re-run your test and reopen this issue if it's still not working for you?

**Comment by kdhuynh** [comment]
This issue is resolved for me now, thank you!

**Comment by mariusu-msft** [comment]
Thanks for the confirmation @kdhuynh
