### ISSUE TITLE
[Android] Resizing RendererView does not correctly adjust video while using ScalingMode.Fit

### ISSUE THREAD

**Issue by kdhuynh** [Azure/Communication#181]
**Describe the bug**
A RendererView that is using ScalingMode.Fit to render the video will not adjust the video image correctly if the size and aspect ratio of the RendererView are changed while the video is currently rendering. 

**To Reproduce**

1. Join a call that has one other participant, who is streaming their vide.
2. Display a RendererView representing the remote video, using ScalingMode.Fit.
3. Change the size and aspect ratio size of the RendererView.
4. Observe that the video within the RendererView will resize, but the empty space around the video does not adjust based on the new aspect ratio of the RendererView

**Expected behavior**
Resizing a RendererView will update the empty space around the rendered video if using ScalingMode.Fit

**Screenshots/Video**
See how the video on the right has a gray margin on the left side, from when it was a different size and aspect ratio.

https://user-images.githubusercontent.com/1747789/107419810-0fbfcc80-6acd-11eb-84e3-76bb276047fa.mp4

**Smartphone (please complete the following information):**
 - Device: Pixel 3, Samsung Galaxy S20, Android Studio Emulator
 - OS: Android
 - Version 11.0

**Comment by sankum-msft** [comment]
Thanks for reporting this issue. I have opened AB#2374360 to get this fixed.

**Comment by mariusu-msft** [comment]
Hi. This should be now fixed with the latest release of the Calling SDK.
