### ISSUE TITLE
Question establishConnection on pushRegistry and beta.8 sdk

### ISSUE THREAD

**Issue by hyounoo** [Azure/Communication#182]
So I was able to get voip push notifications from ANH using {bundleID}.voip handle.
Both background and lock screen get notifications!.

But I have some questions regarding answering the call process.
1. When processing notification from background where app is terminated, app need to initialize callClient and callAgent.
This becomes problem when user answers call in CallKitUI because the connection hasn't made yet.
How should I manage this? 

2. New 1.0.0-beta.8 introduced ACSIncomingCallPushNotification where it was dictionaryPayload: [AnyHashable : Any]
How do I convert the payload from pushRegisrty to this new Object?

my pushRegitry for receiveIncomingPushWith code is as below
```
    func pushRegistry(_ registry: PKPushRegistry, didReceiveIncomingPushWith payload: PKPushPayload, for type: PKPushType, completion: @escaping () -> Void) {
        let dictionaryPayload = payload.dictionaryPayload
        print("dictionaryPayload: \(dictionaryPayload)")

        if type == .voIP {
            CallKitManager.shared().reportNewIncomingCall(dictionaryPayload: dictionaryPayload) { success in
                if success {

//                    below line has error with 1.0.0-beta.8 sdk
                    self.callAgent?.handlePushNotification(payload.dictionaryPayload, withCompletionHandler: { (error) in
                        if (error != nil) {
                            print("Handling of push notification to call failed: \(error.debugDescription)\n")
                        } else {
                            print("Handling of push notification to call was successful.\n")
                        }
                    })
//                   how to I pass above payload as InvomingCallPushNotification object?
//                    self.callAgent?.handlePush(notification: **IncomingCallPushNotification**!, completionHandler: { (Error?) in
//                    })

                } else {
                    print("Handling of report incoming call failed.\n")
                }
                completion()
            }

            if self.callAgent == nil {
                // MARK: generate communicationUserToken from stored data.
                if self.communicationTokenCredential != nil {
                    self.callClient?.createCallAgent(userCredential: communicationTokenCredential, options: CallAgentOptions()) { (callAgent, error) in
                   self.callAgent = callAgent
                   self.callAgent.delegate = self
                } else {
                    print("No token found,\n")
                }
            }
        }
    }
```

**Comment by paulmarcsqr** [comment]
let acsPNObject =  IncomingCallPushNotification.fromDictionary(payload)

**Comment by hyounoo** [comment]
> let acsPNObject = IncomingCallPushNotification.fromDictionary(payload)

Thanks

**Comment by jpickardsqr** [comment]
@raosanat can we please include these sorts of changes in the release notes? Are you able to update the existing beta.8 to include this?

**Comment by raosanat** [comment]
Hi, yes we missed this in release notes, we have added a helper API as you saw above which parses the push payload and then you can pass that object to the `handlePush`

```
        let callNotification = IncomingCallPushNotification.fromDictionary(pushPayload.dictionaryPayload)
        callAgent.handlePush(notification: callNotification) { (error) in
                assert(error == nil, "SDK couldn't handle push notification")
         }
```

Btw just for your information we are also working on CallKit integration in the SDK to keep the logic in the application to minimal and SDK will take care of interacting with CallKit on applications behalf. We should have the first version out within the next 2 releases.

**Comment by ProbablePrime** [comment]
This one looks to be solved.
