### ISSUE TITLE
onCallsUpdated not called with added calls for outgoing calls

### ISSUE THREAD

**Issue by jpickardsqr** [Azure/Communication#184]
ACSCallAgentDelegate.onCallsUpdated is not called with `args.addedCalls` when a new outgoing call is made.

This is hinted at in the documentation, although I think it could be clearer.
https://docs.microsoft.com/en-us/objectivec/communication-services/calling/acscallagentdelegate
> Occurs when a new call is created, in case of an incoming call or when an existing call is disconnected.

This is different to the Web SDK where the callAgent `callsUpdated` event *is* fired for outgoing calls.

I think it would be less confusing if every call (whether incoming or outgoing) triggered `ACSCallAgentDelegate.onCallsUpdated`. I think it would be good if every call is "added" before it is "removed" regardless of whether it an incoming call or an outgoing call.

**To Reproduce**
1. Make a call, e.g. `callAgent.call(participants: [callees], options: startCallOptions)`

**Expected behavior**
The callAgent's delegate is called with `onCallsUpdated` where `args.addedCalls` contains the call.

**Additional context**
Version 1.0.0-beta.8

**Comment by raosanat** [comment]
Hi, we had two issues here
1. `CallAgent` `calls` list wasnt getting updated for any outgoing calls. 
2. `OnCallsUpdated` event not raised on outgoing call.

1st part is fixed in beta.8, 2nd we will fix in the upcoming release. Thanks for reporting

**Comment by RinaRish** [comment]
@jpickardsqr it was fixed, please reopen if issue persists.
