### ISSUE TITLE
callerId requires casting to CommunicationUserIdentifier

### ISSUE THREAD

**Issue by jpickardsqr** [Azure/Communication#185]
Using the Swift SDK, in `CallDelegate.onCallStateChanged` the `Call` argument has a `callerId` property that is of type `CommunicationIdentifier`. In order to get the actual ACS ID associated with the call, `callerId` must be cast to CommunicationUserIdentifier, for example:

```
changedCall.callerId as? CommunicationUserIdentifier)?.identifier
```

It would be simpler if this was not necessary.

**To Reproduce**
1. Attempt to access `call.callerId.identifier` in `onCallStateChanged`.

**Expected behavior**
It works.

**Actual behavior**
Compiler error.

**Version**
1.0.0-beta.8

**Comment by raosanat** [comment]
`CommunicationIdentifier` is the protocol which is implemented by all identifier types `PhoneNumberIdentifier` , `CommunicationUserIdentifier`, `MicrosoftTeamsUserIdentifier` and `UnknownIdentifier`. So first you will have to cast to one of the identifier types. There is a similar issue [here]https://github.com/Azure/azure-sdk-for-ios/issues/674). Please create any `AzureCommunication.framework` related issue [here](https://github.com/Azure/azure-sdk-for-ios/issues)
