### ISSUE TITLE
Please provide documentation for Swift

### ISSUE THREAD

**Issue by jpickardsqr** [Azure/Communication#186]
The current iOS documentation shows only Objective-C. There is no documentation for Swift, which, while very similar, is different in some aspects (for example, the names of the classes omit the leading `ACS`). The `1.0.0-beta-6` release notes describe some differences between the Objective-C and Swift SDKs:
https://github.com/Azure/Communication/releases/tag/v1.0.0-beta.6

The Objective-C documentation is what you get if you click on `References > Calling Libraries > Calling (iOS)` from the main ACS documentation:
https://docs.microsoft.com/en-us/azure/communication-services/overview
https://docs.microsoft.com/en-us/objectivec/communication-services/calling/

Of course, it is possible there is Swift documentation that I have missed.

**Comment by ProbablePrime** [comment]
#AB2434542
