### ISSUE TITLE
SMS Short Codes/List threshold of SMS per second/minute

### ISSUE THREAD

**Issue by React365-Chris** [Azure/Communication#188]
We are reviewing the SMS side of ACS for a project in 2021 and the documentation is missing critical data. The project we are considering will require sending several thousand SMS messages per month, which we are currently doing with another provider. I need to know more around the amount of SMS messages that can be sent via ACS (per min/per second, etc.). 

The number is drastically different when using Short Codes. Are SMS Short codes something CS is considering supporting?

1. Support 'Short Codes'
2. Update documentation around service levels

Thanks,
Chris

**Comment by React365-Chris** [comment]
If I am asking this question on the wrong forum please let me know. Thanks for your help!

**Comment by Prakulka** [comment]
Hello @React365-Chris, Azure communication services does not support Short Codes at the moment. It is on our roadmap for later this year. A more granular roadmap will become available on our docs page closer to its launch. 

We currently support Toll-free numbers in US to send/receive messages. The current limit in Public preview is 100 messages/minute. This limit will change when we go to GA and our docs will be updated to reflect the new thresholds and SLAs. As for short code throughput, it will support higher volumes than toll free numbers.
