### ISSUE TITLE
iOS SDK: Unable to identify when the remote participant's mute and speaking states have changed

### ISSUE THREAD

**Issue by terrychen1122** [Azure/Communication#19]
During the call, I was not able to get notified when a remote participant unmuted/muted or was speaking.

To Reproduce:
1. Establish a call
2. Mute one participant and the other end is not able to get notified by this action

Expected behavior:
I was assuming the state of remote participant should have been changed and I could get notified by implementing the `ACSRemoteParticipantDelegate` protocol method `(void)onParticipantStateChanged:(ACSRemoteParticipant *)remoteParticipant :(ACSPropertyChangedEventArgs *)args`.

Below is the code snippet:
```
- (void)onRemoteParticipantsUpdated:(ACSCall *)call :(ACSParticipantsUpdatedEventArgs *)args {
    for (ACSRemoteParticipant *remoteParticipant in args.addedParticipants) {
        self.remoteParticipants[remoteParticipant.identity.getId] = remoteParticipant;
        remoteParticipant.delegate = self;
    ...
}
```
I also verified the other protocol method `(void)onVideoStreamsUpdated:(ACSRemoteParticipant *)remoteParticipant :(ACSRemoteVideoStreamsEventArgs *)args` did get called when I enabled and disabled the video stream.

If `(void)onParticipantStateChanged:(ACSRemoteParticipant *)remoteParticipant :(ACSPropertyChangedEventArgs *)args` is not the one I should listen for mute and speaking state changes, how could I do that?

 - Device: iPhone X
 - OS: 13.1

**Comment by raosanat** [comment]
``` onParticipantStateChanged``` callback on delegate ```ACSRemoteParticipantDelegate ``` should be raised when state of the remote participant changes from mute to unmute and you should be able to read the current state by reading the following property on the ```ACSRemoteParticipant``` object

```
/// True if the remote participant is muted
@property (readonly) BOOL isMuted;

```

Please give us sometime to reproduce the scenario at our end. In the meanwhile can you attach the logs of both the participants. The log file ```acs_sdk.log``` will be found in Cache folder of your app container.

**Comment by terrychen1122** [comment]
Is it this one? I found a file under Caches folder called `acs-sdk-0-4108691083.blog`. Zipped it.
[acs_sdk-0-4108691083.blog.zip](https://github.com/Azure/Communication/files/5272603/acs_sdk-0-4108691083.blog.zip)

**Comment by mariusu-msft** [comment]
@terrychen1122 we have confirmed this is a bug. Should be fixed in an upcoming release. Currently targeting the week of 10/6.

cc: @raosanat

**Comment by raosanat** [comment]
@terrychen1122  We have made a release which fixes this issue. Here is the link to the release  [AzureCommunicationCalling - v1.0.0-beta.4](https://github.com/Azure/Communication/releases/tag/v1.0.0-beta.4)
Please verify if the bug is fixed in the new release. Thanks.

**Comment by terrychen1122** [comment]
Thanks @raosanat . since we have new protocol methods, when the mute state changes, are we getting both `onParticipantStateChanged` and `onIsMutedChanged` or just getting `onIsMutedChanged`?

**Comment by mariusu-msft** [comment]
@terrychen1122 you will only get `onIsMutedChanged`. `onParticipantStateChanged` will get called only if the in-call state of the participant changes, such as transitioning between `Connected` and `Disconnected`.

Please let us know if you have any feedback in general about the API. As part of our Public Preview we are trying to capture as much feedback as possible.

**Comment by mariusu-msft** [comment]
Closing the issue as this should be fixed in latest release.

Thanks @terrychen1122 for the report!
