### ISSUE TITLE
Need Xamarin/MAUI solution

### ISSUE THREAD

**Issue by MhAllan** [Azure/Communication#190]
Microsoft and mobiles mean Xamarin/MAUI. Microsoft is too late in bringing this communication platform, but it is finally here. Except, unfortunately, as usual priorities go against Microsoft techs and developers so we see React components but no mention to Xamarin/MAUI

**Comment by mariusu-msft** [comment]
Hi,

We don't currently have plans for MAUI support.

For Xamarin (iOS and Android) there's an open source bindings project you may find useful which is maintained by @tompi 
https://github.com/Laerdal/Xamarin.AzureCommunicationCalling

For Cross-Plat Xamarin and MAUI support I'm adding @larodan to consider the ask and triage.

Thanks,
marius

**Comment by MhAllan** [comment]
open source libraries usually don't last long and fail to update by time. this is essential for .net developers to have official solutions in Xamarin/MAUI
