### ISSUE TITLE
[iOS] SDK crash when get a error in TokenRefresherClosure

### ISSUE THREAD

**Issue by AmyL219** [Azure/Communication#192]
**Describe the bug**
The SDK would crash with `ACSException` when ` TokenRefresherClosure` failed to get a token and just got a error.

**To Reproduce**
-Initialize the `CommunicationTokenRefreshOptions` with a tokenRefresher closure
`let tokenCredentialOptions = CommunicationTokenRefreshOptions(initialToken: nil, refreshProactively: true, tokenRefresher: tokenFetcher)`

- return a error with empty token in the tokenRefresher closure
`completionHandler(nil, error)`

-The SDK would crash

**Screenshots**
![Screen Shot 2021-01-28 at 1 50 17 PM](https://user-images.githubusercontent.com/75647512/108130439-86783f00-7064-11eb-84da-2633fb660a76.png)

**Smartphone (please complete the following information):**
 - Device: iphoneSE
 - OS: iOS14
 - Version: beta 8.0

**Logs**
[xcappdata1.zip](https://github.com/Azure/Communication/files/5992036/xcappdata1.zip)

**Comment by raosanat** [comment]
Created a [bug](https://skype.visualstudio.com/SPOOL/_backlogs/backlog/Calling/Features/?workitem=2378828) in our backlog to fix this issue.

**Comment by AmyL219** [comment]
[ADO Ticket](https://skype.visualstudio.com/SPOOL/_workitems/edit/2372241)

**Comment by mariusu-msft** [comment]
This is fixed in latest beta SDKs
