### ISSUE TITLE
[iOS] Question RemoteParticipantDelegate.onIsSpeakingChanged event

### ISSUE THREAD

**Issue by hyounoo** [Azure/Communication#193]
this event is triggered whenever remoteParticipant turns on / off mic not when they are really speaking.
I think this might related to mic sensitivity somehow?
If so, how can I configure this sensitivity so I can properly display whether remoteParticipant is actually speaking?

**Comment by raosanat** [comment]
Event should be raised when the remote participant is speaking. Can you verify if you still notice in the latest build ? But in either case you wont be allowed to configure the sensitivity.

**Comment by kagbakpem** [comment]
@hyounoo, this event might indeed be sensitive to background noise. Please make sure to also check the isSpeaking property on the RemoteParticipant object to report the speaking status as the event is triggered when the participant starts and stops speaking.

**Comment by hyounoo** [comment]
Haven’t check the latest beta. I’ll check the whether its working now.

**Comment by RinaRish** [comment]
@hyounoo any update?

**Comment by mariusu-msft** [comment]
@hyounoo the event is raised when there is sufficient audio activation from the remote participants.

Latest releases in BETA are less sensitive as we have enabled silence suppression. 

Please let us know if you have more questions. Closing this.
