### ISSUE TITLE
[iOS] SDK crash if user input an invalid teams meeting link on beta 9.0

### ISSUE THREAD

**Issue by AmyL219** [Azure/Communication#198]
**Describe the bug**
When the `TeamsMeetingLinkLocator` is initialized by an invalid meeting link, the SDK would crash with an `ACSException`
![Screen Shot 2021-02-22 at 11 29 47 AM](https://user-images.githubusercontent.com/75647512/108761299-844e2e80-7503-11eb-9bed-4cd9506080d9.png)

**To Reproduce**
1. create TeamsMeetingLinkLocator with an invalid meeting link
```let teamsMeetingLinkLocator = TeamsMeetingLinkLocator(meetingLink: "https://teams.microsoft.com/l/meetup-join/19%3")```
2. let CallAgent join with the link locator
```CallAgent.join(with:teamsMeetingLinkLocator)```
3. App would crash on running time

**Expected behavior**
App shouldn't crash

**Smartphone (please complete the following information):**
 - Device: iphone 11
 - OS: iOS 14.4
 - Version beta 8.0 & 9.0

**Logs**
[xcappdata22.xcappdata.zip](https://github.com/Azure/Communication/files/6024790/xcappdata22.xcappdata.zip)

**Comment by AmyL219** [comment]
[ADO ticket](https://skype.visualstudio.com/SPOOL/_workitems/edit/2402960)

**Comment by raosanat** [comment]
Fixed in beta.12 release.

**Comment by raosanat** [comment]
Still reproducible, figured out the issue will fix in next release.

**Comment by raosanat** [comment]
Fixed in the latest release [v2.1.0-beta.1](https://github.com/Azure/Communication/releases/tag/v2.1.0-beta.1). 
Please re-open the bug if still reproducible, thanks.
