### ISSUE TITLE
Roadmap is currently empty

### ISSUE THREAD

**Issue by johannesstock** [Azure/Communication#20]
The Roadmap Section (Projects - Roadmap) currently does not show any items.

Do we get a glimpse on whats planned or is this empty by purpose?

![image](https://user-images.githubusercontent.com/2735399/94023271-5333cb80-fdb6-11ea-82a4-e8b73694f5ae.png)

**Comment by anthonysva** [comment]
@johannesstock - at this time roadmap updates are posted to https://azure.microsoft.com/en-us/services/communication-services/

Are there specific features or capabilities you are seeking?

**Comment by johannesstock** [comment]
@anthonysva - Besides being informed about the direction you go, specifically important for me would be:
-Recording 
-Broadcast to broader audiences using Azure Media Services

**Comment by anthonysva** [comment]
Can you elaborate on the broadcasting and recording feature details? For example, with Broadcasting - what platforms, how large of an audience, do you need features to change cameras which are broadcasting, presenter specific controls, audience specific controls, etc. 

Thank you again for your feedback!

**Comment by johannesstock** [comment]
Sure, I'm happy to provide you with input. Here are my more specific wishes.

Broadcast/ Recording Targets & Audiences:
-A possibility to broadcast to an RTMP service of choice would be great (Azure Media Services, Youtube, Restream, Custom) 
-Having Azure Media Services Live Events as a target for streaming to a larger audience (>1000) would also suit our needs
-For a simple Recording an Azure storage account would be good

Camera Changes / Stream Content
-I think a good start would be to have the "auto arrangement" we are used to in a Teams group call as a single RTMP Stream/Recording
-More down the road, having the possiblity to recieve additional specific streams / recordings (Speaker Cam or Screenshare) would be a nice addition
-I could also image to have more control over the auto arranged like switching Layout from Gallery to Togeter mode / Large Gallery, Pin a specific participant to stage etc.
-Provide a list of People to be Broadcasted / Recorded

Presenter / Audience Controls:
-Privacy Feature: I Dont want to be on the Broadcast

**Comment by jolguk** [comment]
johannesstock's wishes are similar to mine:
Broadcast enablement, ideally to Azure Media Services.
Recording facility.

**Comment by tophpalmer** [comment]
Hey @johannesstock , @jolguk , I'm closing this issue as we have published a roadmap now and we have a card tracking this feature request. I do want to be candid that this feature area is pretty far off in the backlog but we'll continue to update our roadmap and appreciate your continued feedback!
