### ISSUE TITLE
[Android] CommunicationIdentifier.getId() return null for those participants from Teams meeting

### ISSUE THREAD

**Issue by AmyL219** [Azure/Communication#201]
**Describe the bug**
The `Identifier string` for those participants from Teams meetings could return null when I join a meeting through a `TeamsMeetingLinkLocator` from Android Calling SDK 
  
**To Reproduce**
1. Join a team meeting through `TeamsMeetingLinkLocator` from Android Calling SDK 
2. For the `RemoteParticipant` from `ParticipantsUpdatedEvent.getAddedParticipants()`, `remoteParticipant.getIdentifier().getId()` could return null 

**Expected behavior**
`remoteParticipant.getIdentifier().getId()` should return an unique identifier to every remote participant

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Google Pixel 4a
 - OS: Android 11
 - Version: beta 8.0

**Comment by kagbakpem** [comment]
`getId()` is not always populated for all identifiers in `azure-communication-common`, so for the time being, make sure to check the type of the identifier before calling the appropriate method to get the underlying string representation. Here is a snippet you could use:
`
        CommunicationIdentifier identifier = remoteParticipant.getIdentifier();
        if(identifier instanceof PhoneNumberIdentifier) {
            return ((PhoneNumberIdentifier) identifier).getPhoneNumber();
        } else if(identifier instanceof MicrosoftTeamsUserIdentifier) {
            return ((MicrosoftTeamsUserIdentifier) identifier).getUserId();
        } else {
            return identifier.getId();
        }
`

**Comment by lpx1989** [comment]
@kagbakpem I have an additional question regarding of this question. Is that possible for a remoteParticipant to have more than one identifiers? eg. having phone number ID and the normal id from getId() ?
