### ISSUE TITLE
Class name prefix in order to remove duplicate class names

### ISSUE THREAD

**Issue by jimmy555** [Azure/Communication#203]
In our application we use multiple video call providers as this is requested by our clients. For this reason we already have and use default classes such as Call, CallClient and CallState. Because the SDK also uses these class names, we get a lot of conflicts and it is not immediately clear which class is called. It is possible to fix this by calling the package name first, e.g. AzureCommunicationCalling.Call, but this is in my opinion not desired. What we would like to see, is that the SDK is going to use a prefix, ACS, for the class names, e.g. ACSCall, ACSCallClient and more. This will result in no conflicting class names and a better readability as you now know immediately from where this class belongs.

**Comment by raosanat** [comment]
Initially we did have the prefixes but we had to remove it because in Swift its not standard to have the prefixes. Please check the following link 
https://stackoverflow.com/questions/24214863/swift-class-prefix-needed

 since Swift has namespace support you should be able to use the package name before the Call or CallClient ?

**Comment by jimmy555** [comment]
Thanks for the response. Yes that is possible, but name of the package is pretty long (+- 5 times longer then the class names). If this is the way to go forward, maybe shorten the package name from AzureCommunicationCalling to ACS?

**Comment by raosanat** [comment]
I don't think that would be a possibility unfortunately. We follow a specific naming convention across Azure packages. We have a similar package `AzureCommunicationChat` and `AzureCommunication` for identities. If Swift provided something like python to shorten the imports would have been better.

**Comment by raosanat** [comment]
Closing this issue as of now. Because of the naming convention followed across Azure we cannot do much at this time, but we will discuss internally if there is any other possible solution for this.
