### ISSUE TITLE
 SMS is unavailable for geographic numbers at this time

### ISSUE THREAD

**Issue by mickeyfan007** [Azure/Communication#204]
When trying to get a phone number to use for SMS it says its unavailable at this time. I am in the US. Wondering when this will be available?
![SMS](https://user-images.githubusercontent.com/79708193/109328140-1cf7ed80-7827-11eb-8ce4-7fbdbe07349e.png)

**Comment by nmurav** [comment]
@Prakulka

**Comment by mickeyfan007** [comment]
This has now being fixed. Thanks!
