### ISSUE TITLE
Unable to restart video broadcast after stopping video

### ISSUE THREAD

**Issue by lanierc** [Azure/Communication#207]
**Describe the bug**
Upon stopping a LocalVideoStream from broadcasting to remote, when attempting to restart, the LocalVideoStream will not add itself back to `Call.localVideoStreams`. The list of LocalVideoStream will always be empty. be empty.

**To Reproduce**
Here is the code for the function that I have created to disable/re-enable broadcasting video:

```
    private fun disableVideo() {
        val cameraStreams = call.localVideoStreams
        println(cameraStreams)
        println(videoStream)
        if (cameraStreams.isNotEmpty() && videoIsBroadcasting) {
            call.stopVideo(videoStream).get()
            videoView.visibility = View.GONE
            stopVideoButton.text = "Show Video"
            videoIsBroadcasting = false
        } else {
            println("not broadcasting")
            val camera = deviceManager.cameraList[0]
            videoStream = LocalVideoStream(camera, applicationContext)
            call.startVideo(videoStream)
            videoView.visibility = View.VISIBLE
            videoIsBroadcasting = true
            stopVideoButton.text = "Hide Video"
        }
    }
```

**Expected behavior**
Video should restart broadcasting upon running this function a second time, with the LocalVideoStream returning to the list of LocalVideoStream on `Call`

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Google Pixel 4 XL
 - OS: Android 11.0
 - Browser N/A, performed in native app

**Additional context**
Written using Kotlin. I'm not 100% sure if this is a bug or something I've done wrong.

**Comment by kagbakpem** [comment]
@lanierc, thanks for reporting this issue. Can you please try this with the latest version of the SDK v1.2.0-beta.1 and report back if this is still a repro scenario? Thanks.
