### ISSUE TITLE
Is inbound PSTN on the roadmap?

### ISSUE THREAD

**Issue by HanzOhlo** [Azure/Communication#21]
Inbound PSTN is a desirable feature.  

With the ability to retrieve and use Caller ID as a variable.  Think a Call Center or Collections Dept app that routes an inbound call to an agent based on account ownership via Caller ID.

Thanks!

**Comment by NMuravlyannikov** [comment]
@HanzOhlo  yes inbound PSTN is on roadmap. Can you please give brief description of the scenarios you have in mind for the inbound PSTN?

**Comment by HanzOhlo** [comment]
Basically what was mentioned in the original post; being able to programmatically route an inbound call among a group of users and trigger actions based on the Caller ID and other inputs.  A "basic" customer service app for instance.  Thx!

**Comment by NMuravlyannikov** [comment]
Got it. Thanks, Yes on the roadmap. @boris-bazilevskiy
