### ISSUE TITLE
Unable to play sound through speaker when in group call - iOS and Android

### ISSUE THREAD

**Issue by Immons** [Azure/Communication#210]
**Describe the bug**
I am unable to play sound through speaker when in group call, there is only one device in Speakers and it's the "default" one which when set plays through headphone.

**To Reproduce**
1. Join group call with device 1 and device 2
2. No way to play sound through speaker instead headphone

**Expected behavior**
Some SDK feature to play sound through speaker

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S7, iPhone 12 Pro Max
 - OS: Android 7.1, iOS 14.4

**Comment by raosanat** [comment]
Audio devices cannot be controlled  through SDK. Please use platform API's to do that. Thanks.
