### ISSUE TITLE
Can we reuse created ACS user to rejoin/join call?

### ISSUE THREAD

**Issue by rashidbpg** [Azure/Communication#211]
Hi,

I was wondering if we could rejoin a user to a group call. Or do we have to create a user every time we want to join a group call?

I have logic in our back end that creates a user and stores the ACS ID in our database to reuse later. This works fine when we are joining the user initially to the group call. However, when the user leaves the group call we use the same ACS ID to try to join the group call. That seem to not work. Is this by design?

Thanks
Rashid

**Comment by mariusu-msft** [comment]
You should be able to join again with same user.

On which platform are you hitting this? Can you share Call ID + logs please?

**Comment by rashidbpg** [comment]
@mariusu-msft below is a subset of the logs. The frontend app calls the backend API to get the token. The backend will check DB to see if the specified user has an ACS comm ID. If so, call identity.issueToken(). If not, createUser() then call identity.issueToken(). I have found that the issue is that when I call createUser->issueToken condition, it will always work. However, if I just call issueToken to renew the token, the call will fail on the second time I join the same group.

**Environment:**
- ReactNative app with native Swift binding
- Backend API for generating/caching tokens and user ACS ID.

**Logs:**
Call agent successfully created. <ACSCallAgent: 0x6000004059e0>
Call created. Optional(<ACSCall: 0x6000004f15c0>)
CallID. Optional("a3c0bfeb-9199-43ec-955d-88ecb09d22e4")
Call joined
2021-03-03 19:54:34.044515-0800 Kismet[85515:532688] [aurioc] AURemoteIO.h:323:entry: Unable to join I/O thread to workgroup ((null)): 2
onCallStateChanged Optional(__C.ACSCallState)
onCallStateChanged CONNECTING
2021-03-03 19:54:35.523346-0800 Kismet[85515:532701] [aurioc] AURemoteIO.h:323:entry: Unable to join I/O thread to workgroup ((null)): 2
onCallStateChanged Optional(__C.ACSCallState)
onCallStateChanged CONNECTED
remote participants Optional("[]")
onCallStateChanged Optional(__C.ACSCallState)
onCallStateChanged DISCONNECTED
Call hung up
Call agent successfully created. <ACSCallAgent: 0x6000004e8080>
Call created. Optional(<ACSCall: 0x60000053bfa0>)
CallID. Optional("23366964-41ea-4410-aa39-019ff02666d6")
Call joined

**Comment by mariusu-msft** [comment]
```if I just call issueToken to renew the token, the call will fail on the second time I join the same group.```


@rashidbpg do you have an issue when you try to create to issue the new token, or when you try to use that token?

Couple more questions:
- Is the token for the same user? 
- If so, why do you need to create a new CallAgent? 

You could reuse the same CallAgent instance, or try to pass in a TokenCredential to CallAgent that supports refresh.

What is the scenario you are trying to implement?

**Comment by rashidbpg** [comment]
> `if I just call issueToken to renew the token, the call will fail on the second time I join the same group.`
> 
> @rashidbpg do you have an issue when you try to create to issue the new token, or when you try to use that token?
> 
> Couple more questions:
> 
> * Is the token for the same user?
> * If so, why do you need to create a new CallAgent?
> 
> You could reuse the same CallAgent instance, or try to pass in a TokenCredential to CallAgent that supports refresh.
> 
> What is the scenario you are trying to implement?

In any scenario, reuse and old or newly generated token, the first time connecting works and fires the status events OK. However, if I reuse a token, it will always fail on the second join() call without an error being thrown. It will also fail on the second join() as well if I just reissue/renew a token for an existing acs user id. Hope that makes sense.

If I generate a new token before every join() call, it will always succeed. 

The scenario we are trying to solve is the ability to map our user to an ACS ID and allow our users to quickly join and rejoin groups without too many calls. We need to be able to allow our users to quickly switch between "groups" without a long delay due to token issuance and user creation.

**Comment by mariusu-msft** [comment]
@rashidbpg can you try your scenario without creating a new CallAgent?

We don't support creating two CallAgents with same identity, we may not be failing gracefully here.

Basically try this:

create CallAgent A for user Alice
call = A.join(...)
call.hangup()

call2 = A.join(...)
call2.hangup()

**Comment by rashidbpg** [comment]
> @rashidbpg can you try your scenario without creating a new CallAgent?
> 
> We don't support creating two CallAgents with same identity, we may not be failing gracefully here.
> 
> Basically try this:
> 
> create CallAgent `A` for user Alice
> call = A.join(...)
> call.hangup()
> 
> call2 = A.join(...)
> call2.hangup()

OK, trying it now.

**Comment by rashidbpg** [comment]
@mariusu-msft I modified the logic to reuse the call agent and also another tweak on the backend. Seems to be working better now. I can join and rejoin the same group. However, when I try to join another group, it is behaving the same as before, no events or errors but not joined. It may be something we are doing wrong on our end so I am going to give a few things a try.

Should we be using the same instance of the callclient and callagent throughout the lifecycle of our application?

**Comment by mariusu-msft** [comment]
@rashidbpg if you are using the same user yes. You should be using the same instance of CallAgent.

With the changes to reuse the same instance of a callAgent for join, can you please provide client logs? You can follow instructions here:

https://docs.microsoft.com/en-us/azure/communication-services/concepts/troubleshooting-info?tabs=csharp%2Cios%2Cdotnet#enable-and-access-call-logs

**Comment by rashidbpg** [comment]
@mariusu-msft it is working well now, after some refactoring of how we initialize and join calls. I am now using the same client and call agent throughout. I am also able to reuse the token/user so I am set for now. We are excited to test this service to see if it can hold a very large group session.

Thank you for your quick and very helpful responses!

**Comment by mariusu-msft** [comment]
I'm happy you sorted this out. I will leave this open as a Bug to fix instantiation of multiple call agents with same identity.

We appreciate your feedback!

**Comment by rashidbpg** [comment]
@mariusu-msft I am now working on the Android integration. However, I am running into some major issues with a simple operation of creating a call agent. The below Java code is causing the following exception. Can you help me with this as well?

```
private void createAgent(String token, String displayName) {
    try {
      Log.d("ACS", "creating agent");
      CommunicationTokenCredential credential = new CommunicationTokenCredential(token);
      CallAgentOptions options = new CallAgentOptions(); // this causes
      options.setDisplayName(displayName);

      CallClient callClient = new CallClient();

      this.callAgent = callClient.createCallAgent(this.getReactApplicationContext(), credential, options).get();
      Log.d("ACS", "agent created");
    } catch (Exception ex) {
      // TODO: Error handling
      Log.d("ACS", "Exception creating agent", ex);
    }
  }
```

**LogCat Error:**
`2021-03-05 17:25:59.708 32192-32300/com.Likewise.apps.Radiant E/se.apps.Radian: No implementation found for com.azure.android.communication.calling.internal.status com.azure.android.communication.calling.internal.NativeLibrary.sam_call_agent_options_create(com.azure.android.communication.calling.internal.Out) (tried Java_com_azure_android_communication_calling_internal_NativeLibrary_sam_1call_1agent_1options_1create and Java_com_azure_android_communication_calling_internal_NativeLibrary_sam_1call_1agent_1options_1create__Lcom_azure_android_communication_calling_internal_Out_2)
2021-03-05 17:25:59.709 32192-32300/com.Likewise.apps.Radiant W/se.apps.Radian: Got a deoptimization request on un-deoptimizable method com.azure.android.communication.calling.internal.status com.azure.android.communication.calling.internal.NativeLibrary.sam_call_agent_options_create(com.azure.android.communication.calling.internal.Out)
2021-03-05 17:25:59.709 32192-32300/com.Likewise.apps.Radiant W/se.apps.Radian: Got a deoptimization request on un-deoptimizable method java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[])
2021-03-05 17:25:59.709 32192-32300/com.Likewise.apps.Radiant W/se.apps.Radian: Got a deoptimization request on un-deoptimizable method java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[])
2021-03-05 17:26:03.841 32192-32300/com.Likewise.apps.Radiant E/unknown:ReactNative: Exception in native call
    java.lang.RuntimeException: Could not invoke AzureCommunicationService.initCall
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:383)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:223)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151) 
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27) 
        at android.os.Looper.loop(Looper.java:223) 
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226) 
        at java.lang.Thread.run(Thread.java:923) 
     Caused by: java.lang.UnsatisfiedLinkError: No implementation found for com.azure.android.communication.calling.internal.status com.azure.android.communication.calling.internal.NativeLibrary.sam_call_agent_options_create(com.azure.android.communication.calling.internal.Out) (tried Java_com_azure_android_communication_calling_internal_NativeLibrary_sam_1call_1agent_1options_1create and Java_com_azure_android_communication_calling_internal_NativeLibrary_sam_1call_1agent_1options_1create__Lcom_azure_android_communication_calling_internal_Out_2)
        at com.azure.android.communication.calling.internal.NativeLibrary.sam_call_agent_options_create(Native Method)
        at com.azure.android.communication.calling.CallAgentOptions.<init>(CallAgentOptions.java:53)
        at com.Likewise.modules.RNAzureCommunicationService.RNAzureCommunicationService.createAgent(RNAzureCommunicationService.java:101)
        at com.Likewise.modules.RNAzureCommunicationService.RNAzureCommunicationService.initCall(RNAzureCommunicationService.java:50)`

Also, when I remove the CallAgentOptions parameter from createCallAgent(), the app closes with SIGABRT and no other exception. Thank you in advance!

**Comment by kagbakpem** [comment]
@rashidbpg, which version of the SDK are you using and which ABI/device is this error happening on? The error seems to elude to the fact it is an unsupported ABI or potentially a AOSP variant we haven't tested on. IF you can provide these details, it'll help us further debug.

Thanks

**Comment by rashidbpg** [comment]
> @rashidbpg, which version of the SDK are you using and which ABI/device is this error happening on? The error seems to elude to the fact it is an unsupported ABI or potentially a AOSP variant we haven't tested on. IF you can provide these details, it'll help us further debug.
> 
> Thanks

I am using SDK version 30 with an Android R X86_64 image emulator. This is a ReactNative project that I am trying to integrate the ACS SDK. 

Below are the errors I was getting:

```
Execution failed for task ':app:mergeDebugNativeLibs'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeJavaResWorkAction
   > 2 files found with path 'lib/x86/libc++_shared.so' from inputs:
      - /Users/rashid/.gradle/caches/transforms-2/files-2.1/483bd9f2bbf62aa83cc74a68a4897878/jetified-react-native-0.63.4/jni
      - /Users/rashid/.gradle/caches/transforms-2/files-2.1/7b050d47ff824e7389d223b05a46e608/jetified-azure-communication-calling-1.0.0-beta.8/jni
     If you are using jniLibs and CMake IMPORTED targets, see
     https://developer.android.com/r/tools/jniLibs-vs-imported-targets

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

I was able to get it to work by statically including the libc++_shared.so in my project. I want to avoid this however.

**Comment by kagbakpem** [comment]
@rashidbpg, we are aware of the native libc++_shared.so duplication issue with RN and will be working on providing a solution in the future. I noticed you're using RN 0.63.4? Is everything working as expected for you thus far?

**Comment by rashidbpg** [comment]
@kagbakpem actually no, not everything is working. I'm still getting failures when trying to create a call agent with options to set the display name. It's the error I mentioned above. I really need to find a solution to these issues as this is a big feature that we were hoping for our next release that is coming soon. So, any suggestions would be greatly appreciated.

I'm using RN 0.63.4 because I created a new project to test the integration. Is there a version that I should be using?

**Comment by kagbakpem** [comment]
@rashidbpg, We've had success with RN 0.61.5, 0.62.0-rc.0 and 0.62.0-rc.1 thus far. I suggest you give one of these versions a try if that works for you.
Re: the issue with createCallAgent API on CallClient, have you tried this without the CallAgentOptions? If so, does that work? I am trying to gather all the variables here to better assess the issue from our end and provide a fix. Thanks

**Comment by rashidbpg** [comment]
@kagbakpem creating an instance of CallAgentOptions causes the issue. I can create an instance of the call agent without the options. Therefore, we cannot show the user name of the participants without CallAgentOptions, unless there is another API to use.

**Comment by rashidbpg** [comment]
Also, is there a jdk, ndk, and jni we should be using?

**Comment by rashidbpg** [comment]
@kagbakpem I notice that the ACS Android Quickstart also has the same issue with the CallAgentOptions, FYI. Seems like there is something wrong with that class definition.

**Comment by rashidbpg** [comment]
@kagbakpem I'm having the same issues for my sample RN app and the ACS quick start sample on the emulator and on my device. My device is on Android 11

**Comment by rashidbpg** [comment]
@kagbakpem @mariusu-msft are there any suggestions/updates on this? I understand that ACS is still in preview but this is blocking progress integrating with ACS. We were hoping to leverage ACS for our group call/chat rollout.

**Comment by rashidbpg** [comment]
> @rashidbpg, i'll investigate and let you know by EOD Thanks.

@kagbakpem Great! Thank you very much. That would be very helpful.

**Comment by rashidbpg** [comment]
@kagbakpem Ah, great! That does work. I didn't realize that the order matters. I am sorry if this is documented, however I didn't see it. Thank you for the update

**Comment by mariusu-msft** [comment]
Closing since this seems to be resolved
