### ISSUE TITLE
Issue Implementing Video Calling

### ISSUE THREAD

**Issue by tjprescott** [Azure/Communication#212]
@jimmy555 commented on [Tue Mar 02 2021](https://github.com/Azure/azure-sdk-for-ios/issues/737)

**Describe the bug**

I'm trying to use the SDK to implement video calling. From our backend, I receive a Teams URL which I can join from within our iOS app. When I join the call, I see the camera of the application in the Teams app on my laptop. Thus the SDK is sending the camera. But sadly enough I do not see the preview of the camera in the app. It feels like the problem is with the
`self.localVideoView = try self.renderer!.createView()` line. I checked to see what the size of Frame is (`self.localVideoView.frame`) but this resulted in (0, 0, 0, 0). I tried adding the created view as a subview but with no success:

```
let localView = try self.renderer!.createView()

self.localVideoView.addSubview(localView)
```

***Exception or Stack Trace***
Add the exception log and stack trace if available

Device manager is set -> ACS device manager is set
Set audio session -> Created audio session
Set local camera -> Called before the `let camera = self.deviceManager!.getCameraList()!.first` line
Localview frame: Optional((0.0, 0.0, 0.0, 0.0)) -> Printed the frame of the local view after the `try self.renderer!.createView()`
Join meeting
Start video success
State changed: Connecting
State changed: Unknown -> I don't know if this is a bug as well, but to me it looks like the user is in the Lobby, but the SDK says that the state is unknown. After I let the user join the call in the Teams app, the state changes to Connected. 

**To Reproduce**

I guess you can reproduce it by using the code I added.

***Code Snippet***
Add the code snippet that causes the issue.

        let locator = TeamsMeetingLinkLocator(meetingLink: "<TEAMS URL>")
        
        let callOptions = JoinCallOptions()
        
        let camera = self.deviceManager!.getCameraList()!.first
        let localVideoStream = LocalVideoStream(camera: camera)
        let videoOptions = VideoOptions(localVideoStream: localVideoStream)
        callOptions?.videoOptions = videoOptions
        
        do {
            self.renderer = try Renderer(localVideoStream: localVideoStream!)
            
            do {
                self.localVideoView = try self.renderer!.createView()
                
                guard let call =  self.callAgent?.join(with: locator, joinCallOptions: callOptions) else {
                    print("Error: failed to join call")
                    return
                }
                
                self.call = call
                self.call?.delegate = self
                self.call?.startVideo(stream: localVideoStream, completionHandler: { error in
                    if let err = error {
                        print("Start video error: \(err)")
                    } else {
                        print("Start video success")
                    }
                })
            } catch let error {
                print("Failed to create local view: \(error)")
            }
        } catch let error {
            print("Failed to create local renderer: \(error)")
        }

**Expected behavior**

I expect the `try self.renderer!.createView()` to create a view that shows the video stream of the user.

**Screenshots**

The blue View is the `self.localVideoView` which I made blue to show the View.

![WhatsApp Image 2021-03-02 at 14 41 30](https://user-images.githubusercontent.com/11029052/109657359-b5fb7100-7b65-11eb-8997-a53ecf9db5bc.jpeg)

**Setup (please complete the following information):**
 - OS: MacOS [e.g. iOS]
 - IDE : Xcode [e.g. IntelliJ]
 - Version of the Library used: 1.0.0-beta.8

**Additional context**

The CallClient and CallAgent are all setup fine. There is no problem there as far as I can see. 

What might be good to know is the the localVideoView is send from the UIViewController to a class via a protocol. In that class, the view is used. Example code:

```
protocol TempProtocol {
 func sendLocalVideoView(_ view: UIView)
}

class VideoVC: UIViewController {
   @IBOutlet weak var localVideoView: UIView!

   var delegate: TempProtocol?

   self.delegate.sendLocalVideoView(self.localVideoView)
}

class TempImplementation: TempProtocol {
   var localVideoView: UIView?

   func sendLocalVideoView(_ view: UIView) {
      self.localVideoView = view
   }

  // The code in Code Snippet is used here.
```

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ X] Bug Description Added
- [ X] Repro Steps Added
- [ X] Setup information Added

---

@tjprescott commented on [Tue Mar 02 2021](https://github.com/Azure/azure-sdk-for-ios/issues/737#issuecomment-789297340)

@jimmy555 which module are you importing in your code? 

@RezaJooyandeh please tag the appropriate developer.

---

@jimmy555 commented on [Wed Mar 03 2021](https://github.com/Azure/azure-sdk-for-ios/issues/737#issuecomment-789793980)

@tjprescott I'm using these modules:

```
pod 'AzureCommunicationCalling', '~> 1.0.0-beta.8'
pod 'AzureCommunication', '~> 1.0.0-beta.8'
pod 'AzureCore', '~> 1.0.0-beta.8'
```

**Comment by raosanat** [comment]
Hi @jimmy555 we have successfully had rendering of local and remote participant video streams. Without the entire application its a bit hard to know what exactly is going on. One thing  you could try is just create a normal UIView without using AzureCommunicationCalling SDK and try to render that and see if it works. The `createView` API returns an object inherited from `UIView`.

**Comment by jimmy555** [comment]
Hi @raosanat, I tried using a normal UIView and I found out that the problem has to do with the frame of the view. The createView returns a `RendererView` which has a frame of `(0,0,0,0)`. This results in the view not being shown. When I add the width and the height of the `localVideoView` I created in the Storyboard, the `RendererView` is shown. Is this a known issue?

The code used to present the `RendererView`.
```
let localView = try self.renderer!.createView()
let w = self.localVideoView?.width ?? 0
let h = self.localVideoView?.height ?? 0
localView.frame = CGRect(x: 0, y: 0, width: w, height: h)
self.localVideoView?.addSubview(localView)
```

**Comment by sankum-msft** [comment]
@jimmy555 can you please share implementation of `UIViewRepresentable` that you are using to attach `RendererView` to Swift UI?

**Comment by mariusu-msft** [comment]
@jimmy555 is this issue resolved?

**Comment by mariusu-msft** [comment]
Closing.
