### ISSUE TITLE
[iOS] Hang up the call automatically when the call is released

### ISSUE THREAD

**Issue by terrychen1122** [Azure/Communication#213]
Problem:
Recently, we ran into an issue where a view controller contains a call and this view controller was dismissed accidentally by other components in the app. When this view controller was dismissed, the call was active. In this case, the call was deallocated, but the camera was still being used and the current user was still in the call. 

Proposed solution:
When an active call is released, I suggest having the sdk automatically hang up the call.

Alternative:
To work around this (to prevent any edge cases that dismiss our view controller), we call `hangup` to the call in this view controller's `dealloc`.

**Comment by mariusu-msft** [comment]
This is currently by design.

As long as a CallClient instance exists, and there are active Calls on the instance of CallClient, the Call object will be kept alive.
