### ISSUE TITLE
SDK crash when another video guest user join the Teams meeting from Web/App

### ISSUE THREAD

**Issue by AmyL219** [Azure/Communication#216]
**Describe the bug**
The App crashed by a thread kill in SDK
![Screen Shot 2021-03-03 at 4 26 22 PM](https://user-images.githubusercontent.com/75647512/110165088-3a890200-7da7-11eb-8ec0-460557f761bd.png)

**To Reproduce**
1. Use CallingSDK to join a Teams meeting with more than 5 people by an meeting link 
2. Use the meeting link to join on a private web browser as a guest user. Make sure join meeting with open the camera . 
3. Give admission to the guest user in the Teams meeting
4.  The CallingSDK crash

**Expected behavior**
The CallingSDK should send an remote participant update

**Desktop (please complete the following information):**
 - Browser:  chrome 

**Smartphone (please complete the following information):**
 - Device: iphone SE
 - Version: beta 8.0

**Logs**
[TeamsInteropCrash.zip](https://github.com/Azure/Communication/files/6092980/TeamsInteropCrash.zip)

**Comment by ashishvirani7** [comment]
@AmyL219 this issue will be resolved in next release!

**Comment by AmyL219** [comment]
[ADO ticket](https://skype.visualstudio.com/SPOOL/_workitems/edit/2392661)

**Comment by kagbakpem** [comment]
A fix for this issue will be available in the upcoming android 1.0.0-beta.10 release.
