### ISSUE TITLE
Failed to get the participant list after state changed to connected in the addOnStateChangedListener 

### ISSUE THREAD

**Issue by AmyL219** [Azure/Communication#217]
**Describe the bug**
I can get the participant list in the addOnStateChangedListener if the state is `connecting`/ `inLobby`. 
Whenever the call state changes to `connected`, the remote participant list couldn't be fetched anymore. 

**To Reproduce**
1. Join a Team meeting through the meeting link
2. Give admission to the guest user in the Teams
3. The callState change to `connected` inside `OnStateChangedListener`
4. Unable to fetch the participant list in the `OnStateChangedListener`

**Expected behavior**
Should be able to fetch the participant list in the `OnStateChangedListener`

**Screenshots**
![image](https://user-images.githubusercontent.com/75647512/110166130-bfc0e680-7da8-11eb-96ed-654b1dce3eab.png)

**Smartphone (please complete the following information):**
 - Version : beta 8.0

**Comment by kagbakpem** [comment]
@AmyL219, this issue will be resolved in beta.9.

**Comment by AmyL219** [comment]
[ADO Ticket](https://skype.visualstudio.com/SPOOL/_workitems/edit/2388621)

**Comment by kagbakpem** [comment]
@AmyL219, this should be fixed in the latest version, v1.2.0-beta.1. Please give it a try and let us know if the issue persists.
