### ISSUE TITLE
remoteParticipants/onRecordingActive listener not being trigger after callState change to connected

### ISSUE THREAD

**Issue by AmyL219** [Azure/Communication#218]
**Describe the bug**
There are 30% chance when I join a Teams meeting by a meeting link, the remoteParticipants/onRecordingActive listener would not be triggered even there are remote participants change in the meeting 

**To Reproduce**
1. Join a Teams meeting with more than 1 person by a link
2. Give admission to this guest user from the Teams Meeting
3. OnStateChanged to `connected` in the App
4. No more update on `OnRemoteParticipantsUpdatedListener` even there is remote participant join/leave the meeting
5. Turn on/off video recording in the Teams meeting can't trigger update `OnIsRecordingActiveChangedListener`

**Expected behavior**
`OnRemoteParticipantsUpdatedListener` and `OnIsRecordingActiveChangedListener` should be triggered when there is user join/leave meeting and video recording change on the Teams meeting

**Additional context**
Please let me know if you want me provide any file for debugging

**Comment by AmyL219** [comment]
[ADO tickrt](https://skype.visualstudio.com/SPOOL/_workitems/edit/2388608)

**Comment by kagbakpem** [comment]
@AmyL219, this should be resolved in the latest version v.1.2.0-beta.1. Give it a try and let us know if the issue persists. Thanks
