### ISSUE TITLE
nhandled Rejection (SyntaxError): Unexpected end of JSON input ( after selecting avatar and name )

### ISSUE THREAD

**Issue by Githamza** [Azure/Communication#22]
I get these errors after running the app

I followed the steps mentioned
the run project `dotnet run` 

I get this error on browser
```
Unhandled Rejection (SyntaxError): Unexpected end of JSON input
▼ 3 stack frames were expanded.
getToken
src/core/sideEffects.ts:720
async
src/core/sideEffects.ts:64
async Object.setup
src/containers/ConfigurationScreen.ts:18
```

And in console

```
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HM2VP*****", Request id "0HM2VPP3******": An unhandled exception was thrown by the application.
System.UriFormatException: Invalid URI: The URI is empty.
```

**Comment by ddematheu2** [comment]
On which of the samples is this happening?

**Comment by alex-kwan** [comment]
> I get these errors after running the app
> 
> I followed the steps mentioned
> the run project `dotnet run`
> 
> I get this error on browser
> 
> ```
> Unhandled Rejection (SyntaxError): Unexpected end of JSON input
> ▼ 3 stack frames were expanded.
> getToken
> src/core/sideEffects.ts:720
> async
> src/core/sideEffects.ts:64
> async Object.setup
> src/containers/ConfigurationScreen.ts:18
> ```
> 
> And in console
> 
> ```
> fail: Microsoft.AspNetCore.Server.Kestrel[13]
>       Connection id "0HM2VP*****", Request id "0HM2VPP3******": An unhandled exception was thrown by the application.
> System.UriFormatException: Invalid URI: The URI is empty.
> ```

I was wondering can you confirm you entered a resource connection string into the appsettings.json?

**Comment by Githamza** [comment]
Yes I have entreted connection string.
This is happening on chat sample

**Comment by alex-kwan** [comment]
Thanks for the clarification!

I understand the issue now. When creating a ChatClient you will require an additional URL in the constructor. By default, there is an empty string. You will need to fill this value with a string that matches your Azure Communication Services resource

![image](https://user-images.githubusercontent.com/704758/94153208-5750ff00-fe31-11ea-85e5-3b559da29d16.png)

**Comment by alex-kwan** [comment]
@Githamza I was wondering if this solved your issue and we can close this?

**Comment by alex-kwan** [comment]
@Githamza closing, feel free to reopen
