### ISSUE TITLE
onRemoteParticipantsUpdated update the participant state to `.idle` when the participant is inLobby

### ISSUE THREAD

**Issue by AmyL219** [Azure/Communication#221]
**Describe the bug**
The remote participant state is not correct when the participant is waiting permission in Teams room. The state of the participant is `.idle` rather than `.inLobby`.
Not sure if it's expected or a bug. Please let me know. 

**Do you have any documentation about when the value of ACSParticipantState/ACSCallState would change?** 
The document can help us in determining how to handle each state change. I only can find the [description] of each state. (https://docs.microsoft.com/en-us/objectivec/communication-services/calling/acsparticipantstate) . 

**To Reproduce**
1. Use Calling SDK to join a Teams meeting and get the permission 
2. Use web browser to join the Teams meeting as a guest user, don't give him permission of join
3. `onRemoteParticipantsUpdated` get fired, and the new guest user added, but the state of the participant is `.idle` rather than `.inLobby`

**Expected behavior**
The state of the participant who is waiting in Lobby for permission should be `.inLobby` rather than `idle`

**Screenshots**

**Desktop (please complete the following information):**
 - Version: beta 8.0

**Comment by AmyL219** [comment]
[ADO ticket](https://skype.visualstudio.com/SPOOL/_workitems/edit/2397385)

**Comment by akania** [comment]
@AmyL219 can you please provide more details
1) is there a Teams user who admits user who joins with " Calling SDK"
2) " Calling SDK" - that's iOS ?
3) "onRemoteParticipantsUpdated get fired,..." - that's observed on "Calling SKD " side ?

**Comment by AmyL219** [comment]
@akania 
1. The scenario is when the app user **(named A)** is **connected** to an ongoing Teams meeting, there is another app/web guest user **(named B)** want to join the meeting and **waiting in lobby**. When app user A gets a `addOnRemoteParticipantsUpdated`, and accesses to `userB.getState()`, it returns `idle` rather than `inLobby`. When someone admits userB to the meeting, the  `userB.getState()` would become `connected` which is sensible.
**I doubt if it's sensible when a user is waiting in lobby, other participants read the user's state as IDLE?**
![Screen Shot 2021-03-22 at 1 55 12 PM](https://user-images.githubusercontent.com/75647512/112057224-3df5ea80-8b16-11eb-9b81-e4facaf1719d.png)
![Screen Shot 2021-03-22 at 1 46 27 PM](https://user-images.githubusercontent.com/75647512/112057234-40f0db00-8b16-11eb-9968-53857188d57a.png)

**Comment by AmyL219** [comment]
2. I just test Android. So this issue exists both on iOS and Android
3. Yes, on the delegate for iOS and listener on Android

**Comment by ashishvirani7** [comment]
@AmyL219 Thanks for reporting! This is fixed for both Android/iOS and it will be available in next release!
