### ISSUE TITLE
Custom message between peers in Azure Communication Services

### ISSUE THREAD

**Issue by hoangph271** [Azure/Communication#222]
I successfully created a working example of a group call using (Azure Communication Services).
But as I scroll through the pages, I can't find a way to emit/receive custom message (custom event) between clients...!

For example, in a group call of Bob, Alice, and Sia:

Bob emit "suggest-camera-on"
Alice & Sia would then receive the event and show a dialog asking "Do you want to turn on the camera"...!

How can I achieve this...?

**Comment by mariusu-msft** [comment]
Hi,

We do not currently support exchanging messages between peers in a group call.

Once potential suggestion is to use ACS Chat SDK side by side with Calling, and exchange messages via that channel.

Adding @RinaRish for future consideration of this ask.

Thanks for your feedback.
-Marius

**Comment by ProbablePrime** [comment]
I'm going to close this and link it to #223 ,
