### ISSUE TITLE
Request: allow `chatThreadClient.sendMessage` to send Custom Message Types

### ISSUE THREAD

**Issue by hoangph271** [Azure/Communication#223]
https://azuresdkdocs.blob.core.windows.net/$web/javascript/azure-communication-chat/1.0.0-beta.5/globals.html#chatmessagetype

As described in the above url, the ChatMessageType type is any string...!
However, if I send a message with my custom type like this:

```js
chatThreadClient.sendMessage({
  content: `@group-created ${groupId}`
}, {
  type: '@custom-type'
})
```
The invocation will fail, with the error attached in the image...!

**To Reproduce**
Create an ACS Chat app, `sendMessage` with `type` is a custom value

**Expected behavior**

The `chatThreadClient.sendMessage` method should allow custom message type...!

**Screenshots**

<img width="832" alt="Screen Shot 2021-03-11 at 16 54 53" src="https://user-images.githubusercontent.com/39024711/110769745-1e93cd80-828b-11eb-8b4e-d2e40d19d71f.png">

**Desktop**
 - OS: macOs
 - Browser: Chrome
 - Version: 89.0.4389.82 (Official Build) (arm64)

**Comment by ProbablePrime** [comment]
Hey @hoangph271 this is likely a bug in our documentation as the chat services currently do not support custom message types. Ideally this should restrict you a little bit more with the types(if using typescript), or in the documentation.

I picked this up by looking at the documentation a little more closely but I also read our REST docs: https://docs.microsoft.com/en-gb/rest/api/communication/chat/chatthread/sendchatmessage#chatmessagetype

This could most certainly be clearer. I'll assign this to myself and see what we can do but I don't think this is currently a bug more a documentation issue/feature request.

Thanks!

**Comment by hoangph271** [comment]
I'm planning to use ACS Chat SDK as an event channel between peers in my group participants...!
So I wanted a custom message type of my own, would this be possible in the future...?

**Comment by ProbablePrime** [comment]
I have logged this with the chat team, but cannot commit to it existing right now. We will take the feedback into account though. 

#AB2401968

**Comment by juancamilor** [comment]
Hi @hoangph271 .
We will be releasing a new feature soon where you can add metadata to your messages as a dictionary of key-value pairs, so you could use it in your scenario. The feature will be release in public preview in the next month.
