### ISSUE TITLE
Memory leak Renderer View for LocalVideoStream

### ISSUE THREAD

**Issue by iaulakh** [Azure/Communication#224]
**Describe the bug**
The Android Profiler for application developed using azure-communication-calling:1.0.0-beta.8 indicates memory leak for LocalVideoStream even though Renderer and RendererView are disposed.

![Screen Shot 2021-03-08 at 4 16 02 PM](https://user-images.githubusercontent.com/73618019/110845474-859b8d00-825f-11eb-8ff4-2b889c70c291.png)

**To Reproduce**
1. Start a call 
2. Turn on local user camera
3. No remote participant is in call
4. Disconnect call 

**Expected behavior**
After call disconnect the Renderer View may not hold memory. 

**Additional context**
Dispose is called on both Renderer and RendereView when activity ends.

- azure-communication-calling:1.0.0-beta.8

[https://skype.visualstudio.com/SPOOL/_workitems/edit/2399761](Azure DevOps Bug URL)

**Comment by RinaRish** [comment]
this issue was resolved, please fill free to reopen if persists
