### ISSUE TITLE
Turning the local video off/on quickly shows a blank local video

### ISSUE THREAD

**Issue by iaulakh** [Azure/Communication#225]
**Describe the bug**
As Renderer is created from LocalVideoStream and we can not bind LocalVideoStream to two renderer. Once we dispose Render, the LocalVideoStream can not be bind to other Render immediately. The new Render does not show LocalVideoStream. However, if after Render dispose We wait for a second and create new Render then it shows video. [[azure-communication-calling:1.0.0-beta.8]](url)

**To Reproduce**
1. turn on camera
2. toggle camera button (turn  off, then turn on)
3. video is not displayed

**Expected behavior**
On quick camera button toggle the video feed should be displayed.

**Additional context**
As per communication with SDK team "There is a bug in that path where dispose returns before the full cleanup."

- [azure-communication-calling:1.0.0-beta.8]

[https://skype.visualstudio.com/SPOOL/_workitems/edit/2399773](Azure Bug)

**Comment by raosanat** [comment]
This is resolved in the latest build. Please verify and re-open again if you still see issues. Thanks.

**Comment by raosanat** [comment]
Closed by mistake, assuming it was iOS.

**Comment by kagbakpem** [comment]
@iaulakh, can you please test this on the latest SDK version (1.0.0) freshly released yesterday? ty

**Comment by iaulakh** [comment]
> @iaulakh, can you please test this on the latest SDK version (1.0.0) freshly released yesterday? ty

Thanks @kagbakpem. I will test this week and will leave comments once done.

**Comment by iaulakh** [comment]
works fine. Thanks @kagbakpem

**Comment by kagbakpem** [comment]
Great, thx for the update, @iaulakh.
