### ISSUE TITLE
FAT framework

### ISSUE THREAD

**Issue by terrychen1122** [Azure/Communication#226]
Can we also provide FAT framework for the iOS release on cocoapods?

Only cocoapod 1.9+ supports XCFramework. Unfortunately, we are still using 1.8.4 and upgrading it right now will be a big undertaking.

**Comment by tompi** [comment]
@terrychen1122 just FYI, its quite easy to create this, I needed this as well, this command should do it:

```
lipo -create ./ios-arm64/AzureCommunicationCalling.framework/AzureCommunicationCalling ./ios-x86_64-simulator/AzureCommunicationCalling.framework/AzureCommunicationCalling -output AzureCommunictionCalling
```

**Comment by terrychen1122** [comment]
@tompi yes, it's doable to remake FAT out of it. However, I don't think it's possible if we are using cocoapods. Before we upgrade to cocoapods 1.9, we can't use cocoapods to pull in this library.

**Comment by raosanat** [comment]
@terrychen1122  supporting 2 ways might be a bit of an overhead for us as most of customers are fine with xcframework. @tjprescott can you please provide input here, if its possible to do this ?

**Comment by tjprescott** [comment]
@raosanat my understanding is that since the podspec can only point to one source, you would need to publish the FAT framework ZIP somewhere and have a separate podspec to target that. However, we would not publish that podspec to trunk, so the customer would need to add a separate specs repo or target the podspec directly either locally or by URL.

**Comment by terrychen1122** [comment]
Understood. Meanwhile, before migrating to cocoapods 1.9, we will stick to linking the binary framework directly.

**Comment by raosanat** [comment]
Closing this for now, if you need us to publish a separate FAT framework package as well please let us know. We though would not be able to publish 2 different podspecs in trunk.
