### ISSUE TITLE
[iOS][Beta 9] SDK crash when getting remoteParticipant.identifier on the event onRemoteParticipantsUpdated

### ISSUE THREAD

**Issue by AmyL219** [Azure/Communication#228]
**Describe the bug**
The CallingSDK crash on getting `remoteParticipant.identifier` on the event `onRemoteParticipantsUpdated`

**To Reproduce**
1. On the delegate method `onRemoteParticipantsUpdated`, execute the code `let identifier = args.addedParticipants[0].identifier`
2. Using CallingSDK join a group call with more than one participant
3. App would crash when user connected

**Expected behavior**
Should be able to get the remoteParticipant.identifier

**Screenshots**
![Screen Shot 2021-03-11 at 2 13 21 PM](https://user-images.githubusercontent.com/75647512/110896484-91fc0600-82b0-11eb-9516-63f0d322c0f3.png)

**Desktop (please complete the following information):**
 - Version beta 9

**Smartphone (please complete the following information):**
 - Device: iphone SE

**Logs**
[IdentifierCrash.xcappdata.zip](https://github.com/Azure/Communication/files/6127796/IdentifierCrash.xcappdata.zip)

**Comment by akania** [comment]
#227 related

**Comment by AmyL219** [comment]
ADO [ticket](https://skype.visualstudio.com/SPOOL/_workitems/edit/2398985)

**Comment by raosanat** [comment]
Issue is fixed now. Please run `pod cache clean --all` and `pod install` .
