### ISSUE TITLE
Remote participants have nil for their identifier property in 1.0.0-beta.9

### ISSUE THREAD

**Issue by tjprescott** [Azure/Communication#231]
@smartcat32 commented on [Thu Mar 11 2021](https://github.com/Azure/azure-sdk-for-ios/issues/762)

In beta 9 (of AzureCommunicationCalling, AzureCommunication, AzureCore) during a call when client is first called with CallDelegate's onRemoteParticipantsUpdated(), the remote participant(s) have the value nil for their identifier property.  According to the Objective C declaration of this property, it's supposed to always be non-nil.  Therefore I am getting a crash anytime I try to access a RemoteParticipant's identifier property in Swift.

![Screen Shot 2021-03-11 at 6 49 00 PM](https://user-images.githubusercontent.com/1614210/110885296-74707180-829b-11eb-9a54-bf0990c3a745.jpg)

I'm using Xcode 12.4.  My Podfile includes AzureCommunicationCalling, AzureCommunication, AzureCommunicationChat, and AzureCore - all at 1.0.0-beta.9 and cleanly installed.  I'm testing on iPhone 12 Pro iOS 14.4 simulator.

What's also interesting is I see that in the CHANGELOG.md of this beta 9 release, the following statement:
"Removal of label identifier in CommunicationUserIdentifier and UnknownIdentifier".   Now I understand this isn't the same property that I'm referring to above, but the above property would BE a CommunicationUserIdentifier in this case if it weren't a nil.  When I look at AzureCommunication's Identifiers.swift, CommunicationUserIdentifier class does still have an identifier: String property.  Separate issue or somehow related? 

As I require some way to have a String id of each user of the call (such as for Azure Chat), I don't see how to use beta 9.

**Comment by tompi** [comment]
Probably not a good solution, but as a workaround you could use beta 9 without upgrading the two other libs, Ive been using that today and it works fine as far as i can tell

**Comment by ProbablePrime** [comment]
@tjprescott Does the workaround provided work for you?
