### ISSUE TITLE
The video stream of remote participants from web client is not centred/cropped on android screen properly

### ISSUE THREAD

**Issue by lpx1989** [Azure/Communication#233]
**Describe the bug**
The video stream from remote participants on web client show up on the screen of android client side not centred properly.

**To Reproduce**

1. Use calling web client to create a call and join few participants.
2. Copy and paste the group call Id from web client to the Android calling sample to join the call.
3. After joining the call from Android calling sample, we can notice that video stream of remote participants from web client are not centred properly.

**Expected behavior**
The video stream for any participants showing up on the screen should be centred.

**Screenshots**
![image](https://user-images.githubusercontent.com/1281563/111083419-c0edc400-84ca-11eb-87bc-54ec0ac2c653.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 4a
 - OS: Android 11
 - Version beta8 calling sdk for android

**Additional Context**
Link to the ADO ticket https://skype.visualstudio.com/SPOOL/_workitems/edit/2394915

**Comment by akania** [comment]
Thank you for reporting @lpx1989 
Can you confirm that this is also the case when you'll use different scaling mode when creating view ( renderer.createView takes options ) https://docs.microsoft.com/en-us/javascript/api/azure-communication-services/@azure/communication-calling/scalingmode?view=azure-communication-services-js
Try using 'Fit'

**Comment by lpx1989** [comment]
@akania I tried with "FIT" when rendering local video stream from web client side, but the video stream showing on mobile screen was still not centred properly. I have already had re-pro session with @kagbakpem

**Comment by chriswhilar** [comment]
On the android device, is that the teams app?

**Comment by mariusu-msft** [comment]
Closing. This should be fixed in the latest release of the SDK
