### ISSUE TITLE
Speaking Change Listeners were triggered unexpectedly

### ISSUE THREAD

**Issue by lpx1989** [Azure/Communication#234]
**Describe the bug**
The speaking change event was triggered not properly. When turning on mic for one of remote participants from web clients, the speaking change event was triggered for multiple remote participants which messed up the participants' view update on Android device screen.

**To Reproduce**

When testing for the Android Calling Sample regarding of the participants view update when off-screen participant's speaking change listener was triggered. I have 4 remote participants joined from web client and one local participant. At the beginning, user 01 02 03 and local user showed up on the screen while user 04 was off screen.
Then I started my testing steps:
turn on mic for user 04, the expected result : 04 01 02 & local user on screen, 03 was off screen.
turn on mic for user 03, ............................result: 03 04 01 & local user on screen, 02 was off screen.
........................................ 02, ............................result: 02 03 04 & local user on screen, 01 was off screen.
continue this process......

**Expected behavior**
When speaking event is triggering for a certain remote participant, it should not trigger events for others' whose mic is off.

**Smartphone (please complete the following information):**
 - Device: Pixel 4a
 - OS: Android 11
 - Version This problem was noticed in beta6 & 7 calling sdk for android and continue show up in beta8 (but for beta8 it only happens for the first time triggering in the call)

**Additional context**
The link to the ADO ticket https://skype.visualstudio.com/SPOOL/_workitems/edit/2361930

**Comment by raosanat** [comment]
@kagbakpem this is now resolved right ?

**Comment by kagbakpem** [comment]
Yes, this is now resolved. Please make sure to also check the `isSpeaking` property on the `RemoteParticipant` to render the speaking status. ty
