### ISSUE TITLE
Unable to join to meeting in Beta 9

### ISSUE THREAD

**Issue by devgokhan** [Azure/Communication#237]
Hi.

I updated ACS from beta 7 to beta 9. Now I am not be able to join any meeting. 
After I call join then returned call object always null. Sometimes it is not null. In not null case, onStateCalled delegate never calls and never joins the meeting..
Same code is working in beta 7 correctly.. I am able to join to the meeting in Beta 7
Why it happens I could not understand.. Any ideas?

Note: To join a meeting I am using join method..

```
// uuid: CF500100-B6B4-49B6-10DC-1006E3EB80FC
let groupCallContext = GroupCallLocator(groupId: uuid)
let options = JoinCallOptions()
let audioOptions = AudioOptions()
audioOptions?.muted = !(self.microponeOn)
options?.audioOptions = audioOptions
self.call = self.callAgent?.join(with: groupCallContext, joinCallOptions: options)
if let call = self.call {
   call.delegate = self
   if call.state == .connected {
      self.hideLoading()
      self.connectedContinue()
   }
} else {
    self.hideLoading()
    self.showAlertPopup(type: .error, text: self.loc.Error.unableToJoin)
}
```

onStateChanged seems renamed in Beta 9. However Xcode forces us to add @nonobj tag to the method. This method delegation never calls..??

```
@nonobjc func onStateChanged(_ call: Call!, args: PropertyChangedEventArgs!) {
        switch call.state {
 
        case .none:
            break
        case .earlyMedia:
            break
        case .connecting:
            break
        case .ringing:
            break
        case .connected:
            self.hideLoading()
            self.connectedContinue()
            break
        case .localHold:
            break
        case .remoteHold:
            break
        case .disconnecting:
            break
        case .disconnected:
            self.connected = false
            self.timer?.invalidate()
            self.timer = nil
            self.close()
            break
        case .inLobby:
            break
        @unknown default:
            break
        }
        
    }
```

**Comment by raosanat** [comment]
Hi, We are not able to reproduce the issue. `@nonobjc` if added you wont get the event raised , I verified this behavior with our internal testapp. I am not sure why you are being forced to add `@nonobjc`. Which XCode version are you using ?

**Comment by devgokhan** [comment]
I don't know but it is never working..
Sometimes this kind of logs coming when joining: [aurioc] AURemoteIO.h:323:entry: Unable to join I/O thread to workgroup ((null)): 2
Last release is not working stable. I also tried with iOS 13.
My Xcode version is 12.4

My project is full swift project. Did you tried with full swift project? If you use objective c demo or some codes even swift, problems sometimes still happens. I experienced this one of other framework before. Please try with full swift demo projects, somethings working differently sometimes.

**Comment by mkambale** [comment]
@raosanat Hi..
We do have issue with Beta 9 SDK for iOS.
When we write custom mobile app with Swift 5.2 , we do see issue with the delegates of protocol - CallDelegate and RemoteParticipantDelegate.

Do we need to make any Build changes for this go away?

<img width="843" alt="Screen Shot 2021-04-01 at 9 12 46 PM" src="https://user-images.githubusercontent.com/28888982/113319417-03b6f500-932f-11eb-8e6e-93fa8458b179.png">

**Comment by raosanat** [comment]
Do you have different delegates implemented by the same class? Can you separate them into different observer classes and give it a try? 

In the upcoming version we have renamed the delegates to follow the Swift guidelines.

**Comment by raosanat** [comment]
Please try with GA `1.0.0` or `1.0.0-beta.12` we have renamed the delegates to be Swift friendly and unique method signatures. Please re-open if you still see issues.

**Comment by rashidbpg** [comment]
@raosanat unfortunately, we are having issues with publishing to TestFlight with the latest SDK. We are getting errors similar to https://github.com/Azure/Communication/issues/113 even though the comments in the thread says that the latest has a fix. We are looking into it more but if you have any suggestions, please let me know.

**Comment by devgokhan** [comment]
Still happening in 1.0.0 release.. In demo it is works.. : https://github.com/Azure-Samples/communication-services-ios-calling-hero
(In demo I also update to 1.0.0 and tried it)
However in my project it never works.

<img width="738" alt="Screen Shot 2021-04-29 at 10 11 32" src="https://user-images.githubusercontent.com/8233432/116522921-5d82ee80-a8de-11eb-8ef9-f2cbf46c361f.png">

I also tried with inside NSObject class. It is same. 
<img width="416" alt="Screen Shot 2021-04-29 at 11 31 50" src="https://user-images.githubusercontent.com/8233432/116523085-83a88e80-a8de-11eb-9638-8b396b06c3bb.png">
<img width="704" alt="Screen Shot 2021-04-29 at 11 31 39" src="https://user-images.githubusercontent.com/8233432/116523088-84d9bb80-a8de-11eb-9bc7-bd52450206ae.png">

I don't know why it is happening. Any ideas? And is there anybody like me still having this issue??

**Comment by mkambale** [comment]
@raosanat How do I access the available speakers for the selection? Docs says Devicemanger.speakers and Devicemanager.getspekaers(). But, its seems none of the available in beta.11 version. Any help will be appreciated.
