### ISSUE TITLE
In call progress indicator?

### ISSUE THREAD

**Issue by rashidbpg** [Azure/Communication#239]
**Is your feature request related to a problem? Please describe.**
We have an app which leverages group calls and chat that we would like to show a in-call indicator when the user is joined to the group call. Currently, the app will stop recording and playing back voice on iOS immediately and will eventually stop playback on Android. Maybe we could leverage another solution for the progress indicator but would be great if the SDK supports it.

**Describe the solution you'd like**
Would expect that the API will set the in call progress indicator while joined to a group call. Playback and voice call should continue while in sleep or screen is off.

**Describe alternatives you've considered**
Possible leverage another package for call indicator

**Additional context**
N/A

**Comment by RinaRish** [comment]
Hi @rashidbpg! Thanks for your feedback. One way of doing this is implementing the indicator by using the CallState
` public enum CallState

    {

        /// <summary>

        /// None - disposed or applicable very early in lifetime of a call

        /// </summary>

        None = 0,

        /// <summary>

        /// Early Media

        /// </summary>

        EarlyMedia = 1,

        /// <summary>

        /// Currently unused, used to be Incoming

        /// </summary>

        //Reserved = 2,

        /// <summary>

        /// Call is being connected

        /// </summary>

        Connecting = 3,

        /// <summary>

        /// Call is ringing

        /// </summary>

        Ringing = 4,

        /// <summary>

        /// Call is connected

        /// </summary>

        Connected = 5,

        /// <summary>

        /// Call held by local participant

        /// </summary>

        LocalHold = 6,

        /// <summary>

        /// Call is being disconnected

        /// </summary>

        Disconnecting = 7,

        /// <summary>

        /// Call is disconnected

        /// </summary>

        Disconnected = 8,

        /// <summary>

        /// In Lobby

        /// </summary>

        InLobby = 9,

        /// <summary>

        /// Call held by a remote participant

        /// </summary>

        RemoteHold = 10

    }`
Let me know if that helps.
