### ISSUE TITLE
Azure Communication Services Chat SDK for Javascript - sending html message type

### ISSUE THREAD

**Issue by jhl0214** [Azure/Communication#245]
When I try to send a html message type, such as `<img src="src_url" alt="alt">`, the src attribute is gone when I load the message. Is that supposed to happen or is that a bug? Or am I missing something? I couldn't find any example/tutorial regarding sending a message of html type. Any help would be great! Thank you.

**Comment by leijae** [comment]
untested... but have you tried replacing the " with single ' ?

**Comment by juancamilor** [comment]
Thanks for the question @jhl0214 
When the content type is set to 'html', there are sanitization functions on the service side that removed not allowed tags, including the src. You can just use 'Text' as the content type and the message will by carried unmodified end to end.
Let me know if you need further details.

FYI @ashwinder
