### ISSUE TITLE
Call incoming although CallAgent is disposed

### ISSUE THREAD

**Issue by bbonkr** [Azure/Communication#246]
**Describe the bug**
Call incoming although CallAgent is disposed

**To Reproduce**
1. callAgent dispose
2. Call to client that callAgent has been disposed
3. The client that callAgent has been disposed has incoming call

**Expected behavior**

If callAgent is diposed, should not have incoming call.

**Screenshots**

N/A

**Desktop (please complete the following information):**
 - OS: Windows 10 Version 10.0.19042 Build 19042
 - Browser: Microsoft Edge
 - Version 89.0.774.68 (Official build) (64-bit)

```powershell
PS> node -v
v14.15.1
```

```powershell
PS> nvm -v
7.6.3
```

dependent packages:
- @azure/communication-calling: 1.0.0
- @azure/communication-common: 1.0.0
- react: 16.13.0
- react-dom: 16.13.0
- next: 10.0.3

**Smartphone (please complete the following information):**

**Additional context**

It was not case with @azure/communication-calling 1.0.0-beta.6

**Logs**
<br/>Please attach the logs or share the callId. Instructions could be found [here](https://docs.microsoft.com/en-us/azure/communication-services/concepts/troubleshooting-info?tabs=csharp%2Cjavascript%2Cdotnet)

**Comment by akania** [comment]
Thank you for reporting @bbonkr , we'll validate it - tracking item [ADO#2415155](https://skype.visualstudio.com/SPOOL/_workitems/edit/2415155)

**Comment by bbonkr** [comment]
I could not access ADO#2415155

Please take a care of it.

**Comment by chriswhilar** [comment]
Hi @bbonkr, did the incoming call happen after the dipose method fully reosolved?

**Comment by bbonkr** [comment]
> Hi @bbonkr, did the incoming call happen after the dipose method fully reosolved?

Yes, It did.

I had been disposed callAgent like below code. and had no error when call dispose function.

```typescript
let callAgent: CallAgent;

const disposeCallAgent = async (): Promise<void> => {
    await callAgent.dispose();

    callAgent = null;
}

await disposeCallAgent();
```

I confirmed callAgent is null after dispose function called.

Then after call to diposed callAgent, there is call incoming.

**Comment by chriswhilar** [comment]
Mmm this is odd. Im not able to repro this.

**Comment by bbonkr** [comment]
@chriswhilar 

If it happens only to me and could not be able to repro it,  might mean to be wrong in my code.

Let me check my codes.

I would like to request a some references for dispose CallAgent.

There is no explain to callAgent dispose in [npm @azure/communication-calling](https://www.npmjs.com/package/@azure/communication-calling)  page.

**Comment by chriswhilar** [comment]
I will try to keep reproing

can you please try it with a different device? Try to see if this happens when you dispose from chrome and then get the incoming call on chrome

**Comment by bbonkr** [comment]
@chriswhilar 

I'll try on chrome then report here.

Thank you for support.

**Comment by bbonkr** [comment]
@chriswhilar 

I had been tried on Chrome, there is same issue.

Chrome 
Version: 89.0.4389.114 (64bit)

If make a call least once, the call comes after CallAgent disposed.

If did not receive a call, the call does not come after CallAgent disposed.

**Comment by chriswhilar** [comment]
Sorry in my last comment i actually meant that you dont have to do it from a group call, just make the chrome user receive the incoming call however you want (either from group call or 1:1 call). Just dont do a 1:1 call where the caller is ios, so we can see if its happening only when chrome is used in both caller and callee sides. 

Do you have your app code somewhere i can clone it and try it out?

Also, can you please try and repro with this tutorial app here: https://github.com/Azure-Samples/communication-services-web-calling-tutorial
clone that tutorial app. In package.json change @azure/communication/calling version to 1.0.0 (make sure when runin npm install that version 1.0.0 actually gets installed into your node_modules)
To dispose of the callAgent whenever you want, just do window.callAgent.dispose() from devtools console. You can also modify the code a bit to dispose using code.
I have tried this with the tutorial sample app and have not ran into the issue, so id like to see if you run into the same issue using this tutorial app.

**Comment by RinaRish** [comment]
This issue was closed due to no repro, please feel free to reopen if it persists.
