### ISSUE TITLE
I upgraded my ACS lib to beta.9 and i have some issues.

### ISSUE THREAD

**Issue by ozanurkn** [Azure/Communication#248]
**Describe the bug**
I upgraded ACS to beta.9 and i couldn't get remoteParticipant, actually like this;

i have two device for testing. First of all i entered with first device in meeting and for example one min later i entered with second device. First device gets all remoteParticipant(second device infos like displayName) but my second device couldn't get remoteParticipant(first device infos like displayName).

i am using this code about that.

 `call.addOnRemoteParticipantsUpdatedListener(p -> onParticipantUpdated(call.getRemoteParticipants()));`

But onParticipantUpdated method doesn't call my first device.

Thanks.
Ozan

**Comment by kagbakpem** [comment]
Can you also update to beta.10 and let us know if the issue persists? Thanks

**Comment by ozanurkn** [comment]
@kagbakpem hi,

Actually i am trying to do one to one meeting , not possible more than two person being in a call. İ am using GroupCallLocator like this.

` private void joinGroupMeeting() {
        joinButtonState(true);
        Log.i("DEBUG:", "joinGroupMeeting Method runnnig");

        GroupCallLocator groupCallContext = new GroupCallLocator(UUID.fromString(groupId));
        JoinCallOptions joinCallOptions = new JoinCallOptions();
        call = agent.join(this, groupCallContext, joinCallOptions);
        call.addOnStateChangedListener(p -> callStateChanged(call.getState()));
    }`

**Comment by ozanurkn** [comment]
hi, i updated sdk to 1.0.0 but still like this.

**Comment by kagbakpem** [comment]
@ozanurkn, can you share a full snippet of code where you're trying to do this? From what we see, this should be working, so the issue might be in a different layer. Sharing a snippet or the logs from the device would help debug this. ty

**Comment by ozanurkn** [comment]
Sure,

```
private void joinGroupMeeting() {
        GroupCallLocator groupCallContext = new GroupCallLocator(UUID.fromString(groupId));
        JoinCallOptions joinCallOptions = new JoinCallOptions();
        call = agent.join(this, groupCallContext, joinCallOptions);
        call.addOnStateChangedListener(this::onCallStateChanged);
    }
```

onCallStateChanged() method working and when my call state is CONNECTED;

I am calling method for setting ui.

`call.addOnRemoteParticipantsUpdatedListener(this::onParticipantsUpdated);`

if remoteParticipants count 0 or null , below code is working for update ui.
```
if (call.getRemoteParticipants().size() == 0) { 
            currentMeetingUILogic("setCurrentVideoScreenUI");
}
```

```
private void currentMeetingUILogic(String tag) {
        Log.i("DEBUG:", "currentMeetingUILogic Method runnnig " + tag);
        if (mRemoteParticipant != null) {
            if (mRemoteParticipant.isMuted()) {
                getBinding().imgCurrentIsmuted.setVisibility(View.VISIBLE);
            } else {
                getBinding().imgCurrentIsmuted.setVisibility(View.GONE);
            }
            if (mRemoteParticipant.getVideoStreams().size() != 0) {
                Log.i("DEBUG:", "There is camera open.");
                remoteRendererDispose();
                getRemoteCamera();
                getBinding().clCurrentMeetingUnvideo.setVisibility(View.GONE);
                getBinding().clCurrentMeetingNoone.setVisibility(View.GONE);
                getBinding().clCurrentMeetingContainer.setVisibility(View.VISIBLE);
                getBinding().txtCurrentNameSurnameLong.setVisibility(View.VISIBLE);
                getBinding().txtCurrentNameSurnameLong.setText(mRemoteParticipant.getDisplayName());
            } else {
                Log.i("DEBUG:", "there is camera closed. ");
                remoteRendererDispose();
                getBinding().clCurrentMeetingNoone.setVisibility(View.GONE);
                getBinding().clCurrentMeetingContainer.setVisibility(View.GONE);
                getBinding().clCurrentMeetingUnvideo.setVisibility(View.VISIBLE);
                getBinding().txtCurrentNameSurnameLong.setVisibility(View.VISIBLE);
                getBinding().txtCurrentNameSurnameLong.setText(mRemoteParticipant.getDisplayName());
                getBinding().txtCurrentNameSurnameShort.setText(convertNameFullToShort(mRemoteParticipant.getDisplayName()));
            }
        } else {
            Log.i("DEBUG:", "there is no one");
            remoteRendererDispose();
            getBinding().clCurrentMeetingUnvideo.setVisibility(View.GONE);
            getBinding().clCurrentMeetingContainer.setVisibility(View.GONE);
            getBinding().clCurrentMeetingNoone.setVisibility(View.VISIBLE);
            getBinding().imgCurrentIsmuted.setVisibility(View.GONE);
            getBinding().txtCurrentNameSurnameLong.setVisibility(View.GONE);
        }
    }
```

But onParticipantsUpdated() method not calling when i did above scenario.


```
private void onParticipantsUpdated(ParticipantsUpdatedEvent args) {
        List<RemoteParticipant> remoteParticipants = args.getAddedParticipants();
        .....
        .....

}
```

thanks.
Ozan

**Comment by kagbakpem** [comment]
@ozanurkn, we noticed there is a potential issue with the SDK when used with App targeting SDK Version 30. As a temporary fix, while we sort this out on our end, can you make sure to target SDK version 29 for now. To do so, in your module level `build.gradle`, make sure `targetSdkVersion` is set to 29 and let us know how that goes. Thank you.

**Comment by ozanurkn** [comment]
I am already using target sdk 29.

**Comment by kagbakpem** [comment]
which devices are you using for the testing?

**Comment by ozanurkn** [comment]
Samsung Galaxy A50
Android OS Version = 10

Samsung Galaxy S8
Android OS Version = 9

**Comment by kagbakpem** [comment]
How are you attempting to end the call? Which API are you using?

**Comment by ozanurkn** [comment]
its a little complicated. I'll tell you right now.

this code my close realtime comminucation's method end button.
```
 @Override
    public void onClickedCurrentCloseAll() {
        //stopCall();
        willCloseCommunication = true;
        intent(MainActivity.class);
        finish();
    }
```

so i killing activity with finish and running onDestroy() method.

```
@Override
    protected void onDestroy() {
        Log.i("DEBUG:", "onDestroy method running.");
        super.onDestroy();
        clickLaggerDispose();
        stopCall();
    }
```

```
private void stopCall() {
        Log.i("DEBUG:", "stopCall method running.");
        if (call != null) {
            try {
                durationMeeting(false);
                localRendererDispose();
                remoteRendererDispose();
                call.stopVideo(this, currentVideoStream).get();
            } catch (ExecutionException | InterruptedException e) {
                e.printStackTrace();
            }
            call.hangUp(new HangUpOptions());
        }
    }
```
but it doesn't always give an error. 

I noticed something else. When i switch camera , the image is going off on the other device.

```
@Override
    public void onClickedSwitchCamera() {
        if (deviceManager.getCameras().size() >= 2) {
            if (desiredCamera.getId().equals(deviceManager.getCameras().get(0).getId())) {
                desiredCamera = deviceManager.getCameras().get(1);
            } else {
                desiredCamera = deviceManager.getCameras().get(0);
            }
            try {
                if (getBinding().clPreMeetingScreen.getVisibility() == View.VISIBLE) {
                    previewVideoStream.switchSource(desiredCamera).get();
                } else if (getBinding().clCurrentMeetingScreen.getVisibility() == View.VISIBLE) {
                    currentVideoStream.switchSource(desiredCamera).get();
                }
            } catch (ExecutionException | InterruptedException e) {
                e.printStackTrace();
            }
        } else {
            showDialog(ErrorDialogFragment.newInstance(getString(R.string.avs_not_yet_camera_count), getString(R.string.sm_error_dialog_button_text), true, DialogButtonActionType.JustDismiss.getValue()));
        }
    }
```

thats my switch camera code.

thanks.

**Comment by kagbakpem** [comment]
Can you make sure you await the result of the `hangup(..)` CompletableFuture using `call.hangUp(new HangUpOptions()).get();` and let us know whether this works better?

**Comment by ozanurkn** [comment]
actually i am not sure what's different.

**Comment by kagbakpem** [comment]
@ozanurkn, this should be fixed on the latest version. Please give it a try and let us know if the issue persists.
