### ISSUE TITLE
Provide LocalVideoStream for Logical device

### ISSUE THREAD

**Issue by vbsteven** [Azure/Communication#251]
**Is your feature request related to a problem? Please describe.**
I have a wearable device connected to an Android phone and I'm looking for a way to use that device as a video camera source to make video calls using the ACS Android SDK (calling SDK currently in preview). From my Android app I have full access to the wearable device so I have access to the raw video data.

**Describe the solution you'd like**
I'm looking for a way to create a `LocalVideoStream` that calls my own code to provide the video stream data. Similar to how the Azure Media Calling Bot SDK allows Bots to provide their own video streams (either as encoded H264 or raw frame data)

**Describe alternatives you've considered**
I've looked at the Android Calling Hero sample, which only allows LocalVideoStream objects to be created by using `deviceManager.getCameras()` followed by `new LocalVideoStream(camera, androidContext)`. This means I can only use the original phone cameras (front & back) because those are the only ones coming back from `getCameras()`. 

I've noticed an enum called VideoDeviceType in the calling SDK:
```
public enum VideoDeviceType {
    UNKNOWN,
    USB_CAMERA,
    CAPTURE_ADAPTER,
    VIRTUAL;

    private VideoDeviceType() {
    }
}
```

The native phone cameras that come back from `deviceManager.getCameras()` all seem to have `USB_CAMERA` as device type. The `CAPTURE_ADAPTER` and `VIRTUAL` device types seem interesting for my purposes. Is there a way I can instantiate/register a Video Device with one of those and use that as my LocalVideoStream?

**Comment by mariusu-msft** [comment]
Thanks for the feedback @vbsteven. 

We're actively investigating similar asks for Android. We will keep this open and provide an update in a couple of weeks.

@sankum-msft once we have something in Public Preview or API design, let's validate it with @vbsteven's scenario too.

Regarding the device types, that's sometime we will be removing soon. We don't have implementations for those types yet, as such should be removed.

**Comment by tompi** [comment]
A solution for this would probably also solve #249 
(Since you could just use local camera for whatever you need and then create a new one for use by ACS and forward data to that)

**Comment by sankum-msft** [comment]
This feature is still under development

**Comment by RinaRish** [comment]
[Ticket](https://skype.visualstudio.com/SPOOL/_workitems/edit/2424744)
