### ISSUE TITLE
Server side Audio/video session recording

### ISSUE THREAD

**Issue by rahatur** [Azure/Communication#254]
**Is your feature request related to a problem? Please describe.**
For audit purposes recorded audios/videos are necessary for many systems. A server side recorded session can serve the purpose.

**Describe the solution you'd like**
If we can have a support at the API level that can trigger a ongoing session would be nice. The stored session can reside on the Azure. Single session can be recorded for each room.

**Describe alternatives you've considered**
A bot can join and record the sessions on local storage.

**Comment by carlchan1994** [comment]
We need the video recording feature too. It is one of the major requirements from my customer.

**Comment by RinaRish** [comment]
Hi @rahatur & @carlchan1994! Thanks for your feedback? Can you provide more details on your requirements? For example:
1) do you need audio-only recordings or both audio+video?
2) which format of recording?
3) do you need it mixed or unmixed? how many channels?
4) what is the storage requirement
5) scenarios

Thanks!

**Comment by rahatur** [comment]
Hi @RinaRish Following are my suggestions:
> 1. do you need audio-only recordings or both audio+video?
Options for audio only and audio+video would be better as the service supports both.
> 2. which format of recording?
To keep the file size smaller mp4 would be better
> 3. do you need it mixed or unmixed? how many channels?
Both would be better but if we have to choose one we would choose the mixed option
> 4. what is the storage requirement
To start with we can use the azure file storage. Option to have FTP storage would be nice.
> 5. scenarios
Applications like telemedicine - where patient talks to a hospital staff and then the hospital staff brings a doctor on the call for special advice.
As long as there are more than one participant in a room a recording can go on and stored on a preconfigured storage location.

Thanks.

**Comment by DominikMe** [comment]
@rahatur Call recording is now available as part of the CallAutomation SDK, you can find more documentation here: https://learn.microsoft.com/en-us/azure/communication-services/concepts/voice-video-calling/call-recording
