### ISSUE TITLE
Please include in the document the browser & OS versions support list

### ISSUE THREAD

**Issue by hoangph271** [Azure/Communication#257]
About the Call SDK & Chat SDK
I can't find in the document a list of supported browsers & OS versions

Please include in the document the browser & OS versions support list in the document

**Comment by LaithRodan** [comment]
https://docs.microsoft.com/en-us/azure/communication-services/concepts/voice-video-calling/calling-sdk-features#javascript-calling-sdk-support-by-os-and-browser

**Comment by hoangph271** [comment]
Thank

> https://docs.microsoft.com/en-us/azure/communication-services/concepts/voice-video-calling/calling-sdk-features#javascript-calling-sdk-support-by-os-and-browser

Thank you for your help, but as I see there're Native SDK as well, the support list is not included...!
And the JS SDK doesn't specify the browser version as well...?

**Comment by LaithRodan** [comment]
We support the latest three releases of the browser versions, unless mentioned otherwise in the limitations.

**Comment by ProbablePrime** [comment]
I am submitting an edit to the documentation to resolve this today. I will update you when it has been done.

**Comment by ProbablePrime** [comment]
This page has been updated to clarify Laith's prior information. I also cleaned up the browser support table to be a little clearer. Thank you for your feedback!

**Comment by hoangph271** [comment]
> Thank
> 
> > https://docs.microsoft.com/en-us/azure/communication-services/concepts/voice-video-calling/calling-sdk-features#javascript-calling-sdk-support-by-os-and-browser
> 
> Thank you for your help, but as I see there're Native SDK as well, the support list is not included...!
> And the JS SDK doesn't specify the browser version as well...?

Thank for your work, guys...!
Is there any update on the Native SDK support list...?
I didn't see these changes...?
