### ISSUE TITLE
CallState is switching to NONE after few seconds on Android

### ISSUE THREAD

**Issue by paulmarcsqr** [Azure/Communication#258]
Hi, i encounter the following issue with my home Wifi and android SDK: If both devices are connected to same wifi calls are working fine, if i changed one of my devices to 4G or i try to call one of my colleagues, after call is CONNECTED, we can't hear each other and the state is switching to NONE after 5-7 seconds. I mention i can receive calls on the wifi on which i see this problem, the bug only happens when i am the caller.  

Another scenario i tried is calling from iOS app while the iOS device is on the same wifi first then from 4G, both cases are working fine, the bug is reproducing when i try to call from my android device and iOS one is on 4G, having it in the same wifi network it seems to solve the issue.
The devices are Samsung A21s, android 10. We tested with beta 8 and 10 and we got the same results.

**Comment by LoadLibrary** [comment]
Hi Paul,

Can you attach logs reproing the issue to this bug?
You'll find the instructions for sourcing the logs at: https://docs.microsoft.com/en-us/azure/communication-services/concepts/troubleshooting-info?tabs=csharp%2Candroid%2Cdotnet

**Comment by paulmarcsqr** [comment]
Can you provide us an email address for sending the logs? Thank you!

**Comment by raosanat** [comment]
Please attach blogs with `msrtc` in the name of the blog.

**Comment by mariusu-msft** [comment]
Hi @paulmarcsqr,

This should be fixed now in latest BETA releases for iOS and Android.

Thanks for your report.
-Marius
