### ISSUE TITLE
iOS SDK: Joining a group call always unmutes microphone

### ISSUE THREAD

**Issue by ryanespiritu** [Azure/Communication#26]
**Describe the bug**
Joining a group call always unmutes microphone.

**To Reproduce**
1. Set `ASCAudioOptions`'s `muted` property to `YES`
2. Join a call via a groupID
3. Observe microphone is not muted

**Expected behavior**
My microphone should be muted after specifying `muted = YES` for the audio options.

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: iOS 13.2.3

**Code Snippet**
```
ACSAudioOptions *audioOptions = [[ACSAudioOptions alloc] init];
audioOptions.muted = YES;

ACSJoinCallOptions *joinCallOptions = [[ACSJoinCallOptions alloc] init];
joinCallOptions.audioOptions = audioOptions;

ACSGroupCallContext *groupCallContext = ...;

self.call = [self.callAgent joinWithGroupCallContext:groupCallContext joinCallOptions:joinCallOptions];
...
```

**Comment by raosanat** [comment]
Hi , Thanks for reporting the issue. This is a bug at our end and we will fix this in the upcoming release.

**Comment by raosanat** [comment]
@terrychen1122  We have made a release which fixes this issue. Here is the link to the release  [AzureCommunicationCalling - v1.0.0-beta.4](https://github.com/Azure/Communication/releases/tag/v1.0.0-beta.4)
Please verify if the bug is fixed in this new release. Thanks.

**Comment by mariusu-msft** [comment]
Closing issue. This should be fixed now. 

Thanks for the report.
