### ISSUE TITLE
[Communication] PhoneNumbers SDK - Order has failed

### ISSUE THREAD

**Issue by leijae** [Azure/Communication#265]
VS 2019
.Net Core 3.1
PhoneNumbers SDK v1.0.0-beta6

Failed to purchase phone number(s)
![image](https://user-images.githubusercontent.com/50371033/115921883-bddae180-a441-11eb-8d83-a4d5160af668.png)

Fails on Line 46  where the first breakpoint is
![image](https://user-images.githubusercontent.com/50371033/115921992-e7940880-a441-11eb-9122-70f157abeead.png)

**Comment by leijae** [comment]
Updated to version 1.0.0 g.a. and still getting the same error...

**Comment by leijae** [comment]
Here is a perfect case of: Release an SDK that is literally disabled... 👏 
![image](https://user-images.githubusercontent.com/50371033/116298822-8c745580-a762-11eb-86a1-03b423796019.png)

**Comment by manoskow** [comment]
Hi @leijae , We have re-enabled the purchase of toll-free numbers through the SDK and the portal. We are sorry for the disruption, but thank you for bearing with us as we work through these issues and build out a better process. Unfortunately the temporary pause was necessary in this case to prevent further misuse :( 

I understand this process isn't perfect and the team is working hard to figure out a solution where we can balance security and ease-of-use for all of our customers. Until then we still do have a limit of 1 phone number per customer to reduce the abuse of these APIs. If you need more phone numbers you can follow the instructions [here](https://github.com/Azure/Communication/blob/master/special-order-numbers.md) (as noted in the image) and order more numbers. 

If you have more ideas or feedback in these areas we would love to hear from you either through this forum or through our [feedback forum](https://feedback.azure.com/forums/934536-azure-communication-services).

I'm hoping you are unblocked now, but let us know if there are any other issues that come up. Thank you for working with us as we figure this out!

**Comment by leijae** [comment]
Well my use-case required multiple phone numbers as each of my clients require their own phone numbers for text-confirmation. As in: Please text "yes" to confirm your appointment at 2:30pm

@manoskow The frustrating thing wasn't that you shut it down... I get you have to keep your business and your clients safe. What's frustrating is the lack of communication about what's going on.

**Comment by manoskow** [comment]
I hear you and that is a really important learning for us. We absolutely can communicate this better in the future and try multiple channels (not just relying on the support teams to communicate for us).

We are building out our integration with Azure Service and Resource Health to help with this type of thing so customers can subscribe to events/notifications when things like this happen. 

Thanks again for your feedback and patience!
