### ISSUE TITLE
Possible to retrieve the Audio Stream for Spatial effects on JS?

### ISSUE THREAD

**Issue by eliaspuurunen** [Azure/Communication#27]
In WebRTC applications, it is possible to re-route a MediaStream through effects.

Are there any entrypoints known for the JS Azure Communication SDK?

**Comment by anthonysva** [comment]
@eliaspuurunen - can you elaborate on the desired functionality? E.g. capture unmixed audio

**Comment by eliaspuurunen** [comment]
@anthonysva - on one of our WebRTC projects, we take the audio track from a MediaStream, then apply filters to it. 

https://developer.mozilla.org/en-US/docs/Web/API/PannerNode

Does the JS library allow a developer to access the underlying MediaStream tracks?

**Comment by RinaRish** [comment]
Hi Elias! it's currently not supported, but I'll discuss with the engineering team

**Comment by eliaspuurunen** [comment]
Hi @RinaRish - to work with our WebRTC requirements, we found a workaround for displaying the local preview of a shared screen. See issue #67. It appears it is possible to go the undocumented route and grab MediaStreams, but for obvious reasons this is probably a bad/unsupported idea.

**Comment by RinaRish** [comment]
Hi @eliaspuurunen! Thanks for the feedback. I will encourage you to wait until there is a proper implementation of it. I'm going to close this issue and track it under #67. Feel free to reopen if you have more questions.

**Comment by eliaspuurunen** [comment]
Sounds great. Thank you @RinaRish!
