### ISSUE TITLE
[iOS] Adding error to `rendererFailedToStart` method

### ISSUE THREAD

**Issue by terrychen1122** [Azure/Communication#270]
Sometimes, we have seen our logs showing `rendererFailedToStart` method in `ACSRendererDelegate` was called causing the users didn't see the stream properly. There is literally nothing we can do at this point since no info is provided. And we didn't know if it's on us or on acs or intermittent failure.

Asks: could you provide an error (Error) such that we can log the description of it to understand what went wrong?

version: beta9

**Comment by mariusu-msft** [comment]
At that point you should restart your state machine that renders the current participant state.

For example it could be a race condition, remote participant stopping video at the exact same time when you are trying to render the video stream.

We'll keep this open to see if we can provide any additional information about why rendering failed.

**Comment by terrychen1122** [comment]
@mariusu-msft , do you mean that I should discard this renderer and attempt to redo the rendering again?

**Comment by terrychen1122** [comment]
It sounds like feasible mitigation. To prevent a loop, we will need to set the max # of repeating this process.

**Comment by mariusu-msft** [comment]
@terrychen1122 yes. But also check if the stream is available anymore - it can definitely happen as part of the race condition I just described.

**Comment by terrychen1122** [comment]
A colleague just reproduced this by quickly turning on and off the camera in the preview (the user has joined the call). For context, when turning on the camera, we create the renderer from the local stream and attach the renderer view to the screen. When turning off, we dispose that renderer and remove the renderer view from the screen. 

For this case, I am not sure the mitigation would help since when turning on and off, it's basically recreating the renderer.

**Comment by mariusu-msft** [comment]
You are correct, the mitigation I mentioned above is suitable only for remotevideostreams.

**Comment by terrychen1122** [comment]
For local video stream, any insights why it happens for this case?

**Comment by sankum-msft** [comment]
That would happen if you did not dispose any previous renderer attached to the local video stream.

**Comment by RinaRish** [comment]
@terrychen1122 sorry for the very late response but do you have any other questions? or we can close this?

**Comment by mariusu-msft** [comment]
Closing. @terrychen1122 please open up again if if you have any questions
