### ISSUE TITLE
[iOS] stateChanged not working still in 1.0.0 too 

### ISSUE THREAD

**Issue by devgokhan** [Azure/Communication#274]
Hi.. Problem still happens : https://github.com/Azure/Communication/issues/237

Swift Language : 5

Error : 
Objective-C method 'onStateChanged::' provided by method 'call(_:didChangeState:)' conflicts with optional requirement method 'remoteParticipant(_:didChangeState:)' in protocol 'RemoteParticipantDelegate'

Still happening in 1.0.0 release.. In demo it is works.. : https://github.com/Azure-Samples/communication-services-ios-calling-hero
(In demo I also update to 1.0.0 and tried it)
However in my project it never works.

Any ideas?
Any body faces this problem?

<img width="416" alt="Screen Shot 2021-04-29 at 11 31 50" src="https://user-images.githubusercontent.com/8233432/116523729-37aa1980-a8df-11eb-9400-7e2245ef6672.png">
<img width="704" alt="Screen Shot 2021-04-29 at 11 31 39" src="https://user-images.githubusercontent.com/8233432/116523738-38db4680-a8df-11eb-9e49-3033653fb752.png">
<img width="738" alt="Screen Shot 2021-04-29 at 10 11 32" src="https://user-images.githubusercontent.com/8233432/116523743-3a0c7380-a8df-11eb-8c51-19136f65703b.png">

**Comment by devgokhan** [comment]
I think any object in my class maybe effects it.. In my project if class is empty it works. 
I am suspecting with works swift only variables or things.. I am still inspecting the issue. It is strange.

**Comment by devgokhan** [comment]
I think somethings is wrong in SDK.
I solved the issue with writing the code in differend extension file.
In same file it gives the error that I shared it before.

<img width="612" alt="Screen Shot 2021-04-29 at 12 10 54" src="https://user-images.githubusercontent.com/8233432/116528070-0d0e8f80-a8e4-11eb-8b1c-088038ab3c4c.png">
<img width="375" alt="Screen Shot 2021-04-29 at 12 10 36" src="https://user-images.githubusercontent.com/8233432/116528074-0ed85300-a8e4-11eb-8f61-ff5c94f54ffc.png">

**Comment by devgokhan** [comment]
Definitely SDK has serious problems.  Yes I could resolved building issue with writing the delegate codes in different file.. I also debug in simulator and device. Everything was working correctly..

However, I am unable to archive right now. So I am unable to upload it to the App Store

Could you please release quick fix? Issue happens every time if build archive so you can it like this. Can anybody check?

<img width="243" alt="Screen Shot 2021-04-29 at 14 08 49" src="https://user-images.githubusercontent.com/8233432/116542048-ddb44e80-a8f4-11eb-99cd-21928e7313fe.png">

<img width="710" alt="Screen Shot 2021-04-29 at 14 09 03" src="https://user-images.githubusercontent.com/8233432/116542042-db51f480-a8f4-11eb-886f-b0b0f7d27c2c.png">

**Comment by raosanat** [comment]
@devgokhan Can you for now split the implementation into different classes each implementing a different Delegate ? That should resolve your problem for now.

**Comment by raosanat** [comment]
@devgokhan i am not sure i understand the problem. You are able to build the application but not able to archive it ? Maybe its something to do with usage of extensions ?

**Comment by devgokhan** [comment]
Yes I am able to build for debug however unable to archive it. Only two methods doing that other methods of delegations is working..

**Comment by raosanat** [comment]
We are able to build our internal test-app and successfully generate ipa file as well. In our application as well we have  both delegates, `RemoteParticipantDelegate` and `CallDelegate` , `didChangeState` implemented.

**Comment by mariusu-msft** [comment]
@devgokhan is this resolved now for you? Were you able to split the classes?

**Comment by RinaRish** [comment]
@devgokhan closing this issue since we did not hear back from you. Please feel free to reopen
