### ISSUE TITLE
[iOS] 1.0.0 -[ACSCall displayName]: unrecognized selector sent to instance 0x6000026ef600'

### ISSUE THREAD

**Issue by devgokhan** [Azure/Communication#275]
Hi getting the error bellow.

I found how it happens.. if display name is getting in didChangeMuteState, this is happens..
If displayName is null it needs to be "" I think. (if you forced with ! or as! -> do not)

```
func remoteParticipant(_ remoteParticipant: RemoteParticipant, didChangeMuteState args: PropertyChangedEventArgs) {
       // Utils.log("Meeting -> remoteParticipant() for participant: \(remoteParticipant.displayName) isMuted: \(remoteParticipant.isMuted)")

```

2021-04-29 12:27:27.519555+0300 App[16847:241600] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[ACSCall displayName]: unrecognized selector sent to instance 0x6000026ef600'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff20421af6 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff20177e78 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff204306f7 +[NSObject(NSObject) instanceMethodSignatureForSelector:] + 0
	3   CoreFoundation                      0x00007fff20426036 ___forwarding___ + 1489
	4   CoreFoundation                      0x00007fff20428068 _CF_forwarding_prep_0 + 120
	5   App                           0x00000001072fb7aa $s9App21MeetingCallingContextC17remoteParticipant_18didChangeMuteStateySo09ACSRemoteF0C_So27ACSPropertyChangedEventArgsCtF + 298
	6   App                           0x00000001072fbafd $s9App21MeetingCallingContextC17remoteParticipant_18didChangeMuteStateySo09ACSRemoteF0C_So27ACSPropertyChangedEventArgsCtFTo + 93
	7   libdispatch.dylib                   0x000000010d3e97ec _dispatch_call_block_and_release + 12
	8   libdispatch.dylib                   0x000000010d3ea9c8 _dispatch_client_callout + 8
	9   libdispatch.dylib                   0x000000010d3f8e75 _dispatch_main_queue_callback_4CF + 1152
	10  CoreFoundation                      0x00007fff2038fdbb __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	11  CoreFoundation                      0x00007fff2038a63e __CFRunLoopRun + 2685
	12  CoreFoundation                      0x00007fff203896d6 CFRunLoopRunSpecific + 567
	13  GraphicsServices                    0x00007fff2c257db3 GSEventRunModal + 139
	14  UIKitCore                           0x00007fff24696cf7 -[UIApplication _run] + 912
	15  UIKitCore                           0x00007fff2469bba8 UIApplicationMain + 101
	16  App                           0x0000000107437c3b main + 75
	17  libdyld.dylib                       0x00007fff2025a3e9 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[ACSCall displayName]: unrecognized selector sent to instance 0x6000026ef600'

<img width="652" alt="Screen Shot 2021-04-29 at 12 23 56" src="https://user-images.githubusercontent.com/8233432/116530186-6aa3db80-a8e6-11eb-8642-d31dd893381d.png">

**Comment by raosanat** [comment]
The code does not match with the error in the image. In the code you are doing `remoteParticipant.displayName` but error seems to be on `ACSCall` object. Can you double check you have the correct code snippet ?

**Comment by mariusu-msft** [comment]
@devgokhan please let us know if you are hitting this issue on latest BETA SDKs. Closing the issue.
