### ISSUE TITLE
[iOS] 1.0.0-beta.12 - Teams Interop [ACSCall mute | unmute]: mute / unmute backlogged while waiting for admission in Teams meeting

### ISSUE THREAD

**Issue by cheukchuen** [Azure/Communication#276]
Found an issue with the iOS Calling SDK 1.0.0-beta.12 with Teams Interop.

When a person tries to join a Teams meeting and is waiting for admission, we can only mute ourselves but can't unmute until admitted. The [mute](https://docs.microsoft.com/en-ca/objectivec/communication-services/calling/acscall#mute) and [unmute](https://docs.microsoft.com/en-ca/objectivec/communication-services/calling/acscall#mute) functions will be backlogged if we keep executing them while waiting for admission. Once admitted, the backlogged mute and unmute functions will all be executed at once, in order of execution.

Screenshots from iOS Calling Sample utilizing the Calling SDK with Teams Interop:

> Teams meeting: caller pending admission
> <img width="317" alt="Screen Shot 2021-04-29 at 5 10 31 PM" src="https://user-images.githubusercontent.com/11702891/116627947-1d426100-a91c-11eb-96c4-d450f7e4b82c.png">

> Waiting room of the caller: while waiting, the caller is able to mute once, but then unable to unmute-mute subsequently
> ![Screen Shot 2021-04-29 at 5 10 40 PM](https://user-images.githubusercontent.com/11702891/116627942-1ae00700-a91c-11eb-924f-35b15fc60a16.png)

**Comment by akania** [comment]
Thank you for reporting, while user is in lobby - mute/unmute don't take any effect as there's no audio/video connection until user will be admitted.
final state of mute should be applied once user joins to a meeting - we'll fix it in next release
[ADO#2435600](2435600)

**Comment by raosanat** [comment]
Fixed in the latest release [v2.1.0-beta.1](https://github.com/Azure/Communication/releases/tag/v2.1.0-beta.1). 
Please re-open the bug if still reproducible, thanks.
