### ISSUE TITLE
[iOS] Missing required key bundle version for 1.0.0

### ISSUE THREAD

**Issue by devgokhan** [Azure/Communication#278]
Hi. I am having this problem in 1.0.0 release when uploading it to App Store

![Screen Shot 2021-04-30 at 12 31 39](https://user-images.githubusercontent.com/8233432/116677155-896ea480-a9b0-11eb-84b7-e27f36171346.png)

**Comment by raosanat** [comment]
For now please manually update the info.plist file with CFBundleVersion as 1.0.0
We will fix this in the upcoming release. Sorry for the inconvenience.

**Comment by devgokhan** [comment]
Hi. How?
I am trying to add copy of Azure Common Plist file. But I am not sure it is fix or not.
If it is not resolves can you explain how I add it manually? There is no "General" option at the top like AzureCore.

**Comment by devgokhan** [comment]
Hi to resolve this I added CFBundleVersion into Info.plist files. File locations are:
AzreCommunicationCalling/AzureCommunicationCalling.xcframework/Info.plist
AzreCommunicationCalling/AzureCommunicationCalling.xcframework/ios-arm64/AzureCommunicationCalling.framework/Info.plist
AzreCommunicationCalling/AzureCommunicationCalling.xcframework/ios-ios-x86_64-simulator/AzureCommunicationCalling.framework/Info.plist

It is need to be inspect with Finder to see the files.

**Comment by raosanat** [comment]
Released 1.0.1
https://github.com/Azure/Communication/releases/tag/v1.0.1
