### ISSUE TITLE
Will .Net  calling library support xamarin forms since it runs on .net standard 2.0?

### ISSUE THREAD

**Issue by CARP-Kaiser** [Azure/Communication#279]
**Is your feature request related to a problem? Please describe.**
https://github.com/Azure/Communication/issues/38
It it upsetting that there is a lack of support for video calling in Xamarin forms.

**Describe the solution you'd like**
https://github.com/Azure/Communication/issues/16
Will this also cover forms projects? This would fill a need in Xamarin forms.

**Describe alternatives you've considered**
Writing bindings for the Zoom or Amazon Chime sdk.

**Additional context**

**Comment by MhAllan** [comment]
looking at their roadmap, there is nothing about Xamarin Forms or MAUI. Every time Azure comes with something nice they put a deal breaker in it in a way that pushes you to move away from .net or from away from azure: https://github.com/Azure/Communication/blob/master/roadmap.md

**Comment by ProbablePrime** [comment]
Lets use: https://feedback.azure.com/d365community/idea/0059d25d-8a48-ec11-a819-0022484bf651
