### ISSUE TITLE
[iOS] Hit exception when creating new ACSCallAgent while the previous one isn't fully deallocated

### ISSUE THREAD

**Issue by terrychen1122** [Azure/Communication#283]
Simulator crashed after the failure of creating `ACSCallAgent`.

**Expected behavior**
It should not throw exception to crash the app.

**Screenshot**
<img width="2292" alt="Screen Shot 2021-05-03 at 12 33 13 PM" src="https://user-images.githubusercontent.com/5403473/116923647-bd91d180-ac0b-11eb-97ea-c7571acc38e6.png">

**Desktop (please complete the following information):**
 - OS: iOS 14.0 Simulator[e.g. iOS]
 - Version 1.0.0

**Logs**
timeline: 2021/5/3 12:28PM US Pacific
[acs_sdk-0-s3579513326.blog.zip](https://github.com/Azure/Communication/files/6417226/acs_sdk-0-s3579513326.blog.zip)

**Comment by mariusu-msft** [comment]
This should be fixed in latest beta release. @terrychen1122 please let us know if you continue to see this and reopen.
