### ISSUE TITLE
How can I check voice intensity (loudness) of a participant audio stream for prioritizing?

### ISSUE THREAD

**Issue by hoangkimminh** [Azure/Communication#284]
**Describe the bug**
How can I check voice intensity (volumne) of a participant audio stream for prioritizing?

**To Reproduce**
There are videoStreams list that client received from ACS. They have isSpeaking and isMuted properties.
Is there a way to check which videos have the highest volume?

**Comment by chriswhilar** [comment]
Hello @hoangkimminh, we will be releasing this beta feature next week or the week after, along with guidance documentation and sample code!

**Comment by chriswhilar** [comment]
Hello @hoangkimminh we currently do not have a feature for voice intensity (loudness) of a participants audio stream.

However, next week or the week after, we will be releasing The Dominant Speaker feature, which is a bit similar and may be useful for you. This feature provides an ordered list of speakers - from most active -> least active. So based of this list, you can prioritize the most dominant speaker's video streams. We will also provide guidance documentation and sample code.

Would this dominant speaker feature be of any help for you? I will look into a voice intensity and see if this is something that we have planned on our roadmap and will let you know!

**Comment by hoangkimminh** [comment]
@chriswhilar thanks for your answer. I hope this feature is released as soon as possible.

**Comment by chriswhilar** [comment]
@hoangkimminh Your welcome! Yes this will be available on next release which will be next week or the week after, stay tuned!

**Comment by cwhil2492** [comment]
Hey @hoangkimminh, the dominant speaker feature is now available on version 1.1.0-beta.1 which was released last week.
