### ISSUE TITLE
Azure communication Services - IOS SDK

### ISSUE THREAD

**Issue by Kannyasheela** [Azure/Communication#285]
Request raised for the Azure communication services Teams Embed IOS SDK in the form 
https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR8MfnD7fOYZEompFbYDoD4JUMkdYT0xKUUJLR001ODdQRk1ITTdOMlRZNSQlQCN0PWcu
Its been a week still I didn't get any reply. Could please help me on this

**Comment by raosanat** [comment]
@tophpalmer Can you help @Kannyasheela ?

**Comment by akania** [comment]
@Kannyasheela I want to double check what's your goal? do you want to join to TAP program or do you want to enable your M365 tenant for ACS/Teams interop - if latter please use [this](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR21ouQM6BHtHiripswZoZsdURDQ5SUNQTElKR0VZU0VUU1hMOTBBMVhESS4u) form from our [public documentation](https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/voice-video-calling/get-started-teams-interop?pivots=platform-web)

**Comment by RinaRish** [comment]
Hi @Kannyasheela! I am closing this ticket since we did not hear from you back. Feel free to reopen if needed.
