### ISSUE TITLE
Is MacOS support possible?

### ISSUE THREAD

**Issue by hyounoo** [Azure/Communication#288]
I’m trying to implement ACS video call for multiplatform(ios/macos) but when I included the sdk it complained that the sdk does not support macos. 

Is there any work around to use acs sdk on macOS?

**Comment by raosanat** [comment]
@hyounoo We don't officially support MacOSX yet. But we plan to do it in future. We haven't verified yet but Apps built using Mac Catalyst should have access to iOS frameworks. Is this something that will work for you ? [Mac Catalyst](https://developer.apple.com/mac-catalyst/)

**Comment by hyounoo** [comment]
@raosanat Thanks for your answer but I get this error when enabling Mac Catalyst
```
ld: warning: directory not found for option '-F/Users/hyounoo/Library/Developer/Xcode/DerivedData/Catalyst-fkqbpqedbhuwulbhcbpnupbmzknn/Build/Products/Debug-maccatalyst/XCFrameworkIntermediates/AzureCommunicationCalling'
ld: framework not found AzureCommunicationCalling
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

and this is my Podfile
```
# source 'https://github.com/CocoaPods/Specs.git'
# Uncomment the next line to define a global platform for your project

# ignore all warnings from all pods
inhibit_all_warnings!

target 'Catalyst (iOS)' do
  platform :ios, '14.0'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'AzureCommunicationCalling'
end
```

**Comment by raosanat** [comment]
Ok thanks for giving it a try. We will fix this in one of the upcoming releases.

**Comment by ProbablePrime** [comment]
Migrated to: https://feedback.azure.com/d365community/idea/205262dc-1253-ec11-8f8e-000d3a987052
