### ISSUE TITLE
Is there a feature in ACS telephony-SMS service to restrict data to resides in preferred country such as Canada?

### ISSUE THREAD

**Issue by muheebhussain** [Azure/Communication#29]
We have a business requirement to integrate SMS service for appointment reminders, schedule and reschedule appointments with back and forth conversation via SMS. But we have this restriction that our data (such as message sent to phone number, message body .. etc) should always reside in Canada. 

This is a show stopper for us to integrate SMS Service. I reached out to 10-15 providers starting with Twilio.. none of them has this feature. Hoping ACS will give us flexibility to select region or country to store data in selected region? Even if we dont have option to select, if ACS service can restrict our data to always reside in Canada, that will be great.

Not sure if this is something ACS already has it. If not we would like to know if this something on ACS road map to rollout sooner?

**Comment by Prakulka** [comment]
Hi @muheebhussain, we do not store SMS messages persistently. You can be in complete control of where the data gets stored at your end. As a data processor, if a message cannot be delivered to the recipient (example if phone is switched off), we temporarily store the data to retry delivery for 24 hours (at most). All data gets deleted upon delivery. Please email us at phone@microsoft.com if you have more questions. Happy to chat more about specific use cases.

**Comment by muheebhussain** [comment]
Thanks @Prakulka!  I have few more questions I will be sending those in email.

**Comment by muheebhussain** [comment]
Hi @Prakulka,  

Sharing details below, might be helpful to understand our requirements. 

Ontario’s Personal Health Information Protection Act (PHIPA)

Data Centre Location
The location of the data center is an important factor for diversifying risk. If 100% of your data is being stored on Canadian soil, it is protected from external legislation. However, data that is moved across the border either in transit or at rest is susceptible to laws such as the US Patriot Act which allows it to be accessed at any time by the American government.
IT providers who store data within Canada must be well versed in the federal and provincial privacy laws that govern their region.

Is this something we have in Azure Communication Service to handle, Processing data and keeping temporary data in Canada All the time? Even if the data is deleted right after processing, we still wont be able to use ACS SMS service as per Ontario and Alberta’s Health Information Protection Act because data will be subjected to US Law.

**Comment by ProbablePrime** [comment]
@Prakulka Could you review Muheebhussain's new questions? Thank you

**Comment by Prakulka** [comment]
@ProbablePrime Thanks for bringing up this thread. This conversation was continued in email. We are good to close this issue.
