### ISSUE TITLE
SMS not delivered: Azure Communication Service

### ISSUE THREAD

**Issue by DeependraKhangarot** [Azure/Communication#290]
I have one communication service configured and was working fine earlier. 
For the last couple of weeks, the message delivery is stopped, tried to debug locally and "HttpStatusCode" was 202 with "Successful" equal to "true".

End-user didn't receive the message, could you please look into this.

**Comment by baodinh** [comment]
same here. is there any solution for it ?

**Comment by Prakulka** [comment]
Hello @DeependraKhangarot , @baodinh, For insights on delivery, you will need to enable delivery reports. Here is the Quickstart on how to subscribe to delivery report events - https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/telephony-sms/handle-sms-events. 

The 202 returned by the service means that your message has been queued to be sent and not delivered. Please check delivery report "deliveryStatus" field for checking success/failure of the message.
