### ISSUE TITLE
Acs user is not allowed to create conversation

### ISSUE THREAD

**Issue by TekExpo** [Azure/Communication#292]
I followed the steps to mentioned here:
https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/chat/meeting-interop

I am getting below error message when a call is made to [https://api3.cc.skype.com/conv/ ]
, I checked using developer tool and found below :

Response: 

{
  "operationFailure": {
    "sender": null,
    "reason": "unknown",
    "code": 403,
    "subCode": 5222,
    "phrase": "Acs user is not allowed to create conversation.",
    "resultCategories": [
      "ExpectedError"
    ],
    "acceptedElsewhereBy": null
  },
  "CorrelationId": "c52389f8-59bd-44e3-bd36-bdb435a173cc"
}

Any guidance to resolve the issue will help.

**Comment by ichivers** [comment]
I have the same problem:

azure:ACS:info 18/05/2021, 9:8:51:217 CallClient1:CallStack:PluginlessStack:Web[33885b7a-9c04-41de-9561-85266307c5f7][d13938bd][8a410ab7][2]:[40d49c8a][onCallStatusChanged] [status=LocalTerminated][reason={
  "sender": null,
  "reason": "unknown",
  "code": 403,
  "subCode": 5222,
  "phrase": "Acs user is not allowed to create conversation.",
  "resultCategories": [
    "ExpectedError"
  ],
  "acceptedElsewhereBy": null
}]

**Comment by kagbakpem** [comment]
Hello @TekExpo and @ichivers,

We'll take a look at the forms on our end and make sure to enable interop on your tenants.

Thanks

**Comment by ansrin** [comment]
We expect the above issue to be resolved, as all the pending tenants from our side are onboarded.
Please open a new issue ( with callId) if issue persists.
