### ISSUE TITLE
ACS Calling for Windows is not on nuget

### ISSUE THREAD

**Issue by guru98** [Azure/Communication#294]
Hi,
In the documentation and in release notes there are references to the first beta of ACS Calling for Windows but I can't find it

**Comment by LoadLibrary** [comment]
Hi @guru98 , feel free to add https://www.nuget.org/packages/Azure.Communication.Calling as dependency of your UWP project. You may also find helpful the quickstart at https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/voice-video-calling/getting-started-with-calling?pivots=platform-windows to get your conferences up and running.

**Comment by guru98** [comment]
It doesn’t work for me. Same issue. I use code that is  almost the same the one in docs. When you call echo123 the locale feed free until the call ends

Ottieni Outlook per Android<https://aka.ms/ghei36>

________________________________
