### ISSUE TITLE
[Web] Use web client over file:// urls

### ISSUE THREAD

**Issue by marko** [Azure/Communication#297]
**Describe the bug**
The web SDK [requires HTTPS or localhost](https://docs.microsoft.com/en-us/azure/communication-services/concepts/voice-video-calling/calling-sdk-features#user-webrtc-over-https), as WebRTC APIs require a secure context. 

file:// URLs are also [considered secure](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts#when_is_a_context_considered_secure), but are not allowed by the SDK.

The SDK currently throws an exception if `"https:" !== location.protocol && "localhost" !== location.hostname`

**Expected behavior**
The web SDK should work if opened through a file:// URL.

**Comment by mariusu-msft** [comment]
This is now fixed in latest beta SDKs. Closing issue.
