### ISSUE TITLE
[iOS] 1.0.1 - RemoteParticipantDelegate [onIsSpeakingChanged]: event triggered when remote participants leave the call

### ISSUE THREAD

**Issue by cheukchuen** [Azure/Communication#300]
**Describe the bug**
The `onIsSpeakingChanged` event from `RemoteParticipantDelegate` should only be triggered when someone is speaking or stopped speaking, but the event was also triggered when someone leaves the call even though the remote participant was on mute for the entire duration. This event was triggered before the `onRemoteParticipantsUpdated` event from `CallDelegate`.

**Steps to reproduce the behavior:**
1. Start a call
2. Have a remote participant join the group call (on mute for easier debugging)
3. Have the remote participant leave the call

**Expected behavior:**
Should only receive the `onRemoteParticipantsUpdated` event from `CallDelegate`

**Comment by kagbakpem** [comment]
@cheukchuen, thanks for reporting this. Can you make sure you check the isSpeaking property on the remoteParticipant object? Thae property should indicate whether the participant is speaking or not.

**Comment by cheukchuen** [comment]
@kagbakpem `isSpeaking` property is set to false on remoteParticipant whenever a participant leaves.

**Comment by kagbakpem** [comment]
This is expected, @cheukchuen. The event is to be combined with the property to properly reflect the participant speaking state. On the app side, you can choose to ignore the event if the property has not changed. Thanks
