### ISSUE TITLE
Android: When the internet connection is lost and within few seconds it comes back, the call does not resume back. 

### ISSUE THREAD

**Issue by ankiarora** [Azure/Communication#304]
When the internet connection is lost and within few seconds it comes back, the call does not resume back. 

**To Reproduce**
1. Connect the call.
2. And turn off the internet.
3. Turn it on immediately so that it resumes while being in a Connected state.
4. Call does not resumes.

**Expected behavior**
The call must resume back if the call is in a connected state. If it is of none state which becomes after 30 seconds, it is expected to not resume. But in a connected state, it should resume.

**Comment by mariusu-msft** [comment]
@ankiarora this should be fixed in latest Android BETA release. Closing issue
