### ISSUE TITLE
[iOS/ACS] Audio connection fails when we move app to background during teams call

### ISSUE THREAD

**Issue by mkambale** [Azure/Communication#308]
Hello, we are building an iOS app using ACS SDK beta-12 and found an issue with the SDK. Any help will be appreciated -
Steps:
1. User B is using an iOS app say myApp which uses ACS for video calling.
2. User A hosts Teams meeting, user B joins as a guest.
2. Audio transmission works at both ends perfectly.
4. User B moves app myApp to background when meeting is on, and opens any other app for 2 secs.
Or just leave the myApp in background for 2 sec.
5. User switches back to myApp.
6. Audio transmission breaks. Users cannot hear each other.

Expected:
User should continue to hear each other.

Call Id: fcd96218-b4e1-428f-b038-6861c63f03c5

**Comment by manoskow** [comment]
@akania FYI

Hi @mkambale, are you still experiencing this issue? If so, could you reproduce the problem and collect the calling logs and call id?

Following instructions here: https://docs.microsoft.com/en-us/azure/communication-services/concepts/troubleshooting-info?tabs=csharp%2Cios%2Cdotnet#enable-and-access-call-logs

**Comment by mkambale** [comment]
Hi @manoskow, @akania,

Yes issues is still observed. Please help.
Here is the call id: 464a7e76-d6e3-4803-906a-10d869d5f7f7
And, .blog files are attached.
[Caches.zip](https://github.com/Azure/Communication/files/6703451/Caches.zip)
[](url)

Thank you.

**Comment by mkambale** [comment]
I fixed it by making this change.

<img width="693" alt="Screen Shot 2021-07-15 at 1 50 38 PM" src="https://user-images.githubusercontent.com/28888982/125754737-c9e71576-b086-4cd9-add9-3ef9f9ffe597.png">
