### ISSUE TITLE
PlayPrompt/Record/SubscribeToTone api

### ISSUE THREAD

**Issue by rggammon** [Azure/Communication#31]
Is there a way to access the audio stream of a call, to build IVR or call routing capabilities?

Eg: the Service-hosted media scenario from -
https://docs.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/calls-meetings-bots-overview

**Comment by RinaRish** [comment]
@jsandoval-msft

**Comment by jsandoval-msft** [comment]
Hi @rggammon , the capability described is not currently supported as a feature. However, I've added your input into our feature prioritization process to help us refine our roadmap for new capabilities over the next several months. Thank you, good sir.

**Comment by rggammon** [comment]
Thank you @jsandoval-msft! I will close this issue, thank you for considering this feature request :)
