### ISSUE TITLE
[iOS] Remote participant stream is stretched after hang-up

### ISSUE THREAD

**Issue by ryanespiritu** [Azure/Communication#311]
**Describe the bug**
After hanging up a call, the remote participant's video stream is stretched in an unexpected animation.

**To Reproduce**
1. Join a call with two participants (A & B)
2. Participant streams should be in different aspect ratios (e.g. 9:16 and 16:9)
3. Render the video streams for each participant (adding the views to the view hierarchy)
4. Hang up the call for participant A
5. From participant A's perspective, observe weird stretch animation for the video stream of participant B

Note: this happens for both `ACSScalingModeFit` and `ACSScalingModeCrop`

**Expected behavior**
Remote participant's video stream should not be stretched.

**Screenshots**
https://user-images.githubusercontent.com/71148942/120866904-ae24e180-c545-11eb-8059-e6866e78e8ac.mov

**Smartphone (please complete the following information):**
- iPhone 11 Pro, iOS 14.4.2

**Additional context**
Seems to happen for SDK versions > ACS beta 9

**Logs**
[acs_sdk-0-2442831461.blog.zip](https://github.com/Azure/Communication/files/6601412/acs_sdk-0-2442831461.blog.zip)

**Comment by sankum-msft** [comment]
I have created AB#2465285 to track this internally

**Comment by RinaRish** [comment]
Hi @ryanespiritu! Thanks for reporting the issue, it was fixed on our side and the fix will be available in our next release.

**Comment by mariusu-msft** [comment]
Closing. The fix is available in latest release.
