### ISSUE TITLE
Android: If ACS user is rejected to enter the meeting from Teams app, call state changes to NONE from Disconnected

### ISSUE THREAD

**Issue by ankiarora** [Azure/Communication#318]
If an ACS user is rejected to enter the meeting from the Teams app, the call status changes from Connected to None, not allowing the user to know the exact reason for not being able to connect to the call. 

Steps to reproduce it:
1. Start connecting from mobile app having ACS SDK to Teams app.
2. Don't allow the user to enter the call. 
3. Call status changes from Connected to None.

More Details:
If the user is accepted from the Teams app to enter the call, and then removed from the call, the call state changes from Connected to Disconnected.

ACS Version: 
1.1.0-beta.1

**Comment by kagbakpem** [comment]
@ankiarora, thanks for reporting this issue. This should now be fixed on the latest version. Please give it a try and let us know
