### ISSUE TITLE
SMS Pricing? 

### ISSUE THREAD

**Issue by muheebhussain** [Azure/Communication#32]
I would like to clarify on SMS Pricing, is SMS cost same as Chat? It doesn't specify in documentation. 

$0.0008 USD per SMS? 

[Pricing Model ](https://docs.microsoft.com/en-us/azure/communication-services/concepts/pricing)

**Comment by anthonysva** [comment]
We will be updating the pricing on this page as new services are released to public preview. 

https://docs.microsoft.com/en-us/azure/communication-services/concepts/pricing

**Comment by telecomsxchange** [comment]
> We will be updating the pricing on this page as new services are released to public preview. 
> 
> 
> 
> https://docs.microsoft.com/en-us/azure/communication-services/concepts/pricing

How about PSTN termination pricing per country. Will that be added on the same page ? Probably need to add inbound/outbound rate per network. 

Also for sms. Certain countries charge for sender id registration, there should some pricing on that as well.
