### ISSUE TITLE
Android: Call.resume() do not the resume the call properly when a video from Teams app is on

### ISSUE THREAD

**Issue by ankiarora** [Azure/Communication#322]
On call.resume(), a callState is changed to CONNECTED, but a listener(call.addOnStateChangedListener) is not called most of the times.

1. Connect the ACS app with Teams app enabling **VIDEO** on Teams app. Without video, everything works as expected.
2. Put the ACS app call on hold using call.hold(). Call state changes from Connected to Local_hold
3. A few seconds later, resume the ACS app call using call.resume()
4. A call state is changed to Connected but, it is not called on call.addOnStateChangedListener
5. one out of 50 times, a "Connected" state change is called on call.addOnStateChangedListener

**Expected behavior**
a state change to "Connected" should be called in call.addOnStateChangedListener everytime.

**Additional context**
The above scenario works fine when the host's video is off. This issue is only when the host's video is on.

**Comment by kagbakpem** [comment]
Thanks for reporting this, @ankiarora. Can you please indicate which version of the Calling SDK you're using for this scenario and also the device used?

**Comment by ankiarora** [comment]
SDK version: 1.1.0-beta.1
Device: Redmi K20, Samsung Galaxy S9

**Comment by kagbakpem** [comment]
@ankiarora, the latest SDK was published today, v1.2.0-beta.1. Please give it a try and let us know if this issue persists.
