### ISSUE TITLE
ACS Chat thread LastMessageReceivedOn property wrong value

### ISSUE THREAD

**Issue by GuidoNeele** [Azure/Communication#325]
**Describe the bug**
When retrieving the changed threads via {endpoint}/chat/threads?maxPageSize={maxPageSize}&startTime={startTime}&api-version=2021-03-07 the LastMessageReceivedOn isn't up to date.

**To Reproduce**
1. Create thread
2. Add message to thread
3. Add another message to thread
4. Compare thread LastMessageReceivedOn with last chat message CreatedOn property

**Expected behavior**
The LastMessageReceivedOn DateTimeOffset should represent the time when the last message was received in the thread

**Screenshots**
![image](https://user-images.githubusercontent.com/1301586/123970711-a5df8b00-d9b9-11eb-90fa-cf23050aaab9.png)

**Comment by juancamilor** [comment]
Thanks @GuidoNeele 
The team is investigating the issue and will update this ticket once we have more details.

FYI @glorialimicrosoft

**Comment by juancamilor** [comment]
@GuidoNeele the team has identified the root cause and is working on a fix which we will hopefully release in the next couple of weeks. Thanks for the detailed description of the issue.

**Comment by angiurgiu** [comment]
We were returning the date of the last message received from participants other than the user listing the threads. However, per our documentation of the property, we've updated it to return the date of the last message sent to the thread - including those sent by the initiator of the ListThreads operation. The fix should be rolled out to production by end of next week.
