### ISSUE TITLE
Remote participant joining a teams call with Video off

### ISSUE THREAD

**Issue by Kalyan492** [Azure/Communication#327]
Hi,

Is there a way for a remote participant to join Teams meeting with their video off. Like a user can join call muted by using muted in StartCallOptions?

Thanks & Regards,

Kalyan.

**Comment by kagbakpem** [comment]
Hello @Kalyan492,

Joining a Teams meeting with Video off is possible indeed. Here are documentation to do so per platform. You can create a JoinCallOptions object and ommit the VideoOptions or set it to null optionally.

[Web](https://docs.microsoft.com/en-us/javascript/api/azure-communication-services/@azure/communication-calling/callagent?view=azure-communication-services-js#join_MeetingLocator__JoinCallOptions_)
[Android](https://docs.microsoft.com/en-us/java/api/com.azure.android.communication.calling.callagent.join?view=communication-services-java-android)
[iOS](https://docs.microsoft.com/en-us/objectivec/communication-services/calling/acscallagent)

Thanks
