### ISSUE TITLE
ACS javascript library is not being able to pick Media Stream devices

### ISSUE THREAD

**Issue by jorgegarciadominguez** [Azure/Communication#332]
**Describe the bug**
I am launching ACS javascript based server to create conferences. Everything works fine in Chrome and Edge, but not with CEF (Chrome Embedded Framework) Browser. 

**To Reproduce**
1. Run https://github.com/Azure-Samples/communication-services-web-calling-tutorial
2. Obtain Provision User
3. Start Group call
4. Camera and/or Mic will not be picked up and timeout error will be thrown in development console.

**Expected behavior**
Mics and Cameras of the client devices should be picked up.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: CEF Browser
 - Version: Latest

**Error log**
`azure:ACS:info 7/7/2021, 18:19:40:532 CallClient1:CallStack:MA:DeviceManager:MediaStreamManager:MediaStream:6:WebRTCProvider Constraints to be applied: {"audio":{"deviceId":"u14"}}
log.browser.js:18 azure:ACS:info 7/7/2021, 18:19:41:349 CallClient1:CallStack:Trouter [Connection] Ping interval fired
log.browser.js:18 azure:ACS:info 7/7/2021, 18:19:41:349 CallClient1:CallStack:Trouter [Connection] emitting ping event
log.browser.js:18 azure:ACS:info 7/7/2021, 18:19:41:386 CallClient1:CallStack:Trouter [Connection] onPingResponse
log.browser.js:18 azure:ACS:info 7/7/2021, 18:19:41:531 CallClient1:CallStack:MA:webrtc2-2:qm:OptVideoCnt optimal video receivers count changed to 4
log.browser.js:12 azure:ACS:error 7/7/2021, 18:20:0:533 CallClient1:CallStack:MA:DeviceManager:MediaStreamManager [845cd814] Error from promiseQueue! {"type":"MediaStreamRequestTimedout","detail":"Media Stream request timed out. constraints: {\"audio\":{\"deviceId\":\"u14\"},\"video\":null,\"withTimeout\":true}","isAudio":true,"message":"Media Stream request timed out. constraints: {\"audio\":{\"deviceId\":\"u14\"},\"video\":null,\"withTimeout\":true}"}
log @ log.browser.js:12
log.browser.js:18 azure:ACS:info 7/7/2021, 18:20:0:534 CallClient1:CallStack:MA:DeviceManager Device event: stream_error: {"mediaType":"Audio","error":{"type":"MediaStreamRequestTimedout","detail":"Media Stream request timed out. constraints: {\"audio\":{\"deviceId\":\"u14\"},\"video\":null,\"withTimeout\":true}","isAudio":true,"message":"Media Stream request timed out. constraints: {\"audio\":{\"deviceId\":\"u14\"},\"video\":null,\"withTimeout\":true}"}}
log.browser.js:12 azure:ACS:error 7/7/2021, 18:20:0:534 CallClient1:CallStack:MA:webrtc2-2:SSM:StreamsProvider Media type is not found for stream: [object Object]
log @ log.browser.js:12
log.browser.js:15 azure:ACS:warning 7/7/2021, 18:20:0:534 CallClient1:CallStack:MA:webrtc2-2:SSM:StreamsProvider Stream with type: undefined is not registered
log @ log.browser.js:15
log.browser.js:12 azure:ACS:error 7/7/2021, 18:20:0:534 CallClient1:CallStack:MA:DeviceManager:MediaStreamManager could not start media stream: 6, total streams: 1, error: {"type":"MediaStreamRequestTimedout","detail":"Media Stream request timed out. constraints: {\"audio\":{\"deviceId\":\"u14\"},\"video\":null,\"withTimeout\":true}","isAudio":true,"message":"Media Stream request timed out. constraints: {\"audio\":{\"deviceId\":\"u14\"},\"video\":null,\"withTimeout\":true}"}
log @ log.browser.js:12
log.browser.js:18 azure:ACS:info 7/7/2021, 18:20:0:534 CallClient1:CallStack:MA:DeviceManager:MediaStreamManager release media stream generation: 6 cached: 1
log.browser.js:18 azure:ACS:info 7/7/2021, 18:20:0:534 CallClient1:CallStack:MA:UFD [8121dc49] Raising UFD DeviceCaptureNotFunctioning for Audio: Bad
log.browser.js:12 azure:ACS:error 7/7/2021, 18:20:0:535 CallClient1:CallStack:MA:webrtc2-2:SSM:StreamsProvider Media stream request error: {"type":"MediaStreamRequestTimedout","detail":"Media Stream request timed out. constraints: {\"audio\":{\"deviceId\":\"u14\"},\"video\":null,\"withTimeout\":true}","isAudio":true,"message":"Media Stream request timed out. constraints: {\"audio\":{\"deviceId\":\"u14\"},\"video\":null,\"withTimeout\":true}"}`

**Comment by akania** [comment]
Hi @jorgegarciadominguez - thank you for reporting 
[ACS supports number of browsers](https://docs.microsoft.com/en-us/azure/communication-services/concepts/voice-video-calling/calling-sdk-features#javascript-calling-sdk-support-by-os-and-browser) - but Chrome Embedded Framework is not one of them, we'll keep this GH issue as a feature request

**Comment by LaithRodan** [comment]
Feature request tracked under "Epic 2596460: [Web] Support for Chromium Embedded Framework"
