### ISSUE TITLE
[Android][Teams Interop] Call.hangUp() does not return in certain scenarios

### ISSUE THREAD

**Issue by Gemakk** [Azure/Communication#333]
**Describe the bug**
As part of call cleanup code, we typically would call the method Call.hangUp() to ensure that we hang up the call before cleaning up the UI and changing Activities.  Call.hangUp() returns a CompleteableFuture, so waiting for it to complete makes sense to ensure that our user has left the call.  There is one scenario in which Call.hangUp() never returns: When having been denied entry to a Call by a user in the Teams meeting.

**To Reproduce**
1. Join a Teams call and be taken to the Lobby
2. Be denied entry to the meeting by a user on the call
3. Call Call.hangUp()
4. Note that its CompleteableFuture never finishes

**Expected behavior**
Call.hangUp() should return

**Smartphone (please complete the following information):**
 - Device: Android Pixel 2
 - OS: Android 9

**Comment by kagbakpem** [comment]
@Gemakk, we have a fix for this that will be release on the next SDK version. Thanks for reporting this and stay tuned!

**Comment by kagbakpem** [comment]
Linking internal ADO issue AB#2508399

**Comment by kagbakpem** [comment]
@Gemakk, this has been resolved in the latest version of the SDK 1.2.1-beta.1. Please give it a try and let us know if the issue persists.
