### ISSUE TITLE
ACS and Chat Bot (using BOT Framework) integration

### ISSUE THREAD

**Issue by Dharm78** [Azure/Communication#334]
We are working on a solution which is based on Chat Bot (using MS Bot Framework) and  ACS Teams interop. 

We want to respond to basic/initial questions of user using chat bot	
If user is not satisfied with Chat Bot's answers , we want to use ACS Teams Interop feature to start chat/call with real agent.

Do we have Bot Framework and ACS Chat integration into single chat widget?

**Comment by juancamilor** [comment]
Thanks for the question @Dharm78 
We don't have any widgets that have an integration between ACS chat and the botframework at the moment. There is an ongoing project that will allow users to bring bots to ACS via a new bot framework channel, but it is still in development, and won't include any UI components.
There is however a team building UI components for ACS. This may give you a good starting point for what you are looking for :
https://azure.github.io/communication-ui-library/?path=/story/quickstarts-composites--page
