### ISSUE TITLE
speakingWhileMicrophoneIsMuted UFD not working on safari

### ISSUE THREAD

**Issue by cwhil2492** [Azure/Communication#335]
**Describe the bug**
speakingWhileMicrophoneIsMuted UFD is not working on safari.

**To Reproduce**
Speak into microphone after calling the Call.mute() api

**Expected behavior**
speakingWhileMicrophoneIsMuted: true UFD should be raised.

**Screenshots**

**Desktop (please complete the following information):**
 - MacOS
 - Safari

**Smartphone (please complete the following information):**
 - Iphone 12 Pro Max
 - iOS
 - safari

**Comment by cwhil2492** [comment]
Issue has been fixed, and fix for this will be available in the next calling web sdk release.

**Comment by RinaRish** [comment]
@cwhil2492 any update?

**Comment by cwhil2492** [comment]
@RinaRish we can close this, its been fixed as part of latest beat sdk
