### ISSUE TITLE
Cannot share screen between two browsers using ACS JavaScript SDK

### ISSUE THREAD

**Issue by yanghwai** [Azure/Communication#336]
**Describe the bug**
On two browser tabs denoting two clients, when one client tries to share its screen with the other, a dialog prompts letting user to choose which window/tab to share. After selecting, nothing happens on the other side. And the call itself ended after a few seconds.

This only happens on a certain machine **A** (regardless of edge/chrome I use). The very same application works fine on two browser tabs on another machine **B**. Share screen from browser on machine **A** to machine **B** works fine, and vice versa.
- [❌] Two chrome tabs on **Machine A**. 
- [❌] Two edge tabs on **Machine A**. 
- [❌] One chrome, one edge tab on **Machine A**. 
- [✔] Two chrome tabs on **Machine B**. 
- [✔] Call from one chrome tab on **Machine A** to one chrome tab on **Machine B**. 
- [✔] Call from one chrome tab on **Machine B** to one chrome tab on **Machine A**.

**To Reproduce**
1. Caller makes 1:1 call to callee
2. Callee accepts the call from the dialog prompt and invoke call.startScreenSharing() to start screen sharing
3. Callee selects the window to share
4. Wait a while.
5. Call ended unexpectedly with code=487 subcode=10004

**Expected behavior**
Caller should be able to receive from the remoteVideoStream callback "isAvailableChanged" and render the corresponding stream.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome, Edge
 - Version: Chrome Version 91.0.4472.124 (Official Build) (64-bit), Microsoft Edge Version 91.0.864.67 (Official build) (64-bit). 

**Additional context**
  "@azure/communication-calling": "^1.1.0",
  "@azure/communication-common": "^1.0.0",

**Logs**
Callee side log:
[localhost-1626243281889.log](https://github.com/Azure/Communication/files/6813963/localhost-1626243281889.log)

**Comment by akania** [comment]
Thank you for reporting, we'll investigate the issue
ADO 2518064

**Comment by fizampou** [comment]
Please update to the latest SDK version.
That issue shall be fixed.
