### ISSUE TITLE
[Web] Issue of calling service during remote desktop connection.

### ISSUE THREAD

**Issue by t-yanzhang** [Azure/Communication#337]
**Describe the bug**
The shard screen is not visible when demoing web app calling functions through remote desktop connection.
The web app using ACS javascript sdk works fine when we run it directly on a local dev machine. The issue only happens when connecting to that dev machine through remote desktop connection and run it in the same way. 

**To Reproduce**
1. Use remote desktop connection to connect to a dev machine.
2. On the remote desktop of that dev machine, start a web application that uses ACS javascript sdk in two separate browser tabs (one as caller and one as callee).
3. Retrieve ACS User ID for the callee.
4. Use the retrieved ACS User ID to initiate a call to the callee from the caller side.
5. Callee side answers the call and gets the prompt to select which screen to share.
6. See error.

**Expected behavior**
We expected the web app that uses ACS javascript sdk to work in the same way as when we run it directly on the dev machine: the web app for caller side should get the shared screen from the callee side.

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser Edge
 - Version Version 91.0.864.67 (Official build) (64-bit)
 - Browser Chrome
 - Version Version 91.0.4472.124 (Official Build) (64-bit)

**Logs**
Log of caller side browser:
<img width="1011" alt="RemoteDesktopCallerLog" src="https://user-images.githubusercontent.com/82136704/125573434-77afcab3-1fc1-4b10-aca0-ce2fd4651a20.png">

Log of callee side browser:
<img width="1017" alt="RemoteDesktopCalleeLog" src="https://user-images.githubusercontent.com/82136704/125573454-d046e6dd-9e00-424e-92b0-c6e5772252e7.png">

**Comment by RinaRish** [comment]
[AB#2546065](https://skype.visualstudio.com/SPOOL/_workitems/edit/2546065)

**Comment by fizampou** [comment]
Remote desktop is not supported yet.
