### ISSUE TITLE
Reserved capacity for calling minutes/messages and more

### ISSUE THREAD

**Issue by iamalexmang** [Azure/Communication#34]
It would be amazing if the service would have the ability to allow for reservations.
Similarly to how one can reserve for a lower price compute compute, Cosmos DB, SQL Database, Storage capacity and more, I would appreciate if, in exchange for a year/3-years term I could save the overall cost on my subscription(s) for Azure Communication Service.

**Comment by RinaRish** [comment]
Hi Alex! Thanks for the feedback, we will look into this.

**Comment by tophpalmer** [comment]
Thank you again for the feedback @iamalexmang ! 

We're tracking this on the backlog but it's fairly deep in the queue for us. FWIW you can accomplish a similar arrangement with [Azure Monetary Commit as part of an Azure Enterprise Agreement](https://docs.microsoft.com/en-us/azure/cost-management-billing/understand/review-enterprise-agreement-bill).
