### ISSUE TITLE
[Android] App crashes when joining a microsoft teams with AudioOptions

### ISSUE THREAD

**Issue by radulescuserban** [Azure/Communication#340]
**Describe the bug**
App sometime crashes when joining a microsoft teams conference with AudioOptions() set in the JoinCallOptions object.

**To Reproduce**
**Prerequisite:**
- have an AudioOptions bnject set in JoinCallOptions

1. join a microsoft teams conference

**Expected behavior**
App should not crash

**Smartphone (please complete the following information):**
 - Device: Nexus 5X
 - OS: Android 8.1

**Additional context**
SDK version:
com.azure.android:azure-communication-calling:1.1.0-beta.1

AS logs and blog file:
[crash_3_teams.txt](https://github.com/Azure/Communication/files/6822117/crash_3_teams.txt)
[acs_sdk-0-s747796850.zip](https://github.com/Azure/Communication/files/6822123/acs_sdk-0-s747796850.zip)

**Comment by kagbakpem** [comment]
Thanks for reporting this issue @radulescuserban. We'll investigate and get back to you as soon as possible.

**Comment by kagbakpem** [comment]
We have identified the issue and have a fix in our upcoming version. We'll let you know as soon as it's available.

**Comment by jsaurezlee-msft** [comment]
@radulescuserban This issue is resolved on our latest version v.1.2.0-beta.1. Give it a try and let us know if the issue persists. Thanks
