### ISSUE TITLE
[Android] Crash on hanging up from a conference

### ISSUE THREAD

**Issue by radulescuserban** [Azure/Communication#346]
**Describe the bug**
When leaving a microsoft teams meeting sometimes the app crashes.

**To Reproduce**
1. Join a microsoft teams meeting
2. Leave the microsoft teams meeting
3. App crashes

**Expected behavior**
App doesn't crash

**Smartphone (please complete the following information):**
 - Device: Nexus 5X
 - OS: Android 8.1

**Additional context**
This is not a 100% repro rate.
Version of calling library: com.azure.android:azure-communication-calling:1.2.0-beta.1
I have attached the blog file and a txt with what I could salvage from my logcat (which is, unfortunately,  truncated).
[logs.zip](https://github.com/Azure/Communication/files/6899248/logs.zip)

**Comment by kagbakpem** [comment]
@radulescuserban, thanks for reporting this issue. We are aware of the `java.lang.StackOverflowError` exception issue and are working on a fix that should be ready later this week. We'll keep you posted on the progress. Thanks

**Comment by kagbakpem** [comment]
@radulescuserban, we published 1.2.0-beta.2 today with a fix fir this issue. Please try it out and let us know if you're still seeing it. ty.
