### ISSUE TITLE
[Android] - keeps working after application is closed

### ISSUE THREAD

**Issue by pavelprystinka** [Azure/Communication#349]
**Describe the bug**
If during the call application is closed (not just sent to background) the audio (both ways) and video out are still working.
This is very confusing for user.

**To Reproduce**
Steps to reproduce the behaviour:
1. Use Android SDK to make a call. For instance https://github.com/Azure-Samples/communication-services-android-calling-hero
2. Join a call
3. Enable audio and video
4. Close application
5. Observe that remote participants can still be herd as well as they can still hear user speaking.

**Expected behaviour**
All connections should be closed.

**Smartphone (please complete the following information):**
 - Device: Nokia 2.4
 - OS: Android 11

**Comment by jsaurezlee-msft** [comment]
AB#2542311
