### ISSUE TITLE
Samples need to be upgraded to .NET 3.1

### ISSUE THREAD

**Issue by timheuer** [Azure/Communication#35]
**Describe the bug**
.NET Core 2.2 is out of support and no samples should be published using them.  Upgrade to .NET 3.1 targeting.

Some changes to the web apps will be required to remove Obsolete API usage.

Changes to:

- [ ] Group Chat Hero Sample
- [ ] Group Calling Hero Sample

**Expected behavior**
Microsoft samples use supported softare.

**Additional context**
https://dotnet.microsoft.com/download/dotnet-core for a list of supported versions.

**Comment by RinaRish** [comment]
Hi Tim! Thanks for reporting the issue, we are aware of that and working on a fix.

**Comment by timheuer** [comment]
Cool I submitted a PR for the fixes.

**Comment by timheuer** [comment]
@rinarish I'd recommend keeping this issue open until your fix is done to help others know that it is 'open' and not solved.
