### ISSUE TITLE
[IOS] Slow screen share 

### ISSUE THREAD

**Issue by bfwg** [Azure/Communication#350]
**Describe the bug**
Starting with screen share video stream takes about 10 seconds to show up on the other end. 

**To Reproduce**
1. Peer A using the iOS SDK and Peer B using the Web.
2. Peer A joins the meeting, and Peer B joins the meeting.
3. Peer B clicks screenshare.
4. Peer A leaves the meeting.
5. Peer A rejoins the meeting.

**Expected behavior**
Peer A should see the screenshare video stream from Peer B right away.

**Desktop (please complete the following information):**
 - iOS

**Smartphone (please complete the following information):**
 - Device: iOS X
 - 14

**Comment by RinaRish** [comment]
Hi @bfwg! Thanks for reporting the issue. Can you please provide the versions of SDKs you are using on iOS and the web?

**Comment by bfwg** [comment]
HI, we are using the blow:
'AzureCore', '1.0.0-beta.12'
'AzureCommunicationCalling', '1.1.0'

**Comment by RinaRish** [comment]
[AB#2546062](https://skype.visualstudio.com/SPOOL/_workitems/edit/2546062)

**Comment by akania** [comment]
@bfwg can you please try to repro with latest version of ACS SDK?
