### ISSUE TITLE
Acs interop does not allow this user target in dial out.

### ISSUE THREAD

**Issue by deepsuvarna** [Azure/Communication#353]
**Describe the bug**
Azure Communication Calling with Teams users (121) does not work. The call automatically gets disconnected.

The following error shows up on the network tab in google chrome:
POST request : https://api3.cc.skype.com/conv/

{
  "operationFailure": {
    "sender": null,
    "reason": "unknown",
    "code": 403,
    "subCode": 5223,
    "phrase": "Acs interop does not allow this user target in dial out.",
    "resultCategories": [
      "ExpectedError"
    ],
    "acceptedElsewhereBy": null
  },
  "CorrelationId": "6137cd29-692f-411b-9dd1-57d776e850d7"
}

**Comment by kagbakpem** [comment]
@deepsuvarna, can you please provide more details? Which tenant are you using? And which version of the SDK are you using? Can you also make sure the Teams tenant is properly configured to allow meeting joins from an ACS user?

**Comment by deepsuvarna** [comment]
> @deepsuvarna, can you please provide more details? Which tenant are you using? And which version of the SDK are you using? Can you also make sure the Teams tenant is properly configured to allow meeting joins from an ACS user?

The version that I am currently using is     "@azure/communication-calling": "^1.1.0".
I have just taken the default code sample for acs-voice-calling and instead of **communicationUserId** I am using **microsoftTeamsUserId**.

Eg:
const call = callAgent.startCall(
    [{ microsoftTeamsUserId: "<Guid>" }]
  );

Teams tenant is properly configured to allow joining meetings. I have attached the image for your reference. Also, I am able to join the scheduled teams meeting successfully. 

The issue is only when I need to initiate a 121 call with the teams user. 

![image](https://user-images.githubusercontent.com/82024294/129134103-6a68af17-87f5-41d9-90ed-efec37c89a69.png)

**Comment by jsaurezlee-msft** [comment]
Hi @deepsuvarna:

Thanks for attaching the code snippet. For Teams interop, only joining teams meetings (by using a meeting link or a meeting's coordintates) is available. So using callAgent.startCall with a teams user identity or guid won't work. You can use callAgent.join with a Meetings locator object to join a Teams meeting. Note that at this time, this a preview feature and you need to use the beta versions of the Calling SDK.

You can find more info here: [Quickstart: Use the Communication Services Calling SDK](https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/voice-video-calling/calling-client-samples?pivots=platform-web) in the Join a Teams Meeting section.

I'm closing this issue, but feel free to reopen if there are more questions.

**Comment by deepsuvarna** [comment]
@jsaurezlee-msft 
Thanks for the information.
