### ISSUE TITLE
[Android] After disposing videoStreamRenderer multiple times, frames are not rendered to UI (onRendererFailedToStart)

### ISSUE THREAD

**Issue by iaulakh** [Azure/Communication#357]
**Describe the bug**
After disposing renderer view multiple times, Frames are not rendered to UI onRendererFailedToStart

Use case: Application displays only 6 participants to UI. When user speaks, the video stream for user is displayed. When user no longer speaks and other participants speak, application removes the user from UI and destroys the renderer view.
When user speaks multiple times after a time interval, video stream is not displayed.

To create this behaviour, create renderer and destroys multiple times. In third or fourth attempt the error will occur. onRendererFailedToStart 

**To Reproduce**
1) start a call with remote participant with video on
2) dispose remote video stream and recreate (multiple time)
3) Create renderer view and attach to UI
Issue: Video not displayed on UI
Note: was able to reproduce issue with SDK team test application (click dispose video stream button multiple time)

**Smartphone (please complete the following information):**
 - Device: Pixel 4a
com.azure.android:azure-communication-calling:1.2.0-beta.2
https://skype.visualstudio.com/SPOOL/_workitems/edit/2545701

**Comment by jsaurezlee-msft** [comment]
AB#2545907

**Comment by iaulakh** [comment]
The workaround on application side is to refresh UI after delay. If I reduce time then some video views will display or some not.

```kotlin
(container holding video views).postDelayed( {
            (container holding video views).invalidate()
        }, 5000)
```
