### ISSUE TITLE
[Android] call client dispose() takes long time (2 minutes). sometime the call to dispose never returns.

### ISSUE THREAD

**Issue by iaulakh** [Azure/Communication#358]
**Describe the bug**
call client dispose() takes long time (2 minutes). sometime the call to dispose never returns

**To Reproduce**
Steps to reproduce the behaviour:
- Start a call
- Add below logic to code on call end
          When disconnected status received.
          Execute below code
            callAgent?.dispose() 
            callClient?.dispose()
- It takes a long time to proceed to next line after calling `callClient?.dispose()` 
- Sometimes call never returns

**Smartphone (please complete the following information):**
 - Device: Pixel 4a

com.azure.android:azure-communication-calling:1.2.0-beta.2

https://skype.visualstudio.com/SPOOL/_workitems/edit/2546063

**Comment by jsaurezlee-msft** [comment]
AB#2546063

**Comment by raosanat** [comment]
Fixed in the latest release of iOS [v2.1.0-beta.1](https://github.com/Azure/Communication/releases/tag/v2.1.0-beta.1). 
Please re-open the bug if still reproducible, thanks.
