### ISSUE TITLE
[iOS] Missing info.plist file in AzureCommunicationCalling cocoapod

### ISSUE THREAD

**Issue by mkambale** [Azure/Communication#359]
Hello, 

I dont see any info.plist file in latest AzureCommunicationCalling cocoapod. Without that we cannot upload any app to 
Apple App Store which uses this pod.

What would be the correct way to address this?
Any workarounds?

Thank you,
Manjunath K

<img width="443" alt="Screenshot 2021-08-17 at 4 44 31 PM" src="https://user-images.githubusercontent.com/28888982/129717010-79d66cb7-95c5-49f2-8eb1-a0ebdce3e443.png">

**Comment by mkambale** [comment]
This is the error thats shown when I try to upload from xcode.
<img width="977" alt="Screenshot 2021-08-17 at 7 38 05 PM" src="https://user-images.githubusercontent.com/28888982/129774604-832424dd-6dd3-42d4-8e09-85396a522551.png">

**Comment by RinaRish** [comment]
Hi @mkambale! Can you please provide a bit more details on which version of ACS SDK you are using?

**Comment by RinaRish** [comment]
Closing it since we did not hear back from you. Please feel free to reopen if help neede.
