### ISSUE TITLE
Videos From Mobile Devices Not Getting Rendered On Teams App/Web

### ISSUE THREAD

**Issue by Shivam20121992** [Azure/Communication#365]
**Describe the bug**
I am using **ACS with teams Interop**. and the ACS users video is not getting rendered on teams app/web. 

**To Reproduce**
1-One participant on Teams client (Both Web and Desktop) 
2-Second is on mobile , using app build with ACS SDK (1.2.1-beta.1)
3-ACS and Teams users join to a scheduled teams meeting.
4-Video sent from ACS is not visible on Teams side .

**Expected behavior**
Can able to see videos coming from mobile devices on teams app/web.

**Desktop (please complete the following information):**
 - Browser - **Chrome**
 - Version - **92.0.4515.159**

**Smartphone (please complete the following information):**
 - Device: Samsung, RealMe, OnePlus
 - OS: Android 11
 - Browser - **Chrome**
 - Version - **92.0.4515.159**

**Comment by Kalyan492** [comment]
> **Describe the bug**
> I am using **ACS with teams Interop**. and the ACS users video is not getting rendered on teams app/web.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 1-One participant on Teams client (Both Web and Desktop)
> 2-Second is on mobile , using app build with ACS SDK (1.2.1-beta.1)
> 3-ACS and Teams users join to a scheduled teams meeting.
> 4-Video sent from ACS is not visible on Teams side .
> 
> **Expected behavior**
> Can able to see videos coming from mobile devices on teams app/web.
> 
> **Desktop (please complete the following information):**
> 
> * Browser - **Chrome**
> * Version - **92.0.4515.159**
> 
> **Smartphone (please complete the following information):**
> 
> * Device: Samsung, RealMe, OnePlus
> * OS: Android 11
> * Browser - **Chrome**
> * Version - **92.0.4515.159**

I am facing the same issue. When a user joins from mobile, unable to see the video stream from desktop web or Teams user. In this case for mobile user, videoStreamRenderer.createView() is not returning the view.

**Comment by RinaRish** [comment]
Hi @Shivam20121992 @Kalyan492! Thanks for reporting the issue. Is it possible to provide callId? or logs?

**Comment by Kalyan492** [comment]
> Hi @Shivam20121992 @Kalyan492! Thanks for reporting the issue. Is it possible to provide callId? or logs?

Hi, Sorry for the late response. I have updated the calling package to latest version. I am unable to replicate the issue. Streams from mobile device is working fine.

Thank you.

**Comment by akania** [comment]
closing per latest comment from @Kalyan492

**Comment by Shivam20121992** [comment]
@Kalyan492 
Thanks for reporting on this. Can you confirm that, Is it working on all mobile devices and not on some devices?  I too have updated the calling package to the latest version and I can replicate the issue.  

@RinaRish 
Let me run my application and I will share the call id with you.

@akania 
Can you please reopen this ticket as I am still facing this?

**Comment by Shivam20121992** [comment]
++Adding development,

When I join the team meeting and turn on my video. **on MS Teams it signals that video is coming but it does not get rendered**. That might be an issue on the team's side but just reporting for reference.
