### ISSUE TITLE
[iOS] Deploy issue: missing Info.plist for Trouter.framework

### ISSUE THREAD

**Issue by alexLipici-tmd** [Azure/Communication#367]
**Describe the bug**
I integrated both Azure Communication Calling and Azure Chat and we decided to release an incremental update to the users that will use video call and chat feature. The issue appears when I try to upload the build to the appstore, as you can see on the attached screenshot. It seems that Trouter client (which is used by Azure Chat SDK for Real time notification) doesn't have any Info.plist and also a MinimumOSVersion into it. I'm using Azure Calling 2.0.0-beta1 and Azure Chat 1.0.1. The Trouter  version is 0.0.1-beta5 (as on the Chat SDK podspec).

**To Reproduce**
1. Archive the project
2. Upload to AppStore
3. See error from attached file

**Expected behavior**
Expected behaviour is to upload the app without any error. So it involves solving Trouter client dependencies

**Screenshots**
<img width="699" alt="Screenshot 2021-09-01 at 20 18 35" src="https://user-images.githubusercontent.com/79912893/131829892-55a2cc95-13bf-48f8-a0ca-f0a466a6a2da.png">

**Smartphone (please complete the following information):**
 - Device: any iOS device
 - OS: iOS 11.1 and above

**Comment by angiurgiu** [comment]
@alexLipici-tmd this was a known bug, we've released a new version of the chat package based on a Trouter version that has a correct info.plist. Please try out the latest swift chat package and let us know if the issue persists.

@glorialimicrosoft

**Comment by alexLipici-tmd** [comment]
@angiurgiu I've tried Azure Chat 1.0.2 and now it's working. Thank you for the reply
