### ISSUE TITLE
Is this a browser only API?

### ISSUE THREAD

**Issue by sipsorcery** [Azure/Communication#37]
Given the browser compatibility list it seems this SDK is relying on the client running in a browser supporting WebRTC. Will desktop or non-browser based clients ever be supported?

**Comment by mariusu-msft** [comment]
Hi Aaron,

The Calling Voice & Video client libraries are currently available for JavaScript (requiring a compatible browser), and for iOS/Android as native SDKs.

Documentation for library availability can be found here: https://docs.microsoft.com/en-us/azure/communication-services/concepts/sdk-options

Is there a platform in particular that you’d like to see support for?

Thanks,
Marius

**Comment by sipsorcery** [comment]
Thx for the response.

> Is there a platform in particular that you’d like to see support for?

I'd like to be able to place calls to Microsoft Teams from a .NET Core Console application and get access to the raw audio and video streams.

**Comment by nmurav** [comment]
@sipsorcery thanks, .Net app on the roadmap. Quick questions can you please provide more information on the case for a Call to a Teams user from the .Net app? What is the use case here?

**Comment by sipsorcery** [comment]
> Quick questions can you please provide more information on the case for a Call to a Teams user from the .Net app? What is the use case here?

The request I've had from customers is the same as always with any new communications platform, to be able to call from their existing telephone/PBX systems into a Teams meeting or direct to a Teams user. There are two main facets to it:
 - First the ability to be able to integrate calls to Teams into existing application workflows.
 - Second to desire to avoid the constraints and costs imposed by the [Microsoft Phone System](https://www.microsoft.com/en-ie/microsoft-365/microsoft-teams/voice-calling) product.

I don't hold out much hope that Teams will expose a public SIP/VoIP/WebRTC method, through this or any other API, in the foreseeable future. As a real-time communications developer I always hope public access will be included; it makes life sooo much easier. Having been through all the hacky workarounds with SIP/XMPP/Jingle for Google Voice it'd be really nice to avoid the same thing again. But I digress, of course none of that is much to do with this API or issue.

**Comment by pfresnay** [comment]
@nmurav
.NET on the roadmap is a great news! Can you confirm that we will be able to use calling in UWP app with video/audio/screen sharing ?
Any timeframe ? :-)

**Comment by legistek** [comment]
> Is there a platform in particular that you’d like to see support for?

Windows!

This is Microsoft I'm talking to right? :)

**Comment by AdamFrisby** [comment]
For the .NET API; being able to access the raw samples from each client would be very useful (not just forcing stuff to the default audio output device)

Is there a rough ETA on the .NET implementation?

**Comment by mariusu-msft** [comment]
@pfresnay Calling SDK for Windows will be usable from UWP for voice & video. Regarding the full feature set, we are aiming parity with iOS and Android at this time.

**Comment by mariusu-msft** [comment]
@AdamFrisby do you mind giving us more details regarding your scenario? You referenced output devices, would you like access to the raw audio samples to build a custom audio output sink?

Currently raw access to audio samples is not planned, at API level you will have ability to switch between all OS audio output devices.

Would you mind emailing the team at acsfeedback@microsoft.com? @RinaRish and myself would love hear more about your scenarios.

**Comment by legistek** [comment]
I can't speak for @AdamFrisby but having access to the raw samples in the .NET platform could enable us to record too. See https://github.com/Azure/Communication/issues/23

**Comment by AdamFrisby** [comment]
Sure - will do. Our use case is 3D interactive worlds (running inside Unity3D) -- so having access to the samples is essential to spatialise the stream.

**Comment by AdamFrisby** [comment]
Hi - that email address bounced with a "Not in organization" failure message.

This is what I sent;
========================================
We run a Virtual World platform - think VR/3D environments; we've been working with a number of providers for voice/video services and they've all had some degree of reliability issues that we want to replace with a more robust solution.

One of the requirements for us is a .NET SDK, preferably cross platform (we support most platforms), but one of the more subtle requirements is we want access to the raw audio (and video) samples on a per-participant basis; we use this to spatialise the stream (i.e. have 3D audio to match the 3D world).

As a preference; I'd like to just have some kind of buffer I can access through Marshal.Copy/etc containing Samples - and a regular -sync/blocking- callback which notifies of new samples to collect. We'd copy those and handle injecting them into Unity3D's audio buffers ourselves.

The other requirement would be the number of participants within a single channel - we need to support at least 50, preferably up to 200; although most of those users will be passive listeners for the majority of the time.
========================================

**Comment by mariusu-msft** [comment]
Thanks @AdamFrisby. We got the email, @RinaRish and myself will reach out.

**Comment by sipsorcery** [comment]
Given Unity came up it's worth noting that a not dissimilar effort to this API is going on at [Unity WebRTC](https://github.com/Unity-Technologies/com.unity.webrtc). And similar to the requests above I'm also trying to [get access to the raw video samples from .NET](https://github.com/Unity-Technologies/com.unity.webrtc/pull/217).

There are quite a few separate substantive efforts all working on some form of real-time communications for or with .NET. As well as this repo there are:

 - Microsoft's [MixedReality-WebRTC](https://github.com/microsoft/MixedReality-WebRTC),
 - Microsoft's [WinRTC](https://github.com/microsoft/winrtc),
 - Microsoft's [Graph Communications API](https://github.com/microsoftgraph/microsoft-graph-comms-samples). The Graph Communications API may be related to this repo, I'm not sure? I know it's extremely unwieldy to use to place calls to/from Teams even though the underlying Skype stuff is using WebRTC. And it also seems [near-death](https://github.com/microsoftgraph/microsoft-graph-comms-samples/issues/272).
 - Unity's [WebRTC](https://github.com/Unity-Technologies/com.unity.webrtc) plugin (mentioned above),
 - Numerous wrappers for `libwebrtc`.

Perhaps there's a way to get engagement in the Microsoft hierarchy to provide some direction before it's too late and we are left with 10 different ways of using WebRTC from .NET. That will really suck. Even if it was just an interface like `Microsoft.Extensions.Logging.Abstractions` that all these efforts adhered to.

**Comment by ProbablePrime** [comment]
I'm merging this with #72 so we're closing this one.
