### ISSUE TITLE
[iOS AzureCommunicationCalling 1.0.1]deviceManager could have empty camera list

### ISSUE THREAD

**Issue by AmyL219** [Azure/Communication#375]
**Describe the bug**
When we try to reach the device manager's camera list after we create the callClient and device manager but before create callAgent, the camera list could be empty randomly

**To Reproduce**
Steps to reproduce the behaviour:
1. create callClient and device manager
2. get the camera list by `deviceManager.cameras`
3. the list could be empty randomly

**Expected behaviour**
The camera list should return empty list of available camera

**Screenshots**

![Screen Shot 2021-09-14 at 1 50 06 PM](https://user-images.githubusercontent.com/75647512/133334903-34bfb345-3fc3-4d37-80a0-0a0a66828ed0.png)

**Logs**
[cameraListEmpty.zip](https://github.com/Azure/Communication/files/7165119/cameraListEmpty.zip)

**Comment by AmyL219** [comment]
https://skype.visualstudio.com/SPOOL/_sprints/taskboard/ACS%20Mobile%20UI/SPOOL/CY2021-Q3/Sprint%2045%20(Ends%20September%2019)?workitem=2582396

**Comment by mariusu-msft** [comment]
At this time we recommend using a coding pattern like such:
```pseudocode
instance = CallClient()
deviceManager = callClient.getDeviceManager()
deviceManager.addOnCamerasUpdatedListener(<devicesUpdatedListener>)
cameras = deviceManager.getCameras()
// may return 0 cameras. If 0 cameras then the camerasUpdated will be called.
```

We are looking into options for improving developer experience here. Closing this ticket as by-design.
