### ISSUE TITLE
Will Xamarin (Forms/iOS/Android be supported

### ISSUE THREAD

**Issue by croninr** [Azure/Communication#38]
Will there be Xamarin bindings for the existing Android / iOS SDK, or ideally will there be a Xamarin Forms SDK in the near future?

Thanks

**Comment by tompi** [comment]
@croninr I have bindings for the ios SDK, and a sample forms app. Let me know if you want to cooperate(could need help on the android bindings!) and Ill give you access to the repo

**Comment by croninr** [comment]
Hi Thomas,

I’d be happy to help, but I’m afraid I’m not overly experienced at creating bindings for native libraries.  I’ve done it a bit on iOS in the past but never needed to on Android.

I might be of more help testing the bindings on both platforms if that’s any use?


Thanks,
Richard

**Comment by tompi** [comment]
That would be great also, added you now.

P.S. Im not affiliated with Microsoft, just doing this for my organization, so I cant promise you support :)

**Comment by raosanat** [comment]
@tompi if you don't mind giving me access to the bindings for iOS ? Currently we dont have plans to support Xamarin as we first want to provide support for the native platforms first.

**Comment by tompi** [comment]
@raosanat added you now. Will try to get android up and running and cleanup the shared api the next few days if I get the time. This is all published now, so it shouldnt be a problem to bundle this as a nuget, right? (makes it much easier for build server and other ppl...)

**Comment by bigbbri** [comment]
Hi @tompi,  I'd like to see what you have and I think I can help.  I have a video conferencing app using (Vidyo.io - which sucks but it's a Xamarin SDK).  I want to moved away from it immediately so I was looking for an alternative.  My team can help with the Android bindings.  Can you grant access please and we'll take a look and we can talk once we see what you have and what is needed?
Thanks,
Brian

**Comment by tompi** [comment]
@bigbbri Added you now. I uploaded android bindings, they compile and run, but missing some jackson lib runtime. I probably cant look at it until next week, let me know if you figure it out. ios seems to work

**Comment by bigbbri** [comment]
@tompi  we are running behind on our work with some production bugs we have to get settled for another customer's go live and suddenly Google Play Store has slowed WAY down on their approvals and internal releases...  this is delaying us but this week we will be creating a ACS prototype on the web and I'm hoping by this Friday to talk with the mobile team and assign someone the mobile work.   My personal email is Brian@Ameliom.com if you'd like to talk via email instead of the public forum. :) 
Thank you again!
Brian

**Comment by tophpalmer** [comment]
hey @croninr and @bigbbri , I think you've started a healthy dialogue offline, so I'm closing this issue for now. There is a card on our roadmap for official support of Xamarin but it's not scheduled at this time. Thank you for the feedback!

@tompi  thank you as well for building on ACS and helping customers!
