### ISSUE TITLE
Must use 'unsafe-eval' for CSP policy when using JS SDK

### ISSUE THREAD

**Issue by jstclair** [Azure/Communication#384]
**Describe the bug**
Using the communication SDK (@azure/communication-calling: "1.2.0-beta.1") requires allowing `script-src: unsafe-eval` for a CSP policy. 

**To Reproduce**
1. Add communication SDK to project
2. Configure CSP script source policy (or default policy) to: `script-src: 'self'`
3. See error in console:

`Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'". `

The report originates in the `communication-calling/dist/sdk.bundle.js`, lines 112, 85, & 139. Example code is `Function("return this")`

**Expected behavior**
Should be possible to use CSP to lock down our site to not require 'unsafe-eval'

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
 N/A

**Additional context**

**Logs**

**Comment by akania** [comment]
Hi @jstclair , thank you for reporting, we'll look into the options how to solve this issue
#2595825 ADO created

**Comment by fizampou** [comment]
@jstclair 

We don't load any external scripts and the SDK shall be hosted on the same place you load the rest of your scripts. 

I did setup a small NodeJS server to test the behavior and i have setup the CSP like bellow

`javascript
app.use((req, res, next) => {
    res.setHeader(
      'Content-Security-Policy',
      "default-src 'self'; img-src 'self'; script-src 'self'; frame-src 'self'"
    );
    next();
  });
`

and SDK loads as expected. Can you check you CSP policies again and make sure the above?

**Comment by jstclair** [comment]
Ok but my original issue didn’t have anything to do with ‘load-*’; the title is ‘unsafe-eval’. The problem is that we have to make an exception for this library to enable this, which permits eval for any other loaded script.

**Comment by fizampou** [comment]
That's my point, you shall not need 'unsafe-eval' check the snippet i posted above. I'm not getting any errors on my sample when using 'self' on script-src.

**Comment by fizampou** [comment]
reopen if it's still an issue.
