### ISSUE TITLE
Is it possible to host the iOS SDK on cocoapod as well?

### ISSUE THREAD

**Issue by terrychen1122** [Azure/Communication#39]
as the title suggested

**Comment by raosanat** [comment]
Hi @terrychen1122 We do plan to support Swift Package manager soon and will consider adding CocoaPods support in the future if many customers are still asking for CocoaPods support after we have provided the support for Swift PM.

**Comment by mariusu-msft** [comment]
Adding @bsiegel and @tjprescott

**Comment by raosanat** [comment]
Hi @terrychen1122 We have some initial support for cocoa pods if you want to try it out. The specs aren't published to trunk yet but we will be doing for the next release of ACS Calling SDK. Following is the example podfile you can use for now

```
platform :ios, '13.0'
use_frameworks!

source 'https://github.com/Azure/azure-sdk-for-ios.git'

target 'ACSCallingTestApp' do
  pod 'AzureCommunicationCalling', :podspec => 'https://raw.githubusercontent.com/Azure/azure-sdk-for-ios/master/AzureCommunicationCalling.podspec'
  pod 'AzureCommunication', :git => 'https://github.com/Azure/azure-sdk-for-ios.git', :branch => "master"
  pod 'AzureCore', :git => 'https://github.com/Azure/azure-sdk-for-ios.git', :branch => "master"
end
```

**Comment by terrychen1122** [comment]
That's great. Since our side replies to the published specs on Cocoapods, I would wait until that then. Do you have an estimate on when this will be done?

**Comment by ProbablePrime** [comment]
@raosanat Do you have an answer to Terry's question above? thank you.

**Comment by mariusu-msft** [comment]
Closing. Support for Cocoapods has been released and libraries can be downloaded via Cocoapods
