### ISSUE TITLE
No video/audio feed while trying to join/start a group call

### ISSUE THREAD

**Issue by bbesase** [Azure/Communication#396]
**Describe the bug**
I'm attempting to create a group call: 

`
let callAgent = await callClient.createCallAgent(tokenCredential, { displayName: name});
let callAfterSetup = await callAgent.join({groupId}, callOptions);
`

I don't get any errors or anything when creating the group call. However, when other clients attempt to join, there is no video/audio feed after trying to join the same group call with the same group ID.

When I'm trying to listen to the `callsUpdated` event, it never reaches the code so I can never reach this code:

``` callAgent.on('callsUpdated', (e: { added: Call[]; removed: Call[] }): void => {
      e.added.forEach((addedCall) => {
        addedCall.on('remoteParticipantsUpdated', (remoteParticipants): void => {
          console.log('remote participants', remoteParticipants)
          remoteParticipants.added.forEach(participant => {
            subscribeToParticipantVideoStreams(participant);
          })
        });

        addedCall.remoteParticipants.forEach(participant => {
          subscribeToParticipantVideoStreams(participant);
        });

      });
    });
```

**Expected behavior**
First person to try and start the meeting should be able to create the group call, and every subsequent person would be able to join that group call as long as the groupId was the same

**Desktop (please complete the following information):**
 - OS: Mac/Windows
 - Browser Edge, Chrome

**Comment by mariusu-msft** [comment]
@bbesase when you use `callAgent.Join()` you should use the returned call object to listen to any events needed.

For example

```js
let call = await callAgent.join({groupId}, callOptions);
call.on('stateChanged', async () => {
//Handle Connected State

//Add Remote Participants collection listeners
//Check Remote Participants collection
});
```

**Comment by mariusu-msft** [comment]
You can check the tutorial sample which includes some in-line code snippets https://github.com/Azure-Samples/communication-services-web-calling-tutorial/

**Comment by bbesase** [comment]
@mariusu-msft thanks for you quick reply... so we listen to the actual `call` rather than the `callAgent` to get the remote particpants that are added ?

Is there a place where I can see all of the different events to listen to for the `call.on()`?

**Comment by mariusu-msft** [comment]
All events should be listed here: https://docs.microsoft.com/en-us/javascript/api/azure-communication-services/@azure/communication-calling/call?view=azure-communication-services-js

And you can find more information about how to use the library here: https://docs.microsoft.com/en-us/azure/communication-services/how-tos/calling-sdk/events?pivots=platform-web

Definitely suggest check checking the tutorial sample as one point of reference.

**Comment by mariusu-msft** [comment]
`so we listen to the actual call rather than the callAgent to get the remote particpants that are added ?`

Correct - the call object gives you information about the current state of the call, including participants.

**Comment by bbesase** [comment]
@mariusu-msft Yeah, ive been following some examples that I've found here and there. We are using this mostly for our project currently: https://www.npmjs.com/package/@azure/communication-calling

I will look through the documentation you have provided and see if I can get further. Thanks!

**Comment by bbesase** [comment]
@mariusu-msft even in that link you sent they are also listening for events on the callAgent:

```
callAgent.on('callsUpdated', e => {
    // New Call object is added to callAgent.calls collection
    e.added.forEach(call => {
        call.remoteParticipants.forEach(remoteParticipant => {
            subscribeToRemoteParticipant(remoteParticipant);
        })
        call.on('remoteParticipantsUpdated', e => {
            e.added.forEach(remoteParticipant => {
                subscribeToRemoteParticipant(remoteParticipant)
            });
            e.removed.forEach(remoteParticipant => {
                console.log('Remote participant removed from the call.');
            })
        });
    })
})`


I just tried locally switching it to be listening on the `call` rather than `callAgent` but. no luck, still running into the same issue, it just never goes into the call events :(

**Comment by bbesase** [comment]
@mariusu-msft  another odd thing, is if I do a workflow like:

1. Client A starts group call
2. Client B attempt to join the call
3. Nothing happens
4. Client B leaves, and re-joins
5. It works (like 40% of the time)

**Comment by fizampou** [comment]
reopen if this is still an issue.
