### ISSUE TITLE
[Android] Calling SDK - Upon re-entering the conference , I can see multiple instances of my previous one

### ISSUE THREAD

**Issue by bogdanmunteanu** [Azure/Communication#403]
**Describe the bug**
When I force close the app , the conference closes (there is no leftover stream remaining). However , when I try to enter again in the same room , there is another participant and my session from last time has remained as a frozen frame.

**To Reproduce**
1. Create a conference in Teams on Windows
2. Join with Teams SDK 1.2.1-beta1
3. Force close the Android app
4. Rejoin the same conference 
5. Notice that in the conference is present another participant , which is a freeze frame from your last session

**Expected behavior**
Upon exiting the conference , there should be no remains of my presence there.

**Screenshots**
![image_2021_10_20T14_32_41_888Z](https://user-images.githubusercontent.com/8288565/138302752-62c536ca-be31-4a31-8736-6ebecbe81627.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 1.4.00.26376

**Smartphone (please complete the following information):**
 - Device: Huawei P30 Pro
 - OS: Android 10
 - Version : Teams SDK 1.2.1-beta1

**Comment by mariusu-msft** [comment]
Hi,

This is currently expected. As the stack tries to determine if the endpoint has dropped, there is a 2-3 minute timeout until you may see stale participants.

We are looking for long-term options to improve developer experience here, but right now the experience is expected.

To alleviate some of these side effects - please check if you can dispose of the stack upon application exit, so the server does not go into media timeout detection.

Thanks,
Marius

**Comment by bogdanmunteanu** [comment]
Tested and fixed with Calling SDK 1.3.0-beta1 .Closed.
