### ISSUE TITLE
Cannot instantiate CallClient in a Chrome Browser Extension

### ISSUE THREAD

**Issue by deleolajide** [Azure/Communication#404]
**Describe the bug**
When I run this code

```
	const tokenCredential = new ACS.AzureCommunicationTokenCredential(token);
	const callClient = new ACS.CallClient();
```

I get the following error:

![image](https://user-images.githubusercontent.com/110731/138564878-a703f92e-d3c0-407b-bad8-0cc48fe067d1.png)

A quick look at the JavaScript code reveals that it is checking for protocol "https:" and host name "localhost". Anything else is being flagged with this error. 

**To Reproduce**
Create a browser extension with Chrome or Edge and try and run similar code as above

**Expected behavior**
I expect to run my ACS app in a browser extension just like a browser tab

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 95

**Comment by mariusu-msft** [comment]
Thanks for your report @deleolajide.

We're looking at this and will reply soon.

**Comment by akania** [comment]
Hi @deleolajide , currently we're not supporting running ACS within Chrome ( or any other browser ) extension, can you please describe your use case ?

**Comment by deleolajide** [comment]
>can you please describe your use case ?

https://comitfs.github.io/openlink-v2.js/xep/xep-xxx-openlink_15-02.xml
https://www.comitfs.com/communication/#apis

We are are currently implementing the CAS Openlink specification for MS Teams and in order for existing Financial applications that use CAS to work seamlessly with MS Teams, we need to install a resident application on the desktop with a simple and efficient deployment model. A web browser extensions  enables us to achieve that objective 👍 

>currently we're not supporting running ACS within Chrome ( or any other browser ) extension

I can confirm it works very nicely. It only needs you to remove the block. You are already supporting MSAL in browser extensions and WebRTC is proven in browser extensions. Most of the above specification is already implemented and working fine in both Edge and Chrome extensions using ACS endpoints with MS Teams identities.

**Comment by ProbablePrime** [comment]
This has been migrated to Azure Ideas: https://feedback.azure.com/d365community/idea/fd957221-1053-ec11-8f8e-000d3a987052
