### ISSUE TITLE
[iOS] CallingSDK createCallAgent did not trigger completionHandler when an invalid acs token url is provided, leading to app not able to end a call

### ISSUE THREAD

**Issue by kevinyulu** [Azure/Communication#410]
**Describe the bug**
When a user provide an invalid acs token url, this user cannot leave the call after tapping on the leave call button in Composite app.

iOS bug for reference: https://skype.visualstudio.com/SPOOL/_workitems/edit/2628098

**To Reproduce** (in Composite iOS App) 
1. Launch the app, enter an invalid acs token url
2. fill the other fields, tap start experience 
3. Entering the setup screen, tap Join call 
4. in calling screen, tap on hang up button, 
5. tap the leave call in the overlay screen 

**Expected behavior**
User should be able to leave a call

Cause: the `createCallAgent(userCredential :)` function did not trigger the `completionHandler`

```
private func setupCallAgent() -> Future<Void, Error> {
        Future { promise in
            let options = CallAgentOptions()
            options.displayName = self.callConfiguration.displayName

            self.callClient?.createCallAgent(userCredential: self.callConfiguration.communicationTokenCredential,
                                             options: options) { [weak self] (agent, error) in
                guard let self = self else {
                    return promise(.failure(CompositeError.invalidSDKWrapper))
                }

                if let error = error {
                    self.logger.error( "It was not possible to create a call agent.")
                    return promise(.failure(error))
                }

                self.logger.debug("Call agent successfully created.")
                self.callAgent = agent
                return promise(.success(()))
            }
        }
    }
```

This code snippet shows the initialized `communicationTokenRefreshOptions` with the following `tokenRefresher` from the iOS Composite app. Please note that in the callback function of `dataTask(with: urlRequest)`, the completionHandler is not called when there is an error. If iOS Composite app calls in `completionHandler(nil, error)` when the error is not nil, the iOS Composite app would crash with an ACSException later on when a user starts a call.  

``` 
let communicationTokenRefreshOptions = CommunicationTokenRefreshOptions(initialToken: nil, refreshProactively: true, tokenRefresher: getCommunicationToken(completionHandler:))
let communicationTokenCredential = try! CommunicationTokenCredential(withOptions: communicationTokenRefreshOptions)

func getCommunicationToken(completionHandler: @escaping (String?, Error?) -> Void) {
        struct TokenResponse: Decodable {
            let token: String
        }

        if let url = URL(string: preferences.acsTokenUrl) {
            var urlRequest = URLRequest(url: url, cachePolicy: .useProtocolCachePolicy, timeoutInterval: 10)
            urlRequest.httpMethod = "GET"

            URLSession.shared.dataTask(with: urlRequest) { (data, _, error) in
                if let error = error {
                    print(error)
                } else if let data = data {
                    do {
                        let res = try JSONDecoder().decode(TokenResponse.self, from: data)
                        print(res.token)
                        completionHandler(res.token, nil)
                    } catch let error {
                        print(error)
                    }
                }
            }.resume()
        }
    }

```

**Screenshots**
https://user-images.githubusercontent.com/90668345/139750281-18b1e525-8089-45aa-bd26-7956697d32ae.mov

**Desktop (please complete the following information):**
 - OS:  n/a
 - Browser: n/a
 - Version:n/a

**Smartphone (please complete the following information):**
 - Device: iPhone XR and etc
 - OS: iOS14.4
 - Browser: n/a
 - Version: n/a

**Additional context**

**Logs**
<br/>Please attach the logs and share the callId. Instructions could be found [here](https://docs.microsoft.com/en-us/azure/communication-services/concepts/troubleshooting-info?tabs=csharp%2Cjavascript%2Cdotnet)

**Comment by JoshuaLai** [comment]
https://skype.visualstudio.com/SPOOL/_workitems/edit/2635377

**Comment by mkambale** [comment]
@kevinyulu Now with AzureCommunicationCalling-2.0.0, there is a proper error for this on join() call with invalid url. You get this error - **Error Domain=ACSCallingShared Code=93 "Invalid meeting link provided." UserInfo={NSLocalizedDescription=Invalid meeting link provided.}**
