### ISSUE TITLE
Android 12 video artifacts on Chromium browsers

### ISSUE THREAD

**Issue by andreas-niemoeller-qhr** [Azure/Communication#412]
**Describe the bug**
In a call application when using JavaScript SDK in Chrome on Android 12 sender and receiver video streams look normal. The RemoteVideoStream received from js sdk on Android 12 Chrome is corrupted. The colors match the source but it appears to not have been reconstructed using the right height/width of the source.
This was tested using the latest communication-calling v1.2.3-beta.1

**To Reproduce**
Have a video call between an Android 12 Chrome (94) and another device (tested on Windows 10 Chrome 95)

**Expected behavior**
Video should be the same as sent

**Screenshots**
![acs_video_issue](https://user-images.githubusercontent.com/52715014/139870797-1753baf1-f2b0-4740-b2a6-c99b3e838b62.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 
 - Version 95.0.4638.54

**Smartphone (please complete the following information):**
 - Device: Pixel 4a
 - OS: Android 12  (Build SP1A.210812.015)
 - Browser Chrome
 - Version 94.0.4606.85

**Additional context**
Video call did work before the Android 12 upgrade

**Logs**

**Comment by andreas-niemoeller-qhr** [comment]
@mychalhackman

**Comment by fizampou** [comment]
Hello @andreas,

Thanks for reporting the problem. It's a known issue that was introduced with the release of Android 12. You can find more info [here](https://docs.microsoft.com/en-us/azure/communication-services/concepts/known-issues).

this one is the tracking item on [Chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=1237677).

**Comment by fizampou** [comment]
This has been fixed on the latest released version.

More info [here](https://github.com/Azure/Communication/blob/master/releasenotes/acs-javascript-calling-library-release-notes.md#v132-beta1-2021-12-9)

Either 1.3.2 [beta](https://www.npmjs.com/package/@azure/communication-calling/v/1.3.2-beta.1) or [stable](https://www.npmjs.com/package/@azure/communication-calling/v/1.3.2)
