### ISSUE TITLE
iOS 15.1 issues when having video on group calls or Microsoft Teams meetings on web

### ISSUE THREAD

**Issue by fizampou** [Azure/Communication#413]
Greetings,

We have found a big bug introduced by Apple in iOS 15.1 when using Safari browser for ACS video calls that will impact you. I wanted to update you with this issue.

### Issue Description

When joining an ACS calls or a joining a Teams meeting using ACS on iOS 15.1 on any browser with video turn on – this will cause Safari browser to crash.

### Details

This is a [known bug on iOS 15.1 Safari](https://bugs.webkit.org/show_bug.cgi?id=231505) that was introduced with the release of iOS 15.1. We expect this issue to be fixed with the release if iOS 15.2. Currently the only known work around is to not turn off video when using ACS on iOS 15.1 Safari.

### Versions

iOS 15.1 and any ACS Web SDK version

### Mitigations

With version [1.3.1-beta.1](https://www.npmjs.com/package/@azure/communication-calling/v/1.3.1-beta.1) we were able to mitigate that issue, now users on iOS15.1 will be able to join calls with video on.

That fix surfaced two new issues with Safari and iOS 15.1:

* Wrong video orientation on the receiver's end. Mitigation: Switch device orientation to horizontal.
* Going to background will refresh your call. Mitigation: Stop video before going to background.

**Comment by Discodir** [comment]
Hi @fizampou.
We have exactly the same issue.
{ [WEB Azure.Communication.Common] Calling - Safari endless redirect loop to same groupId }

**Comment by fizampou** [comment]
This has been fixed on the latest released version.

More info [here](https://github.com/Azure/Communication/blob/master/releasenotes/acs-javascript-calling-library-release-notes.md#v132-beta1-2021-12-9)

Either 1.3.2 [beta](https://www.npmjs.com/package/@azure/communication-calling/v/1.3.2-beta.1) or [stable](https://www.npmjs.com/package/@azure/communication-calling/v/1.3.2)
