### ISSUE TITLE
does  Azure/communication support  react native or flutter ?

### ISSUE THREAD

**Issue by 10mayje** [Azure/Communication#415]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Logs**
<br/>Please attach the logs and share the callId. Instructions could be found [here](https://docs.microsoft.com/en-us/azure/communication-services/concepts/troubleshooting-info?tabs=csharp%2Cjavascript%2Cdotnet)

**Comment by angiurgiu** [comment]
It is partially supported for Chat, @CHILIU-MSFT will help you with instructions for usage

Calling does not support React Native / Flutter at this time

**Comment by CHILIU-MSFT** [comment]
The following steps will be required to run Azure Communication Service Chat SDK for JavaScript on React Native after initializing your React Native project.

1. Install node-libs-react-native
npm install node-libs-react-native --save-dev

2. Install stream-browserify
npm install stream-browserify --save-dev

3. Install react-native-get-random-values
npm install react-native-get-random-values --save-dev

4. Update metro.config.js to use React Native compatible Node Core modules
module.exports = {
    // ...
    resolver: {
        extraNodeModules: {
            ...require('stream-browserify'),
            ...require('node-libs-react-native'),
            net: require.resolve('node-libs-react-native/mock/net'),
            tls: require.resolve('node-libs-react-native/mock/tls')
    }
};

5. Add following import on top of your entry point file
import 'node-libs-react-native/globals';
import 'react-native-get-random-values';

6. Install Azure Communication Service packages
npm install @azure/communication-common@1.1.0 --save
npm install @azure/communication-signaling@1.0.0-beta.8 --save
npm install @azure/communication-chat@1.1.0-beta.2 --save

Note: Currently, we've verified React Native is only supported in @azure/communication-chat version 1.0.1 and 1.1.0-beta.2. Besides, there may be some extra issue for iOS. Please let us know it this setup does not work for you. @10mayje  Thanks!

**Comment by eamreyesNeudesic** [comment]
@10mayje, I'm working on a Flutter project where we've been able to use native Azure/Communication libraries(Droid, iOS, Web) via Flutter method channels.

**Comment by angiurgiu** [comment]
Hi @10mayje, hope your question has been answered. If you face any problems with the suggested solution, please feel free to ask more questions.
