### ISSUE TITLE
Outgoing screen share in Android / iOS browser

### ISSUE THREAD

**Issue by Kalyan492** [Azure/Communication#416]
Hi,

   Is there outgoing screen share support in mobile browsers? I am using call package to join Teams meeting. Screen share is working fine on desktop browser. But in Android mobile outgoing screen share is not working. If this feature is not supported as of now, is there any roadmap to add it?

Thanks & Regards,
Kalyan Mannam.

**Comment by mariusu-msft** [comment]
Hi @Kalyan492 - this is not supported by the browser ecosystem on mobile devices.

You can check the browser compatibility here https://developer.mozilla.org/en-US/docs/Web/API/Screen_Capture_API to see which browsers support the APIs required for this feature to operate.

Thanks,
Marius
