### ISSUE TITLE
Unable to deploy Communication Service with resource name starting with `comm`

### ISSUE THREAD

**Issue by williamzhao87** [Azure/Communication#42]
**Describe the bug**
Deploying a Communication Service with resource name starting with `comm` results in the following error:
```
{
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
  "details": [
    {
      "code": "BadRequest",
      "message": "{\r\n  \"error\": {\r\n    \"code\": \"HostNamePrefixTaken\",\r\n    \"message\": \"Specified host name prefix is not available\"\r\n  }\r\n}"
    }
  ]
}
```

Perhaps either the uniqueness of the Resource Name is not being correctly validated, or `comm` is a reserved keyword and should not be allowed to be used.

**To Reproduce**
1. Add a new Communication Service and under `Resource Name` enter `comm`, `communicate` or `communication`, and click Create

**Expected behavior**
1. A new Communication Service to be deployed with specified name.  Or if such a name should not be allowed, the user should be warned prior to initiating deployment.

**Screenshots**
![image](https://user-images.githubusercontent.com/11931973/94829186-40ce1900-03d8-11eb-85bc-0ab00c429bb0.png)

**Comment by manoskow** [comment]
Hi @williamzhao87 , thank you for filing this issue! 

The resource could not be created because there are already resources out there named 'com', 'comm', and 'communication'. 

I agree with you this should be validated sooner in the creation process and appreciate the feedback! I am filing a bug on our side to track this issue and work on a fix.

**Comment by tophpalmer** [comment]
AB#2309517

**Comment by tophpalmer** [comment]
We've introduced validation earlier in the creation process, thank you @williamzhao87 for the feedback!
