### ISSUE TITLE
[Android][Chat -1.1.0-beta.3] I cannot see images when host attaches them to the chat

### ISSUE THREAD

**Issue by bogdanmunteanu** [Azure/Communication#425]
**Describe the bug**
When the host sends an image or any other payload (besides text) , the paylod arriving to the mobile device is empty

**To Reproduce**
1. Host a Teams conference
2. Join with an Android device with Calling 1.3.0-beta.1 and Chat-1.1.0-beta.3
3. Ask the host to attach some images

**Expected behavior**
I should receive the payload in the form of a link to display it on the mobile device

**Screenshots**
<img width="934" alt="Screenshot 2021-11-18 at 16 29 30" src="https://user-images.githubusercontent.com/8288565/142458241-68bb5f04-8a71-4158-a25d-cdb4fd205903.png">

**Smartphone (please complete the following information):**
Device:Huawei P30 Pro
OS: Android 10
Teams SDK for Android : 1.3.0-beta1
Chat SDK for Android : 1.1.0-beta1

**Comment by ashwinder** [comment]
Hi @bogdanmunteanu, when a Communication Services user joins a Teams meetings, they might not have access to all the features that Teams users have. For example, features like raise hand, attaching a file or image are not supported for Communication Services users. 
Teams users can send plain text or rich text messages to Communication Services users. In your use case, the Teams host can share a link to an image as message. However, attaching an image is not supported.
