### ISSUE TITLE
Xamarin / MAUI NuGet package for Azure Communication Services

### ISSUE THREAD

**Issue by aodegov** [Azure/Communication#426]
## Summary
Xamarin / MAUI  NuGet package for Azure Communication Services

## Changes
According to discussion there: [Xamarin.Forms/issues/14906](https://github.com/xamarin/Xamarin.Forms/issues/14906):
We'd like to ask you about the opportunity to use Azure Communication Services   
(Video Calls, Group Video calls, Conferences, Recordings, Voice calls) with Xamarin / MAUI
with / through the appropriate NuGet package for Xamarin / MAUI.

## Intended Use Case
Nowadays a lot of community members strive to build mobile apps on MS stack,
such as Xamarin / MAUI and communicate through the Azure Communication Services.
Unfortunately, there is no such option as a NuGet package from MS and as well, we don't see any tutorials or docs about this.

___
Many thanks

**Comment by raosanat** [comment]
@LaithRodan Can you please update here ? Can we somehow prioritize this in the future ?

**Comment by raosanat** [comment]
@aodegov Did you check this project ?  https://github.com/Laerdal/Xamarin.AzureCommunicationCalling , while we work on officially providing support for Xamarin maybe this might work for you ?

**Comment by ichivers** [comment]
I managed to get a React Native app working with the Javascript SDK, thanks to this post https://issueexplorer.com/issue/Azure/Communication/415.  I created a project here https://github.com/ichivers/ReactNativeApp but have had to shelve it due to other work commitments.

**Comment by aodegov** [comment]
@raosanat and @ichivers, this issue is not about the JS SDK, React Native or even [this ](https://github.com/Laerdal/Xamarin.AzureCommunicationCalling) **non MS** solution without the support from MS side.
This issue is about Xamarin / MAUI mobile apps NuGet package (or embedded functionality as a library) to work with Azure Communication Services.
We asking about this here because it's too significant for us to have such solution from MS.
Since we're going to create production app on this stack with Xamarin/MAUI NuGet from MS as a LTS version to work with ACS. 
Since I believe that no one can guarantee the [this ](https://github.com/Laerdal/Xamarin.AzureCommunicationCalling) quite good solution will be supported along next year +. 
But unfortunately there is no any activity from MS side towards this direction at least along the last year from now.
There were several issues created ~1 year ago. Like these: [38](https://github.com/Azure/Communication/issues/38), [190](https://github.com/Azure/Communication/issues/190) and this one [279](https://github.com/Azure/Communication/issues/279).
But still no progress.
That's why this issue was created.

Thanks

**Comment by ProbablePrime** [comment]
This has been migrated to Azure Ideas: https://feedback.azure.com/d365community/idea/4c3c83f6-8948-ec11-a819-0022484bf651

**Comment by aodegov** [comment]
@ProbablePrime , sorry but [this is](https://feedback.azure.com/d365community/idea/4c3c83f6-8948-ec11-a819-0022484bf651) my own post into ideas. That's why it's not migrated anywhere as you mentioned.  
You've just referenced me to my self :) 
Could you please reopen this issue to let MS Team eventually work on it.
Since community waits on such solution from MS more than a year.

Thanks.

**Comment by ProbablePrime** [comment]
@aodegov I can't sorry. 

We're not using GitHub issues for feature requests or work tracking management on this repository anymore.

**Comment by aodegov** [comment]
@ProbablePrime thanks for the reply.
Could you please advice, where is the appropriate place for features requests for Azure Communication Services?

**Comment by ProbablePrime** [comment]
@aodegov The ideas forum. https://github.com/Azure/Communication/issues/new/choose has some other links for other issue types.

Thank you

**Comment by aodegov** [comment]
Thanks, @ProbablePrime.
However, I posted issue as an idea there : https://feedback.azure.com/d365community/idea/4c3c83f6-8948-ec11-a819-0022484bf651 , already.
But it seems to me there is no any progress.
Is there an option to ask someone to take a look this, in order to move forward and start working on it eventually?
