### ISSUE TITLE
ACS able to call existing Microsoft teams user?

### ISSUE THREAD

**Issue by chenxing105** [Azure/Communication#43]
Hi, 
From the calling hero sample, as I understand, is browser starting the call, then others who want to join will access through the given url.
But is it possible that browser/iOS/android using ACS libraries will be able to start a call to sip address of MS Teams users?

**Comment by nmurav** [comment]
@chenxing105  not available now on the roadmap. What is the specific scenario you want to implement? Why would you call from ACS to a Teams SIP address?

**Comment by chenxing105** [comment]
Hi @nmurav 
For Sample scenario, A customer visits my page and needs help from customer support from companyA, then my web will start  videocall to companyA user who will get a call on Teams client desktop app.

**Comment by nmurav** [comment]
Thank, @chenxing105  but in this case to you want to call the UserA directly or have some bot that will be distributing calls between Teams users (let say User A and User B)?

**Comment by chenxing105** [comment]
@nmurav  call userA directly. Is that possible or in the roadmap? Thank you very much.

**Comment by ProbablePrime** [comment]
@nmurav Do you have an answer to the question above? Thank you

**Comment by ProbablePrime** [comment]
Hey @chenxing105 , we've recently released some documentation and information on our Teams Interop feature. This feature is currently in private preview but we have some information here: https://docs.microsoft.com/azure/communication-services/concepts/teams-interop

Including a form you can file to get access. Thank you
