### ISSUE TITLE
[BUG] Audio doesn't work after ongoing was meeting was interrupted through a phone call

### ISSUE THREAD

**Issue by tjprescott** [Azure/Communication#438]
@mkambale commented on [Fri Feb 04 2022](https://github.com/Azure/azure-sdk-for-ios/issues/1146)

**Describe the bug**
If user receives phone call during meeting, user keeps teams call on hold and receives phone call, after the phone call ends and user resumes the call, input and output audio doesn't work.

**To Reproduce**
1. User joins a scheduled meeting using url and token as a guest using his iPhone through my app XYZ.
2. Host joins using Teams app on his/her desktop.
3. Host admits guest.
4. User receives a phone call.
5. User keeps meeting on hold on app.
6. User accepts phone call and answers.
7. User ends phone call.
8. User returns to app XYZ and resumes Teams meeting call.
9. User cannot hear anything, host cannot hear user.

**Setup (please complete the following information):**
 - OS: [e.g. iOS] iOS 15.2
 - IDE : [e.g. IntelliJ]
 - Version of the Library used:    AzureCommunicationCalling - 2.0.0
                                                      AzureCommunicationCommon - 1.0.2

**Additional context**
didChangeSpeakingState() call back is received after the when host speaks, but user cannot hear anything.

Any suggestions appreceited.

Thanks,

---

@tjprescott commented on [Fri Feb 04 2022](https://github.com/Azure/azure-sdk-for-ios/issues/1146#issuecomment-1030167390)

@mariusu-msft for triage.

**Comment by mariusu-msft** [comment]
Hi,

@mkambale thanks for your report.

Just to be sure, this bug report is for the iOS SDK, and not JavaScript SDK running on Safari, right?

In your application, can you let us know if you are using CallKit at all?

Thanks,
Marius

**Comment by mkambale** [comment]
@mariusu-msft Thanks for the reply.
Yes it is for iOS SDK.
Yes I am using CallKit for observing incoming call status. (func callObserver(_ callObserver: CXCallObserver, callChanged call: CXCall) )

when receives the incoming call, app sets the current meetings call to "ObHold" and then changes to "Resume" when incoming phone call ends.

**Comment by raosanat** [comment]
We have fixed this and will be available in next beta release.

**Comment by mkambale** [comment]
@raosanat Thank you

**Comment by fizampou** [comment]
Please update to the latest SDK version.
That issue shall be fixed.
