### ISSUE TITLE
Does it support React Native?

### ISSUE THREAD

**Issue by sabrimev** [Azure/Communication#45]
I would like to use this on my React Native application. Anyone tried this before? Any suggestions?

**Comment by RinaRish** [comment]
Hi @sabrimev! We don't have React Native Support now. Something we are considering. What is the scenario for React Native?

**Comment by sabrimev** [comment]
Hi @RinaRish , need to add one-one, one-many, many-many video & voice calling feature to our enterprise application. Can I use Communication Services with WebRTC in the client side? IS that possible?

**Comment by likern** [comment]
> Hi @sabrimev! We don't have React Native Support now. Something we are considering. What is the scenario for React Native?

My user scenario is to build high-quality cross-platform chat application using React Native. Like Telegram or WhatsApp competitor.

Microsoft heavily is investing into React Native and supports own port for Windows and even MacOS.

React Native allows do not write platform-specific code if libs support it out of the box.

**Comment by likern** [comment]
Ideally I don't want to write and run backend neither. If Azure Communications Services could handle that scenario that would be ideal.

**Comment by chriswhilar** [comment]
Hey folks, yes we have client side javascript sdks for calling and chat which you should be able to use in your react native application. Please take a look at our Azure Communication Services docs to learn and understand how to use these sdks. We also have tutorials/sample applications which you can clone and run locally to try them out. 

No need for you to do anything with webrtc, you can just use our calling sdk so it will be easy and simple for you to integrate calling into your application

**Comment by RinaRish** [comment]
@likern @sabrimev are there still any questions?

**Comment by likern** [comment]
> @likern @sabrimev are there still any questions?

# - No, no questions yet

**Comment by meteorra** [comment]
@likern @sabrimev did you manage to make it work with react-native?
