### ISSUE TITLE
Web: Microphone & Camera device names do not appear after permissions granted until page refreshed

### ISSUE THREAD

**Issue by eliaspuurunen** [Azure/Communication#46]
**Describe the bug**
Device names do not appear on Android Chrome after calling DeviceManager.AskDevicePermission(), then enumerating the Microphone List.

**To Reproduce**
1. Await deviceManager.askDevicePermission(true, true)
2. Fetch list of microphones & cameras using .getMicrophoneList and getCameraList.
3. Camera names do not appear, Microphone names do not appear.

If the user reloads the page, device names appear when gML and gCL are called.

**Expected behavior**
Once device permissions are fetched, device names appear.

**Screenshots**
See screenshot attached for a console log of getMicrophoneList vs. webRTC navigator.mediaDevices.enumerateDevices.

Note that enumerateDevices is called **before** getMicrophoneList.

![image](https://user-images.githubusercontent.com/695294/94924604-d4aced00-048b-11eb-9d5a-e5c757fc2584.png)

**Smartphone (please complete the following information):**
 - Device: LG V-30 (LG-H933)
 - OS: Android 9 
 - Browser Chrome
 - Version 85.0.4183.127

**Comment by RinaRish** [comment]
Hi @eliaspuurunen ! Thanks for reporting, it's a bug on our side and we are working on it

**Comment by akania** [comment]
ADO#2481743

Issue has been fixed and will be published in upcoming release
