### ISSUE TITLE
[WEB] : rear camera local preview is rotating on the mobile device

### ISSUE THREAD

**Issue by Muthukumar230195** [Azure/Communication#473]
we are developing the virtual visit web app using azure communication calling web SDK. we also made the web app responsive to make it available on mobile devices. In the mobile device, if the user switches to the rear camera, then the stream preview is showing as mirrored and also rotating when the user rotates the device from portrait view to landscape view.

Code:
![image](https://user-images.githubusercontent.com/50482582/176669236-4b767bb8-d52f-436c-b97e-9cb68435fa69.png)
Issue No 1: preview rotation 
![Screenshot 2022-06-30 171759](https://user-images.githubusercontent.com/50482582/176670080-4d1c703a-1b67-440e-998b-371333d81bd2.jpg)

Issue No 2: preview mirrored
![Screenshot 2022-06-30 172641](https://user-images.githubusercontent.com/50482582/176671601-0df42610-ffac-45f6-9a94-c993a873bfd6.jpg)

Help us to resolve this issue, Any suggestions and comments are welcomed. 
Thanks in advance!!

**Comment by Muthukumar230195** [comment]
![image](https://user-images.githubusercontent.com/50482582/176833958-43c800bc-47ee-47ff-91eb-50076f118165.png)
If I use this option "isMirrored: true", then the rear camera view is working fine, but the front camera view is rotating when the user rotates the device from the portrait view to the landscape view without enabling the "auto-rotate" option.

**Comment by fizampou** [comment]
Please update to the latest SDK version.
That issue shall be fixed.
