### ISSUE TITLE
Cannot accept/reject a call once initial invitation is rejected by the same user in azure communication service (web sdk)

### ISSUE THREAD

**Issue by sgrmhrzn** [Azure/Communication#475]
We have a call system that is developed under the Microsoft Teams where we have a bot in our end which determines available user and invites that user. We are trying to implement azure communication service to handle the call actions from our web application. In our our system there is a feature where the call keeps searching for available user and re-routes the call even if it was rejected previously. On initial incoming request if user rejects the call it will work but if the same call is routed back to that user and when tries to accept or reject it then azure communication service throws an exceptions. Do we have any solutions for this scenario?
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/15918086/177022493-e6f350d3-d8f7-44d1-94bb-f2515fc43161.png)
![Screenshot 2022-07-03 081945](https://user-images.githubusercontent.com/15918086/177022498-95f2f928-0e23-4abf-a2bd-eb193bc7b65d.png)

**Comment by fizampou** [comment]
Hi @sgrmhrzn,

Calling SDK has the transfer feature for that exact use case. Try to refactor the code to use that,
