### ISSUE TITLE
Make Azure Communication Client Library Open Source

### ISSUE THREAD

**Issue by eliaspuurunen** [Azure/Communication#48]
**Is your feature request related to a problem? Please describe.**
At the moment, the Azure calling library/Javascript npm package is closed source (to my knowledge). Are there any plans to make this package open source?

**Comment by RinaRish** [comment]
Hi @eliaspuurunen! Thank you for the feedback, We have some components that we create to optimize the Audio and Video quality based on proprietary Microsoft technologies to ensure the highest quality.
What do we miss from your point of view by not offering the Open Source SDK?

**Comment by eliaspuurunen** [comment]
Hi @RinaRish. My request has more to do with bugs #47 and #46. We have workarounds for those issues but it would be nice if we could have applied them to the JavaScript library directly. Since the JS library is (probably) transpiled from TypeScript and (looks) obfuscated, it's pretty much impossible for us.

Another reason - the documentation right now is sparse. We had to deduce how to use some functionality through the provided samples, iOS/Android samples, and by attempting to prettify the JavaScript npm library. Again, being able to reference the npm library code would be helpful while the documentation is being built.

Summary: it would help devs figure out how the library works so we don't make bad assumptions. It would also help the community to suggest fixes in case bugs are discovered.

Thanks for being open to suggestions!

**Comment by akania** [comment]
Hi @eliaspuurunen , Can you please elaborate more about documentation being sparse?
1) is intellisense not providing enough details? method/param/property description are not detailed enough?
2) We have [API docs available here](https://docs.microsoft.com/en-us/javascript/api/azure-communication-services/@azure/communication-calling/?view=azure-communication-services-js) - these are essentially the same that intellisense uses
3) "figure out how the library works" - can you give us some hints what are the top things missing currently?

We'll be happy to improve all areas going forward, thanks for feedback!

**Comment by eliaspuurunen** [comment]
Hi @akania.

**Point 1 & 2** - Documentation Detail & intellisense  

I find Intellisense/docs don't provide quite enough detail.

A particular example I just ran into - the `CollectionUpdatedEvent` type.

https://docs.microsoft.com/en-us/javascript/api/azure-communication-services/@azure/communication-calling/collectionupdatedevent?view=azure-communication-services-js

It doesn't actually specify that for those types of event, an object of the form:

```
{
  added: T[],
  removed: T[]
}
```

Nor does it specify if/when added/removed is null/undefined.

The description for this type is:

> Event that a collection of objects has been updated

Based on usage in the sample app, prettifying the JS library, and reviewing other methods, I was able to figure this out.

Another example: the `localVideoStreamsUpdated` event in `Call`.

https://docs.microsoft.com/en-us/javascript/api/azure-communication-services/@azure/communication-calling/call?view=azure-communication-services-js#on--localvideostreamsupdated---collectionupdatedevent-localvideostream--

> callback fn that will be called when this collection will change, it will pass arrays of added and removed elements

Again, the listener is a `CollectionUpdatedEvent<T>`. Clicking the `CollectionUpdatedEvent<T>` links to the article on that type, but doesn't specify the format of the event args object.

**Point 3 - "Figure out how the library works."**

Apologies for being vague on this. I'll give a specific use case.

> A user must see the shared screens of remote users.

For `RemoteParticipant`, it seems their `videoStreams` property is an array that always has 2 elements - one stream for video, one stream for screen sharing. This appears to be the case even if they are not sharing either of them.

https://docs.microsoft.com/en-us/javascript/api/azure-communication-services/@azure/communication-calling/remoteparticipant?view=azure-communication-services-js

First - is that a valid assumption? I discovered this through trial and error. The specifics aren't reflected in the documentation. I'm personally the kind of person who likes to look at the code to see how the implementation works, especially if docs aren't available. So this may be an invalid assumption on my part. 

Specifically re `videoStreams` property - the documentation reads:

> Collection of video streams this participants has.

Is this active streams? Is this all potential streams the remote user may have? Is this property guaranteed to have elements? Are the elements in any particular order? I see a lot of ways I could interpret that description. It also makes it hard to determine if an issue I'm running into is "intended behavior" or "a bug." 

There are other areas where we've had to use trial and error to figure out how the library works. See issues #47 and #46. For instance, after we ask the user for permission to use camera/microphone, will the DeviceManager have a list of Cameras/Mics right away? Should we query that list using the onXChanged events on DeviceManager? When are those events guaranteed to fire?

Finally - we're happy to hop on a call and go through some code if that would help your team. 

Thank you!

**Comment by eliaspuurunen** [comment]
Update from our end: we have worked around a few of the above limitations re: video streams, audio streams, mixing, and effects. We're aware that many of these workarounds are using "undocumented" parts of the JS SDK to get access to audio/video streams. 

In our application, we are mixing multiple video streams together for recording collaborative calls.

IMO, if web SDK users had just a bit more access to the WebRTC-side of things (e.g. the video/audio streams) so we can support more advanced scenarios, that would be amazing (and probably negate most of the need for the JS library to be open source).

Thanks!

**Comment by akania** [comment]
Hi @eliaspuurunen 
First of all - your feedback is really appreciated, I admit that documentation doesn't have great number of details and so intellisense - we'll improve it.

Let me give you some hints & explanation meanwhile

1) regarding Point 1 & 2 
As you've already found our CollectionUpdatedEvent is fired when collection of elements (T) updates , meaning new elements are added or some elements are removed, in case there are no new elements are added, 'added' property will reference empty array, similarly for 'removed'. added/removed will always be an array, never undefined | null, so it's safe to interate over it

2) regarding point 3
a) remoteParticipant.videoStreams ( videoStreams: RemoteVideoStream[] ) is an array of `RemoteVideoStream` objects which can be either of `video` or `screenSharing` ( RemoteVideoStream.type allows one to differentiate ), it can be any combination of video/screen sharing streams, without any guarantee about their order ( which shouldn't really matter? ) or actual availability state ( which you can get by inspecting/subscribing to RemoteVideoStream.isAvailable property )
Issues #46 , #47 will be fixed to provide consistent behavior when running on desktop&mobile versions of Chrome.

Lastly - accessing 'low level' things like raw streams, is something that was already raised and we're evaluating it.

I'm happy that you've found a workarounds for the issues, but please keep in mind that if you're utilizing undocumented properties/methods - these are considered to be 'private', currently they are not really private, and you can inspect/access them programmatically, but going forward - we intend to make them truly private.

Can you please tell us more about
`In our application, we are mixing multiple video streams together for recording collaborative calls.`
I see that you've raised #67 already for accessing screen sharing stream, what is the scenario you're trying to enable, what else apart of exposing raw streams is missing on the public API surface to satisfy your requirements? 

Thanks!

**Comment by eliaspuurunen** [comment]
Hi @akania,

Re: order of remote participant video streams. In our case, we use Vue which allows us to do deep watch of variables. If the intent of the API is to only allow a remote participant to have 0-1 Camera feeds and 0-1 Screen Share feeds, either knowing the order or being able to access those streams via dedicated property would help. Otherwise, it is good to know that order is not guaranteed. 

Re: raw streams & recording. I'll send an email regarding our scenario. 

Thanks!

**Comment by RinaRish** [comment]
Hi @eliaspuurunen! Thanks for your feedback! I'm just wondering if you have any plans to deploy your scenarios for Android native as well?

**Comment by eliaspuurunen** [comment]
Hi @RinaRish - it's not part of our roadmap, we're 100% web/PWA at the moment.
