### ISSUE TITLE
when to use the two initializers of CommunicationUserCredential

### ISSUE THREAD

**Issue by terrychen1122** [Azure/Communication#53]
`CommunicationUserCredential` has two designated initializers (`initWithToken:error:` and `initWithInitialToken:refreshProactively:error:tokenRefresher`). Due to lack of documentation for these methods, I am not sure which to use or when to use one vs the other. Also, can we improve the documentation overall for the SDK?

Thanks

**Comment by raosanat** [comment]
Hi @terrychen1122 yes we are aware of the lack of documentation in that area and we will address the issue very soon. Meanwhile there is a snippet of code [here](https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/voice-video-calling/calling-client-samples?pivots=platform-ios) you can check to get you started
I would suggest using the approach of `tokenRefresher` as SDK can automatically call the function in the app to get a new token when the current token expires or gets invalidated



```
import AzureCommunication

let tokenString = "token_string"
var userCredential: CommunicationUserCredential?
do {
    userCredential = try CommunicationUserCredential(
        initialToken: tokenString, refreshProactively: true,
        tokenRefresher: self.fetchTokenSync
    )
} catch {
    print("Failed to create CommunicationCredential object")
}

// tokenProvider needs to be implemented by contoso which fetches new token
public func fetchTokenSync(then onCompletion: TokenRefreshOnCompletion) {
    let newToken = self.tokenProvider!.fetchNewToken()
    onCompletion(newToken, nil)
}
```

**Comment by terrychen1122** [comment]
so, if I understand it correctly, when `refreshProactively ` is `true`, when the token expires or gets invalidated, `tokenRefresher` block would be called and as the consumer of the SDK, we are responsible for passing a new valid token right?

**Comment by raosanat** [comment]
Yes that's correct in the sample provided provided above, `fetchTokenSync` will end up being called by the SDK whenever token needs to be updated. And yes you will be responsible for having an implementation that fetches the token

**Comment by RinaRish** [comment]
@terrychen1122 closing this instance, feel free to reopen
