### ISSUE TITLE
Unable to get phone numbers on Pay-As-You-Go subscription

### ISSUE THREAD

**Issue by williamzhao87** [Azure/Communication#54]
**Describe the bug**
Unable to get phone number on my Pay-As-You-Go subscription

**To Reproduce**
1. Create a Communication Service
2. Click Phone Numbers -> Click Get
3. See error `Your subscription isn't eligible to acquire phone numbers.`

**Expected behavior**
3. To see a list of available phone numbers

**Screenshots**
![image](https://user-images.githubusercontent.com/11931973/95470206-8184df80-094e-11eb-97a6-7102a93d67a4.png)
![image](https://user-images.githubusercontent.com/11931973/95603704-a3509600-0a24-11eb-9d5c-c3950a966a5d.png)

**Additional context**
My account was recently upgraded to paid from trial account, so it's still within the 12 months where many services are free.

**Comment by boris-bazilevskiy** [comment]
@williamzhao87 we need your Offer ID to clarify the issue, if you don't like the idea of publishing it here, drop an email to acsfeedback@microsoft.com.

**Comment by williamzhao87** [comment]
@boris-bazilevskiy 
I've updated the screenshot with the Offer ID, which according to the following document, corresponds to a "Pay-As-You-Go" subscription:
https://docs.microsoft.com/en-us/azure/cost-management-billing/costs/understand-cost-mgt-data

Pay-As-You-Go | Pay-As-You-Go | PayAsYouGo_2014-09-01 | MS-AZR-0003P | October 2, 20182
-- | -- | -- | -- | --

**Comment by nmurav** [comment]
@williamzhao87  is the Billing address on the subscription is a US address?

**Comment by williamzhao87** [comment]
@nmurav 
No, it is a Canadian address
