### ISSUE TITLE
Can we add nullability annotation for the headers of this library?

### ISSUE THREAD

**Issue by terrychen1122** [Azure/Communication#55]
As the tittle suggest, I think it's just a good practice to follow. Otherwise, we need to manually disable warnings for this library.

**Comment by mariusu-msft** [comment]
Thanks for the report @terrychen1122.

We are tracking to fix this in a future release.

cc: @RinaRish @raosanat

**Comment by tophpalmer** [comment]
AB#2283736

**Comment by tophpalmer** [comment]
Thank you for the feedback! I'm closing this issue but we have a [tracking card](https://github.com/Azure/Communication/projects/1) that is linked to this item.
