### ISSUE TITLE
What's the min Xcode version for this framework?

### ISSUE THREAD

**Issue by terrychen1122** [Azure/Communication#56]
In the release note, I saw 11.5+ is required for running the build script. So, I guess that (11.5+) isn't necessarily the min version for Xcode to run the frameworks. If true, what would be the min version?

**Comment by terrychen1122** [comment]
Also, since we are talking about the min version here. Regarding the iOS version, the current min is 12.0. How far behind the current iOS version do we expect the minimum App target version to be in the future?

**Comment by mariusu-msft** [comment]
Hi,

As you have stated, min iOS version is 12. Do you have any use-case which require support for < 12 ?

@RinaRish can you help with guidance around how far behind do we plan on being compared to current iOS version in terms of long term support?

Regarding the build script, we're looking at ways to improve that. Indeed the version required for that is 11.5.

Thanks,
Marius

**Comment by terrychen1122** [comment]
Thanks @mariusu-msft what's the min XCode version to build this framework? I am using 11.2.1 and it seems to be working with the frameworks alright.

(we don't have any use-case for < iOS 12)

**Comment by mariusu-msft** [comment]
@terrychen1122 We have not tried with anything less than 11.

If you find any issues please let us know. We're looking to improve\remove the build script. Closing this item. Feel free to reopen if you have more questions.

**Comment by terrychen1122** [comment]
@mariusu-msft @RinaRish do you know the answer of this "How far behind the current iOS version do we expect the minimum App target version to be in the future?" Our app supports 2 versions. Hopefully, the sdk support is at least larger than 2.

**Comment by terrychen1122** [comment]
bump ^^

**Comment by mariusu-msft** [comment]
We’re discussing internally and will provide an update soon.

cc: @RinaRish ans @tophpalmer

**Comment by RinaRish** [comment]
Sorry, it's taking a bit longer than expected. @terrychen1122

**Comment by terrychen1122** [comment]
@RinaRish that's ok. Do we have an estimate?

**Comment by mariusu-msft** [comment]
Closing. The current guidance is that we support minimum -2 at this time, depending on features. We will be updating public documentation in the upcoming months.
