### ISSUE TITLE
Video group call with Angular and .net core

### ISSUE THREAD

**Issue by amarjeetsingh0021** [Azure/Communication#57]
Hi,
I went through with the group calling sample code, which is available on the azure communication service link. Here, the UI part is developed in reactjs. 

By any chance, do we any sample code base using Angular and .net core for group video calling?

**Comment by chriswhilar** [comment]
Hi @amarjeetsingh0021, our current samples are all in ReactJS. Another sample we have is the Web Calling Tutorial (https://github.com/Azure-Samples/communication-services-web-calling-tutorial) but this is also in reactjs. The web calling sdk can still be used in Angular though.

**Comment by amarjeetsingh0021** [comment]
Hi Chris,
Thanks for the update.
By any chance, do we have any tutorial to record the video stream using
react js?

**Comment by chriswhilar** [comment]
Hi @amarjeetsingh0021, we currently do not support recording of anything. May i ask you to please describe in detail exactly what your scenario is? I can look into this and come back with some information.

**Comment by RinaRish** [comment]
Hi @amarjeetsingh0021! Thanks for your feedback! As for now, we don't have .Net SDK but UWP is going to be available sometime in the future.

**Comment by amarjeetsingh0021** [comment]
Hi Chris,

I am using azure communication service for group video calling. I have
referred the communicstion service sample demo for the same.

Everything looks good to me like video group calling and screen sharing.

On top of that I wanted to impmenet the recording feature to record the
session but not sure how.

Hope this help to understand my problem statement.

 I would appreciate, If anything you feel which is related to my
scenario please let me know.

Thanks,
Amarjeet Singh

**Comment by chriswhilar** [comment]
Hi @amarjeetsingh0021, yes we will be adding support for recording in future releases.

**Comment by amarjeetsingh0021** [comment]
Hi Chris,

Thanks for the update.

Do we have any tentative timeline to get this feature available?

I will plan accordingly and commit to my team.

**Comment by RinaRish** [comment]
Hi @amarjeetsingh0021 currently we can't give any timeline, sorry about that.

**Comment by amarjeetsingh0021** [comment]
Hi Trishna,

Thanks for the quick update.

It is fine for me. Please keep me posted Once its available.

Thanks,
Amarjeet Singh

**Comment by tophpalmer** [comment]
Hey @amarjeetsingh0021 , I'm closing this issue as it's tracked on [our roadmap](https://github.com/Azure/Communication/projects/1) and we are working on it. Thank you for reaching out with a request and please let us know of any questions or concerns.

**Comment by amarjeetsingh0021** [comment]
Thanks Chris.

I will let you know if I have any questions.
