### ISSUE TITLE
Data channels

### ISSUE THREAD

**Issue by pvaillant** [Azure/Communication#58]
**Is your feature request related to a problem? Please describe.**
I'm building a video app and would like to have functionality similar to a collaborative whiteboard. Currently there doesn't seem to be anything like WebRTC data channels available in Azure Communication Service.

**Describe the solution you'd like**
I'd like to have a mechanism similar to data channels in group calls to allow for additional data related to the group to be passed among/between the group members.

**Describe alternatives you've considered**
SignalR might be an alternative, or a separate websocket style connection, but this requires multiple connections to be made and duplicates some of the apps business logic.

**Comment by sphenry** [comment]
@pvaillant have you looked at [Fluid Framework](https://fluidframework.com/)?

**Comment by RinaRish** [comment]
Hi @pvaillant! Thanks for your feedback, currently there is no support for Data Channels, we did not finalize plans about it.

**Comment by tsubasaxZZZ** [comment]
+1
We hope Data channels in ACS. We released following application, and then this application is using WebRTC service and cognitive.
http://writewith.jp/

But WebRTC is not Azures service. We want to replace it to ACS.
