### ISSUE TITLE
Screen share on IPad Safari

### ISSUE THREAD

**Issue by GeorgeTTD** [Azure/Communication#59]
We are trying to support screen share in the browser across multiple different OS. We have found a few products already which work well apart from IOS safari. This is a big problem for us as a large proportion of our userbase own an iPad.

Unfortunately we don't have the resource to create a separate mobile app natively so we need a solution that works in the default browser of most devices (or the ability to install a supported browser on the device). We really only need the current tab shared which may make the solution easier to fix.

Currently we are using a mix of technologies, we have split the video call from the screen sharing to make life easier. For screen sharing we are using [https://github.com/rrweb-io/rrweb] and streaming the playback via signalr. It works but it is not a stable solution and we run into problems with IFrames. We have also been trialling ACS but have not been able to move past the evaluation stage as support for iPad is a hard requirement. 

Ideally we would like to have a solution for video and screen share under one roof which can scale from 5 -> 5000 users with ease.

**Comment by RinaRish** [comment]
Hi @GeorgeTTD! So screen sharing on ios/Android is not supported yet but it's on the roadmap. The number of people that could join a call as per now is 350. Can you give us a bit more details regarding the constraint of 5 -> 5000 users?

**Comment by GeorgeTTD** [comment]
Hi @RinaRish,

What we are really after is screen sharing in IOS safari using the javascript SDK, **not** a native mobile OS app. Our use case is we have a web platform for online tutoring in which we would like to connect students to their tutor and share the students screen with the tutor so they can assist them. This needs to be delivered via the browser due to the wide range of devices the students have and they should not have to install anything either.

The "5 -> 5000" users is more the total concurrent users not users per call (more likely 2-6 users per call) which I believe ACS will support out the box (some other solutions we tried will not). So that was more of a comment on our usage rather than a feature request.

**Comment by RinaRish** [comment]
So we already have the screen sharing support for javascript SDK and you can go and try it out but the amount of participants is currently limited to 350. You can learn more here https://docs.microsoft.com/en-us/azure/communication-services/concepts/voice-video-calling/calling-sdk-features

**Comment by chriswhilar** [comment]
Hello @GeorgeTTD, as @RinaRish mentioned, our calling sdk for javascript (browser) does support screensharing. The browsers we support are safari, chrome, and new edge chromium. Please give it a try it should work fine for you, let us know if any issues.

Please note that only 1 participant in the call can share their screen at any given time. Meaning that if participant A is screensharing, and another participant B wants to start screensharing, then participant B will take over the screen sharing and participant A will automatically stop screen sharing

**Comment by GeorgeTTD** [comment]
Hello @RinaRish @chriswhilar,

Thanks for getting back to me, I raised this issue as we were testing using the demo calling app the other day and noticed there was no option to share screen when on an iPad (Worked fine on desktop). Having a quick look in the code there is this function:

Source: [Group Calling Hero Sample/Web/Calling/ClientApp/src/containers/Header.ts](https://github.com/Azure/Communication/blob/master/samples/Group%20Calling%20Hero%20Sample/Web/Calling/ClientApp/src/containers/Header.ts)

```javascript
const mapDispatchToProps = (dispatch: any) => ({
  setLocalVideoStream: (localVideoStream: LocalVideoStream) => dispatch(setLocalVideoStream(localVideoStream)),
  setMic: (mic: boolean) => dispatch(setMicrophone(mic)),
  setScreenShare: (screenShare: boolean) => dispatch(setShareUnshareScreen(screenShare)),
  // Only support Desktop -- Chrome | Edge (Chromium) | Safari
  isLocalScreenShareSupportedInBrowser: () => {
    return (
      !utils.isMobileSession() &&
      (/chrome/i.test(navigator.userAgent.toLowerCase()) || /safari/i.test(navigator.userAgent.toLowerCase()))
    );
  }
});
```

Please let me know if screen share is supported through the browser on **Mobile devices**. If it is not currently support will it be and what will the minimum device spec be. 

Thanks,
George

**Comment by chriswhilar** [comment]
Hi @GeorgeTTD,

Some useful info:
On mobile browser, outgoing screensharing is not supported by the calling sdk. However incoming screensharing is supported, that is incoming screensharing from a remote participant that is using a desktop browser.

Desktop browsers that we support are:
- Chrome and Edge chromium on Windows.
- Chrome and Safari on MacOS

Mobile browsers that we support are:
- Safari on iOS
- Chrome on Android.

**Comment by GeorgeTTD** [comment]
@chriswhilar,

I understand that outgoing screensharing is not supported by the calling SDK, that is what I am trying to request as a feature. Will outgoing screensharing on mobile devices be in the roadmap?

Thanks,
George

**Comment by RinaRish** [comment]
Hi @GeorgeTTD yes, it's on the roadmap.

**Comment by RinaRish** [comment]
@GeorgeTTD apologies for the confusion, what I meant that ios/android screen sharing is on roadmap for native SDKs and no browsers. Hope that helps.

**Comment by RinaRish** [comment]
@GeorgeTTD I'm closing this. Feel free to reopen or create another issue if you feel there is something we can help you with.
