### ISSUE TITLE
Can a call be initiated in the same group as chat?

### ISSUE THREAD

**Issue by nikita-rane-22** [Azure/Communication#60]
We are trying to integrate the group calling application with the group chat application. We want the users to initiate a call in the same group in which the chat is in process. How do we achieve this?

**Comment by RinaRish** [comment]
Hi @nikita-rane-22! It's not currently supported, but it's something we'll be looking at. You are actually the first customer asking for it so we would love to hear more details about your use-case (if that possible)

**Comment by RinaRish** [comment]
Hi @nikita-rane-22! It's not currently supported, but it's something we'll be looking at. What is your scenario?

**Comment by nikita-rane-22** [comment]
Hi @RinaRish! I was just trying this out, but please do share updates regarding this.

**Comment by RinaRish** [comment]
to place a group call to a set of users you have a couple of different options:

**option1**: use the 1:n place call feature mentioned here,
https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/voice-video-calling/calling-client-samples?pivots=platform-web#place-a-11-call-to-a-user-or-a-1n-call-with-users-and-pstn
**option2**: to start a group call or join an existing group call, you can use the "join group call"  feature which takes in a "groupId" ( which must be a guid) which is mentioned here
https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/voice-video-calling/calling-client-samples?pivots=platform-web#join-a-group-call
**option 3**: you can start a 1:1 call, and then use the "add a participant to a call" feature and add a user or pstn number to the existing call, this is mentioned here,
https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/voice-video-calling/calling-client-samples?pivots=platform-web#add-a-participant-to-a-call

**Comment by mariusu-msft** [comment]
@nikita-rane-22 for your scenario we recommend option1 from @RinaRish' list.

You can get all the members in the chat thread, and place a call using option1 to all the members in the chat.

**Comment by nikita-rane-22** [comment]
Can we have something on similar terms for VOIP? We aren't looking for PSTN.

**Comment by mariusu-msft** [comment]
@nikita-rane-22 The above links are applicable for VoIP as well.

**Comment by RinaRish** [comment]
@nikita-rane-22 I'm closing this issue, feel free to reopen if you have any other questions.
