### ISSUE TITLE
Sample App: Group Chat - instructions are incorrect

### ISSUE THREAD

**Issue by dombat** [Azure/Communication#64]
This line in readme.md is incorrect. in the sample https://github.com/Azure-Samples/communication-services-web-chat-hero

5. Update the ENVIRONMENT_URL in `./Chat/ClientApp/src/constants.tsx` with the location of your resource. (e.g https://<RESOURCE_NAME>.communication.azure.com)

In the version I just downloaded, constants.tsx does NOT contain this item.

Here is the supplied constants.tsx

// Project settings
export const GUID_FOR_INITIAL_TOPIC_NAME =
  'c774da81-94d5-4652-85c7-6ed0e8dc67e6';

// Project configurations
export const COOL_PERIOD_THRESHOLD = 60 * 1000;
export const INITIAL_MESSAGES_SIZE = 2000;
export const MAXIMUM_LENGTH_OF_NAME = 10;
export const MAXIMUM_LENGTH_OF_MESSAGE = 8000;
export const MAXIMUM_LENGTH_OF_TOPIC = 30;
export const MAXIMUM_LENGTH_OF_TYPING_USERS = 35;
export const MAXIMUM_RETRY_COUNT = 3;
export const MINIMUM_TYPING_INTERVAL_IN_MILLISECONDS = 8000;
export const MAXIMUM_INT64 = 9223372036854775807;
export const NUMBER_OF_MESSAGES_TO_LOAD = 10;
export const PAGE_SIZE = 200;
export const PARTICIPANTS_THRESHOLD = 20;

// Keyboard keys
export const ENTER_KEY = 13;
export const SPACE_KEY = 32;

// Http Status Code
export const OK = 200;
export const CREATED = 201;
export const MULTI_STATUS = 207;
export const PRECONDITION_FAILED_STATUS_CODE = 412;
export const TOO_MANY_REQUESTS_STATUS_CODE = 429;

// Regex
export const URL_REGEX = /https?:\/\/(www\.)?[-a-zA-Z0-9@:%._+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_+.~#?&//=]*)/;
export const EMPTY_MESSAGE_REGEX = /^\s*$/;

**Comment by ashwinder** [comment]
Hi @dombat We recently updated the chat sample and removed the need for updating environment_url. You can skip this step while we get the documentation updated to reflect the same.

**Comment by ddematheu2** [comment]
Documentation has been updated.

**Comment by ashwinder** [comment]
closing the issue as the documentation has been updated to reflect the correct steps.
