### ISSUE TITLE
Determining Stream Type is inconsistent between LocalVideoStream and RemoteVideoStream

### ISSUE THREAD

**Issue by eliaspuurunen** [Azure/Communication#65]
**Is your feature request related to a problem? Please describe.**
If a user is working with a `LocalVideoStream`, they can fetch the type through the method `getMediaStreamType()`.

https://docs.microsoft.com/en-us/javascript/api/azure-communication-services/@azure/communication-calling/localvideostream?view=azure-communication-services-js

If a user is working with a `RemoteVideoStream`, they can fetch the type through the property `type`.

https://docs.microsoft.com/en-us/javascript/api/azure-communication-services/@azure/communication-calling/remotevideostream?view=azure-communication-services-js#type

**Describe the solution you'd like**
Could `LocalVideoStream` expose a property called `type` so the developer does not have to have two code paths for dealing with type determination?

**Comment by akania** [comment]
Hi @eliaspuurunen , thank you for your feedback, that's a good catch and we'll address it in future release.

**Comment by akania** [comment]
hi @eliaspuurunen , small cleanup - we've introduced 'mediaStreamType' ( in v1.0.0-beta.5 ) - please update to latest version - both remote & local stream have same `mediaStreamType` property that can be used to determine if stream is 'video' or 'screenshare'
