### ISSUE TITLE
Is there a way to determine if the Local User is speaking?

### ISSUE THREAD

**Issue by eliaspuurunen** [Azure/Communication#66]
**Is your feature request related to a problem? Please describe.**
When in a call, if a remote participant is speaking, the property `isSpeaking` changes. 

https://docs.microsoft.com/en-us/javascript/api/azure-communication-services/@azure/communication-calling/remoteparticipant?view=azure-communication-services-js#isspeaking

Is there a similar method/property that can be used on the local participant? 

**Describe the solution you'd like**
Perhaps a `LocalParticipant` type that behaves like the `RemoteParticipant` type - would reduce the amount of "unique" code for dealing with local video stream previews, screen share previews, etc. 

The idea would be that local code used to display camera & screen share previews would only need to deal with a "Participant." That could be Local or Remote - perhaps local would have more functions e.g. mute, change camera, etc.. For components in a PWA, it would mean we could use the same display components more easily for Local & Remote participants. 

Related - issue #65 - re: local/remote users have unique code paths.

**Comment by akania** [comment]
Hi @eliaspuurunen , Call itself represents state of a local participant endpoint
https://docs.microsoft.com/en-us/javascript/api/azure-communication-services/@azure/communication-calling/call?view=azure-communication-services-js
With properties like state, isMicrophoneMuted etc..

Currently we're not exposing any property or trigger any event that would allow a developer to learn if local participant is speaking, but we'll consider adding it in future releases

**Comment by ProbablePrime** [comment]
We've had other requests for this feature across our other SDKs, in #273 for example.

Let's ensure that our future SDK releases try to feature this in as many platforms as we can.
