### ISSUE TITLE
Web: Is there a way to preview the local user's screen sharing stream?

### ISSUE THREAD

**Issue by eliaspuurunen** [Azure/Communication#67]
**Is your feature request related to a problem? Please describe.**
For remote users, it is possible to view their screen sharing stream by looking at the `RemoteParticipant` videoStreams array. Is the same possible for a local participant? 

When the screen sharing request succeeds in a call, the `Call.localVideoStreams` array does not seem to update with the new screen share stream.

**Comment by eliaspuurunen** [comment]
Update: it appears it is possible. But this feels like a dangerous hack.

After calling `startScreenSharing()` on the `Call` instance (and awaiting the result), the MediaStream can be fetched like so:

```
// azureCall is the property that holds an instance of Call

let stream = azureCall._tsCall.sharedScreenHandle.mediaStream.rawMediaStream;

document.getElementById("screenPreview").srcObject = stream;            this.$refs.displayPreview.play();

```

**Comment by akania** [comment]
Hi @eliaspuurunen , thank you for feedback, it's a bug on our side, we'll fix it in future release.

Code snippet you've shared will indeed allow you to access media stream, although you're accessing 'private' fields that going forward won't be exposed from the Call - that's a great catch but I'd discourage using it, we'll come with proper implementation soon

**Comment by eliaspuurunen** [comment]
Hi @akania - sounds great. We'll keep an eye on future releases. Can it be noted somewhere in release notes or documentation how best to retrieve said stream? It is a requirement for a client of ours. Thanks.

**Comment by ProbablePrime** [comment]
@eliaspuurunen Do we have an ADO item for this? Can we mark it as ADO Linked so we can monitor it on both sides?

**Comment by eliaspuurunen** [comment]
Hi @ProbablePrime - not sure what ADO is. Unfortunately we migrated to another platform as it met our needs better for the time being. Thanks.

**Comment by ProbablePrime** [comment]
@eliaspuurunen My apologies I tagged, the wrong user but I really appreciate the update. Thank you

**Comment by akania** [comment]
ADO#2806403
