### ISSUE TITLE
Not able to export .ipa from Archive (Xcode 11.5 and Xcode 12.0.1)

### ISSUE THREAD

**Issue by rahulp108** [Azure/Communication#70]
**When I try to export .ipa from archive in Xcode 11.5 and Xcode 12.0.1**
I am implement video calling feature using Azure Communication service. After that when I tried to share build on App Center we have pipeline setup. In that I got errors. So, we tried with manual distribute method. I archived build on Xcode 12.0.1 and tried to export .ipa from archive. For this I choose Ad Hoc Provisioning profile. Then I am getting error saying "IPA processing failed".

When I show logs then I found that 

2020-10-19 14:39:42 +0000  Assertion failed: Expected 2 archs in otool output:
/var/folders/_8/fdh7st9x6xlf_3hx1858q28h0000gn/T/IDEDistributionOptionThinning.~~~CxGDKf/Payload/AcelityPatientApp.app/Frameworks/AzureCommunicationCalling.framework/AzureCommunicationCalling:
Mach header
      magic  cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
MH_MAGIC_64   X86_64        ALL  0x00       DYLIB    38       4960   NOUNDEFS DYLDLINK TWOLEVEL WEAK_DEFINES BINDS_TO_WEAK NO_REEXPORTED_DYLIBS MH_HAS_TLV_DESCRIPTORS

This issue. When searched on different portal for this I didn't found any solution so, raising issue here.

**To Reproduce**
1. Go to integrate video calling feature in swift
2. Then to share build archive it and try to export .ipa file from it using Ad Hoc provisioning profile
4. We will get  error saying "IPA processing failed". 

**Expected behavior**
It should export .ipa from archive.

**Screenshots**
Added screenshot as well

![Uploading Image 19-10-20 at 8.47 PM.jpg…]()

**Desktop (please complete the following information):**
 - OS: Mac OS 10.15.5
 - Xcode Version - 12.0.1 and 11.5

**Comment by tompi** [comment]
Not sure if its the same as my problem, but If you are using beta 4, you probably need to change the cfshortbundleversion of azurecommunicationcalling/info.plist. It’s currently set to 1.0.0-beta-4. Which iTunes connect doesn’t like. Try changing it to eg 1.0.0 and build again. Ps: Microsoft needs to fix that

**Comment by raosanat** [comment]
Thanks @tompi thanks for reporting incorrect version in cfshortbundleversion.

@rahulp108 can you run  this command on the AzureCommunicationCalling library

`lipo AzureCommunicationCalling.framework/AzureCommunicationCalling -remove x86_64 -output output_path/AzureCommunicationCalling.framework/AzureCommunicationCalling

**Comment by rahulp108** [comment]
Thanks @tompi and @raosanat 
As per above suggestion I made changes in my project and it worked for me. So, I am closing this issue.

Thanks once again both of you.
