### ISSUE TITLE
[iOS] Getting EXC_BAD_ACCESS (code=1, address = 0x134) when setting the delegate of device manager 

### ISSUE THREAD

**Issue by terrychen1122** [Azure/Communication#71]
<img width="384" alt="Screen Shot 2020-10-19 at 8 46 09 PM" src="https://user-images.githubusercontent.com/5403473/96537979-5a7eb580-124c-11eb-92a1-cff59ced8ce4.png">

The NSError code is 1. 

Note that at this point I haven't asked for camera and microphone permissions yet. I am not sure if this is required for getting device manager. 

Also, regardless, my suggestion is the completion should either return nil error and a complete device manager or a non-nil error and a nil device manager. Now, I am getting a non-nil error and a device manager but it hit exception when setting the delegate.

**Comment by terrychen1122** [comment]
My code was calling `createCallAgent` and `getDeviceManager` in parallel. I resolved it by calling `getDeviceManager` after the call agent is created. But why is this? I think they are not related. If so, we should document it.

**Comment by raosanat** [comment]
@terrychen1122  yes that's correct we have a known issue where for now you will have to getDeviceManager only only successfully creation of callAgent. We will update the documentation to reflect that. Thanks
