### ISSUE TITLE
.net calling sdk for telephony and for teams calling

### ISSUE THREAD

**Issue by nawab1990** [Azure/Communication#74]
**Is your feature request related to a problem? Please describe.**
I would like to implement calling in my application using .net

**Describe the solution you'd like**
I would like a .net sdk that contains quick starts and samples for telephony and group calling

**Describe alternatives you've considered**
Implementing using Java Script

**Additional context**

**Comment by RinaRish** [comment]
Hi @nawab1990! Thanks for your feedback .Net SDK is on the roadmap but meantime you can start building your solutions with JavaScript https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/voice-video-calling/calling-client-samples?pivots=platform-web. Let us know if you have any other questions.
