### ISSUE TITLE
get live caption from graph api during the call? 

### ISSUE THREAD

**Issue by plato001ca** [Azure/Communication#75]
we are looking to get access on the live caption (text) during a live event ( live conversation) without show and record it as part of video call that help us to process the live caption text and make a proper action once we receive some specific words/ phrases ...

Solution:
1) Adding new rest api on the Graph Api  to retrieve the conversation live captions by time and attendants 
2) setup a web hook on the call to send the caption live contents

**Comment by jsandoval-msft** [comment]
Hi @plato001ca , the capability described is not currently supported as a feature. However, I've added your input into our feature prioritization process to help us refine our roadmap for new capabilities over the next several months. Thanks!

**Comment by ProbablePrime** [comment]
@jsandoval-msft Does this item have an ADO item in our ADO? Can we mark it as linked? Please provide the link to the ADO Item.
