### ISSUE TITLE
HoloLens 2 support

### ISSUE THREAD

**Issue by jeevcat** [Azure/Communication#77]
Are there any plans to support HoloLens 2 for any of the components of this service? I'm guessing this would at least require C++ or .NET SDKs which can target ARM64 Windows.

**Comment by RinaRish** [comment]
Hi @jeevcat! Can you please tell us more about the scenario you are trying to achieve?

**Comment by jeevcat** [comment]
@RinaRish using for example the Chat component with HoloLens and C++.

**Comment by fxsrt10** [comment]
I'd also like to know if HL2 support can be added in the future, we're really interested and have difficulty building other rtc solutions that work well with HL2

**Comment by suriab** [comment]
I would also like to know about C++ SDK for a/v communication between HL-2  and mobile/web.

**Comment by RinaRish** [comment]
> @RinaRish using for example the Chat component with HoloLens and C++.

Adding @ashwinder to answer Chat question.

**Comment by ashwinder** [comment]
Thanks all for your questions. 
1. HoloLens support - Our .Net SDK (available [here](nuget)) is expected to work with HoloLens. We havent built an experience using HoloLens & .NET SDK yet but we plan to test it soon. In the meantime, if you try it out and encounter any problems, please create a new issue and we will look into it. 
2. C++ SDK is not on our roadmap.

**Comment by ashwinder** [comment]
Closing this ticket. If you face an issue with using .Net SDK with HoloLens, please open a new ticket and we will get back to you. Thanks!
