### ISSUE TITLE
[iOS] when an expired token is used, callAgent's completion is not called

### ISSUE THREAD

**Issue by terrychen1122** [Azure/Communication#78]
When an expired token is used to create `userCredential` and using that credential to create call agent, the call agent creation's completion is not called, so the app would be stuck in a loading state forever. The idea graceful handling should be that either `userCredential` is not created and return error or callAgent's completion block should return and contain error

**Comment by mariusu-msft** [comment]
@terrychen1122 which constructor for credential are you using?

**Comment by terrychen1122** [comment]
```
NSError *credentialCreationError;
    self.userCredential = [[CommunicationUserCredential alloc] initWithInitialToken:self.userToken
                                                                 refreshProactively:YES
                                                                              error:&credentialCreationError
                                                                     tokenRefresher:^(void (^ _Nonnull refresher)(NSString * _Nullable, NSError * _Nullable)) {
```
this is the constructor I am using

**Comment by mariusu-msft** [comment]
Hey @terrychen1122, 

We’re following up internally and will get back to you in a few days.

Meanwhile can you tell me if the token you are subsequently providing is also expired?

Thanks,
Marius

**Comment by terrychen1122** [comment]
Oh, are you saying that in this case `tokenRefresher ` is triggered (I didn't check that). If so, yes, due to a caching issue on our side, the token it provided was subsequently was expired as well.

**Comment by mariusu-msft** [comment]
It is possible, we're investigating too, can you check if when triggered you are returning an expired one or not?

**Comment by raosanat** [comment]
If `tokenRefresher` continuously returns expired token then it will be stuck in an endless loop until an un-expired token is provided.

**Comment by terrychen1122** [comment]
We can close it. Actually, we found a bug on our side. The infinite loading state was due to that. Sorry for the false alarm.

**Comment by mariusu-msft** [comment]
Thanks for the report
