### ISSUE TITLE
[iOS] when do we start/stop actually using the camera?

### ISSUE THREAD

**Issue by terrychen1122** [Azure/Communication#79]
Since iOS14, Apple will display an indicator on the status bar for camera usage. I am curious which of the following steps we start using the camera (to make sure we do the right thing at the right timing and step):
1. When `ACSDeviceManager` is created by `ACSCallClient`
2. When a `ACSLocalVideoStream` is initialized by a video device info from the device manager
3. When a `ACSRenderer` is initialized by a local video stream
4. When a `ACSRendererView` is initialized by a `ACSRenderer` that is created by a local video stream

My guess is #2 since I saw exception if I didn't grant permission when doing 2 (but it could also be 3 or 4). Since I don't have Xcode 12 installed locally, it will take some time for us to verify. So, I would just ask here to confirm.

Thanks

**Comment by xixian73** [comment]
#2 throws exception because we can't read camera settings without it.
 
#4 is when the camera is actually opened and iOS will start showing the indicator in status bar for camera usage and it will stay like that unless the app invokes ACSRenderer.dispose()
