### ISSUE TITLE
In Group Video Call speaker is not working 

### ISSUE THREAD

**Issue by rahulp108** [Azure/Communication#81]
**In Group Video Call speaker us not starting **

**To Reproduce**
1. Implemented sample code.
2. Created token from internal server.
3. Using token create userCredential.
4. Using callClient and userCredential created callAgent.
5. Then fetching device manager using getDeviceManager method.
6. Then fetching speakers and setting first speaker to device manager.
7. And starting group video call.
8. Once call is connect then I can hear voice on headphone and in phone but not on speaker.

**Expected behavior**
Need to come voice from speaker as default once we start video call.

**Smartphone (please complete the following information):**
 - Device: iPhone SE 
 - OS: 14.0.1
 - Browser: Xcode 
 - Version: 12.0.1

**Comment by mariusu-msft** [comment]
@rahulp108 to use speaker on iOS you need to use OS APIs to route audio to speakers:

https://developer.apple.com/library/archive/qa/qa1754/_index.html

We're currently working on better defining a better story around device management.

**Comment by rahulp108** [comment]
> @rahulp108 to use speaker on iOS you need to use OS APIs to route audio to speakers:
> 
> https://developer.apple.com/library/archive/qa/qa1754/_index.html
> 
> We're currently working on better defining a better story around device management.


I am using deviceManager object from Azure Communication service then why I need to go with default one? Please clarify.

**Comment by ProbablePrime** [comment]
Hey @RinaRish , the issue author has additional questions, could you please take a look? Thank you.

**Comment by tophpalmer** [comment]
AB#2309710

**Comment by Immons** [comment]
What about Android? Cause for Android it also plays sound from headphone instead speaker.

**Comment by RinaRish** [comment]
Hi! Thanks for reporting this! Unfortunately, you need to use OS APIs for Android as well. Apologies for the delay in responding here. You can check out the latest supported features here - https://docs.microsoft.com/en-us/azure/communication-services/concepts/voice-video-calling/calling-sdk-features#calling-sdk-timeouts
Feel free to reopen if you have more questions
