### ISSUE TITLE
[iOS] iOS 14 Orange Dot + Microphone Usage

### ISSUE THREAD

**Issue by ryanespiritu** [Azure/Communication#82]
With the introduction of iOS 14, the iPhone OS now displays an orange dot at the top right corner of the screen when an app is currently accessing the microphone. 

I noticed that this dot persists in an active ACS call even after calling the `mute` API. I verified that no audio was streaming to the call at the time by calling "Echobot" and listening for a playback. 

I wanted to confirm if this is intended or if this is something that should be handled by the ACS SDK. If not, I'll need to find a way to explicitly disable the iPhone's microphone on my side.

Thanks in advance for the help!

**Comment by terrychen1122** [comment]
it sounds like the SDK should just not continue using the microphone if `muted`

**Comment by raosanat** [comment]
Hi @terrychen1122 We will look into the issue. It indeed seems like an issue in our SDK.

**Comment by ProbablePrime** [comment]
@raosanat This issue is quite stale, do you have an update for this customer? We've had several SDK versions released.

**Comment by mariusu-msft** [comment]
Closing this by Design.

While Muted we still capture audio for local processing like notifying users of "speaking while muted", while not streaming the audio further.

The `isMicrophoneMuted` property should be used to determine if one is locally muted
