### ISSUE TITLE
[iOS SDK] Avoid orphaned ongoing ACSCall

### ISSUE THREAD

**Issue by terrychen1122** [Azure/Communication#87]
We found out that if we release the reference to `ACSCall` but do not hang up the call, the call is still running and there is no way we could hang up. My expectation is when the reference of an activeACSCall is released, the call should end automatically. Could we add support for this or fix this?

**Comment by mariusu-msft** [comment]
This is by design.

You can always get the Call instance by using the Calls property on ACSCallAgent object instance

https://docs.microsoft.com/en-us/objectivec/communication-services/calling/acscallagent

If you dispose of CallClient or CallAgent, it should tear down any active calls.

-Marius.
