### ISSUE TITLE
[iOS] App crash when joining a call with muted and audio permission was not granted  

### ISSUE THREAD

**Issue by terrychen1122** [Azure/Communication#90]
I encountered a crash when I did `joinWithGroupCallContext:joinCallOptions:` with `audioOptions.muted` being true and the audio permission was not granted. 

If the user wants to join the call with muted option, why would they grant permission? Shouldn't they only grant permission when they want to unmute?

**Comment by terrychen1122** [comment]
Is it related to https://github.com/Azure/Communication/issues/82 ?  cuz I realized that on iOS14 even when I joined the call while I was muted, the orange indicator still showed up. That explained the crash since regardless of the option it will access the microphone.
Are we aiming to fix it in the next release?

**Comment by mariusu-msft** [comment]
This should not result in a crash, but throw an exception that audio permissions were not granted. Is that what you are seeing @terrychen1122? @raosanat can you take a look?

Regarding the requirement to allow permissions beforehand, right now the design indeed requires permissions to be granted before application connects to a call, regardless of audio or video modalities.

We can tag this a future improvement item.

**Comment by terrychen1122** [comment]
Yes, it was an exception. But why would you need permission if we are not using the microphone at all. And the users shouldn’t see the orange indicator if they mute.

**Comment by mariusu-msft** [comment]
Hi @terrychen1122,

We will revisit this design for future releases. Marking this as Enhancement.

Thanks,
Marius

**Comment by ProbablePrime** [comment]
@mariusu-msft Is this ADO Linked so we can track it on both sides?

**Comment by raosanat** [comment]
This has been fixed, please verify with latest build.
