### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by jaytarang92** [Azure/Communication#92]
**Describe the bug**
There is a typo in the README.md

**To Reproduce**
1. Go to https://github.com/Azure/Communication/blame/master/README.md#L55
2. Click on Source File
3. Scroll down to Line55
4. See typo

**Expected behavior**
It should be Azure and Azrue

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 10.11 Beta 10
 - Browser Vivaldi
 - Version 3.4.2066.86

**Additional context**
    I am building a function app in Azure and how can I get the example linked in the docs? (Once I am done)
    https://github.com/jaytarang92/sms-health-check
    Thanks

**Comment by tomaschladek** [comment]
Hi jaytarang92, thank you for reporting the typo, I've started the pull request with fix. 

Regarding your question, can you please help me understand which example do you mean? I've noticed that you are sending SMS from python code. But I'm not sure what do you mean by getting the example once you are done. 

Thank you

**Comment by jaytarang92** [comment]
Ahh yeah . I meant getting it added as an example in the readme . But I found it would be better added to the python sdk directly. I actually meant 'Once I am done' .
