### ISSUE TITLE
'AzureCommunication/AzureCommunication-Swift.h' file not found

### ISSUE THREAD

**Issue by devgokhan** [Azure/Communication#93]
Hi. I am unable to run the sample add with "Azure Communication Calling iOS SDK version 1.0.0-beta.4". I installed this SDK with following all steps of the this document : https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/voice-video-calling/getting-started-with-calling?pivots=platform-ios

In documents says do same thing (says download zip and place it in the project) for AzureCore and AzureCommunication however there is no .framework files available so to download AzureCore and AzureCommunication frameworks so I used Swift Package Manager with following instructions: https://github.com/Azure/azure-sdk-for-ios

Anyway I downloaded and put the AzureCore AzucreComminication and AzureCommunicationCalling SDKs but I am facing with this error: "**'AzureCommunication/AzureCommunication-Swift.h' file not found**" in AzureCommunicationCalling.framework when "#import <AzureCommunication/AzureCommunication-Swift.h>". I did everything in shared sample. And also gives this error "**Could not build Objective-C module 'AzureCommunicationCalling'**" ContentView.swift file when import AzureCommunicationCalling

![Screen Shot 2020-11-04 at 10 32 50](https://user-images.githubusercontent.com/8233432/98082313-97bc8780-1e89-11eb-8a61-f29b965fdaf1.png)
![Screen Shot 2020-11-04 at 10 36 39](https://user-images.githubusercontent.com/8233432/98082352-aa36c100-1e89-11eb-9294-095314de7597.png)
![Screen Shot 2020-11-04 at 10 36 48](https://user-images.githubusercontent.com/8233432/98082355-aacf5780-1e89-11eb-9901-803555e83ff1.png)
![Screen Shot 2020-11-04 at 10 39 11](https://user-images.githubusercontent.com/8233432/98082555-fe41a580-1e89-11eb-941a-dc6702f092b5.png)

**Comment by raosanat** [comment]
Hi @devgokhan you can use the shell script  `BuildAzurePackages.sh` that came with the [release ](https://github.com/Azure/Communication/releases/tag/v1.0.0-beta.4)

You will get the path to the AzureCore and AzureCommunication packges after you run the script.

**Comment by devgokhan** [comment]
Hi @raosanat,

Still I can't see .framework files in project path and the path which shared in terminal

Code runned: 
`sh ./BuildAzurePackages.sh`

![Screen Shot 2020-11-04 at 11 13 57](https://user-images.githubusercontent.com/8233432/98086959-7f9c3680-1e90-11eb-9bf7-37c81732ec9d.png)

Then I searched files in my computer I found and  I copied the .framework files into my project then I still get same messages

![Screen Shot 2020-11-04 at 11 31 34](https://user-images.githubusercontent.com/8233432/98087603-634cc980-1e91-11eb-83df-15b8a1ddb40f.png)
![Screen Shot 2020-11-04 at 11 31 23](https://user-images.githubusercontent.com/8233432/98087608-66e05080-1e91-11eb-9d56-61feea30e2df.png)

It seems AzureCommunication framework has no Header files however AzureCore has.. ?
![Screen Shot 2020-11-04 at 11 33 23](https://user-images.githubusercontent.com/8233432/98087758-a313b100-1e91-11eb-8866-6edc4ca55c23.png)

**Comment by raosanat** [comment]
@devgokhan to unblock you for now, we have some initial support for cocoapods.  You can create a PodFile like below

```
# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
use_frameworks!

source 'https://github.com/Azure/azure-sdk-for-ios.git'

target 'ACSCallingTestApp' do
  pod 'AzureCommunicationCalling', :podspec => 'https://raw.githubusercontent.com/Azure/azure-sdk-for-ios/master/AzureCommunicationCalling.podspec'
  pod 'AzureCommunication', :git => 'https://github.com/Azure/azure-sdk-for-ios.git', :branch => "master"
  pod 'AzureCore', :git => 'https://github.com/Azure/azure-sdk-for-ios.git', :branch => "master"

  # Following will be available later when specs are published to trunk
  #pod 'AzureCommunicationCalling', '~> 1.0.0-beta.4'
  #pod 'AzureCommunication', '~> 1.0.0-beta.2'
  #pod 'AzureCore', '~> 1.0.0-beta.2'
end
```

**Comment by devgokhan** [comment]
Hi @raosanat  I could download 3 framework via pod. But error is same. What is missing?

![Screen Shot 2020-11-05 at 10 30 26](https://user-images.githubusercontent.com/8233432/98210761-1bda4200-1f52-11eb-81b8-ce9132fe095d.png)
![Screen Shot 2020-11-05 at 10 30 31](https://user-images.githubusercontent.com/8233432/98210759-1b41ab80-1f52-11eb-8616-99851833bab0.png)
![Screen Shot 2020-11-05 at 10 30 56](https://user-images.githubusercontent.com/8233432/98210752-17ae2480-1f52-11eb-8073-b3198346e635.png)

**Comment by raosanat** [comment]
It could be that you architecture is not set properly. Under “Build Settings” make sure the architecture matches to what you building it for.

**Comment by devgokhan** [comment]
I don't actually understand what do you mean? Everything seems normal, I think maybe file is missing in AzureCommunication framework? Could you download and run successfully with same way? (same pod download)
This is your sample project but I can upload all project with all framework files with you if you wish & need? 
![Screen Shot 2020-11-05 at 11 43 52](https://user-images.githubusercontent.com/8233432/98218194-885a3e80-1f5c-11eb-97ba-1cc37eadcdc5.png)
![Screen Shot 2020-11-05 at 11 43 08](https://user-images.githubusercontent.com/8233432/98218195-88f2d500-1f5c-11eb-8fa0-a70075e8b050.png)
![Screen Shot 2020-11-05 at 11 42 51](https://user-images.githubusercontent.com/8233432/98218196-8a240200-1f5c-11eb-8706-46242a9ecbf0.png)
![Screen Shot 2020-11-05 at 11 42 29](https://user-images.githubusercontent.com/8233432/98218199-8abc9880-1f5c-11eb-9469-1e3c84829acc.png)
![Screen Shot 2020-11-05 at 11 44 34](https://user-images.githubusercontent.com/8233432/98218178-855f4e00-1f5c-11eb-9449-6bc96ce1f64c.png)

**Comment by mariusu-msft** [comment]
I tried this on a new project and was not able to repro with pods.

Can you try with the sample @raosanat?

@devgokhan what is your Xcode version?

**Comment by raosanat** [comment]
Hi, I was able to get the sample here to work with pods, but since we have recently started supporting cocoapods we need to update the sample and we will fix it soon. For now after you have done the pods install like this
```
# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
use_frameworks!

source 'https://github.com/Azure/azure-sdk-for-ios.git'

target 'AzureCommunicationCallingSample' do
  pod 'AzureCommunicationCalling', :podspec => 'https://raw.githubusercontent.com/Azure/azure-sdk-for-ios/master/AzureCommunicationCalling.podspec'
  pod 'AzureCommunication', :git => 'https://github.com/Azure/azure-sdk-for-ios.git', :branch => "master"
  pod 'AzureCore', :git => 'https://github.com/Azure/azure-sdk-for-ios.git', :branch => "master"
end
```

you will see this warning after you do `pod install`. 
```
[!] The `AzureCommunicationCallingSample [Debug]` target overrides the `FRAMEWORK_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-AzureCommunicationCallingSample/Pods-AzureCommunicationCallingSample.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `AzureCommunicationCallingSample [Release]` target overrides the `FRAMEWORK_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-AzureCommunicationCallingSample/Pods-AzureCommunicationCallingSample.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
```
Please update the `Framework search paths` under `Build settings` to only the entry `$(inherited)`
Open the `AzureCommunicationCallingSample.xcworkspace` and under the frameworks please remove the already added frameworks as you will get this error

```
error: Multiple commands produce '/Users/sanathrao/Documents/source/communication-services-ios-quickstarts/Add Voice Calling/DerivedData/AzureCommunicationCallingSample/Build/Products/Debug-iphonesimulator/AzureCommunicationCallingSample.app/Frameworks/AzureCore.framework':
1) Target 'AzureCommunicationCallingSample' has copy command from '/Users/azure-sdk-for-ios-pr/build/Release-iphoneos/AzureCore.framework' to '/Users/sanathrao/Documents/source/communication-services-ios-quickstarts/Add Voice Calling/DerivedData/AzureCommunicationCallingSample/Build/Products/Debug-iphonesimulator/AzureCommunicationCallingSample.app/Frameworks/AzureCore.framework'
2) That command depends on command in Target 'AzureCommunicationCallingSample': script phase “[CP] Embed Pods Frameworks”
```

After these 2 changes i was able to build the sample test app successfully.
Please let us know if you still face the problem. 

Also Swift Package manager is not yet supported.

**Comment by devgokhan** [comment]
Hi. Thank you @raosanat my problem is resolved.
