### ISSUE TITLE
[iOS] Releasing `ACSRenderer` removes `ACSRemoteVideoStream` as well

### ISSUE THREAD

**Issue by ryanespiritu** [Azure/Communication#95]
**Describe the bug**
Disposing and releasing my reference to an `ACSRemoteParticipant`'s `ACSRenderer` causes the associated `ACSRemoteVideoStream` to be removed as well. In other words, the stream no longer appears in the `videoStreams` array maintained by the remote participant.

**Expected behavior**
I would expect that the removal/disposal of an `ACSRenderer` should not have an effect on an `ACSRemoteVideoStream`. For instance, it would be nice to be able to dispose the current renderer but re-use the remote video stream at another time and initialize a new renderer object with it.

**Comment by sankum-msft** [comment]
Disposing `ACSRenderer` raises a `ACSRemoteVideoStream` removed event which should be followed by another `ACSRemoteVideoStream` **added** event almost immediately. If your observation is based on these events, please make sure your app is handling both these events in the right order.

From the issue it seems you are talking about the `ACSRemoteParticipant.VideoStreams` collection. I was not able to repro the bug on my end. Can you please follow [this guide](https://docs.microsoft.com/en-us/azure/communication-services/concepts/troubleshooting-info?tabs=csharp%2Cios%2Cdotnet#enable-and-access-call-logs) to share your client logs for us to investigate? Also, please tell how often are you able to repro this bug.

**Comment by ryanespiritu** [comment]
Hey @sankum-msft thanks for the response! My observation was based off on `onVideoStreamsUpdated:`, I verified that after disposing the renderer I am only seeing **removed** streams and not **added** ones.

To add a bit more context here, I am attempting to dispose the renderers of remote participants when I background my app, in order to avoid any unnecessary overhead while the app is in the background. When I foreground the app, I wanted to create new renderers with the existing remote participants' `videoStreams` but I found that these arrays were empty.

_Here are the exact repro steps:_
1. Background the app and once `UIApplicationWillResignActiveNotification` is received, dispose the `ACSRenderers` for each `ACSRemoteParticipant`
2. Observe there are only `onVideoStreamsUpdated:` events for **removed** streams 
2. Foreground the app and once `UIApplicationDidBecomeActiveNotification` is received, attempt to access `videoStreams` for each `ACSRemoteParticipant` but observe these arrays are empty

**Comment by sankum-msft** [comment]
There is a known bug in ACS Calling SDK is not raising `ACSRemoteVideoStream` added event here. We have a fix in works and should be included as part of the next release.

**Comment by sankum-msft** [comment]
We've released [beta6](https://github.com/Azure/Communication/releases/tag/v1.0.0-beta.6) that should fix this issue.

**Comment by mariusu-msft** [comment]
Closing. Please let us know if you encounter this problem again.
