### ISSUE TITLE
[iOS] Issue with hanging up an `ACSCall` in the connecting state

### ISSUE THREAD

**Issue by ryanespiritu** [Azure/Communication#96]
Hanging up an `ACSCall` while its state is `ACSCallStateConnecting` results in the call getting stuck in `ACSCallStateNone` and the completion block for `hangup:withCompletionHandler` never gets invoked. 

Is this intended? If so, what is the suggested way for handling calls to `hangup:withCompletionHandler` while the `ACSCall` is still early on in its lifecycle?

**Comment by ProbablePrime** [comment]
Hey @ryanespiritu thanks for your query, can you clarify which SDK you're using. Thank you!

**Comment by ProbablePrime** [comment]
Ahh Apologies, I missed the iOs on the issue, thank you!

**Comment by sankum-msft** [comment]
We have identified a bug in the hangup code path that is causing this to fail. Calling team will work to fix this.

Thanks for reporting this issue.

**Comment by ryanespiritu** [comment]
Awesome, thanks for looking into this!

**Comment by terrychen1122** [comment]
@sankum-msft Thanks! Good to know that this is a bug we've identified. Do you know if there is an estimate when we can see the fix released?

**Comment by sankum-msft** [comment]
We don't have a date yet but we'll update when we pull it into current sprint.

**Comment by mariusu-msft** [comment]
This should now be fixed. Closing, please reopen if you encounter same issue again.
