### ISSUE TITLE
[iOS] is there a way to detect the speaking state of the current user?

### ISSUE THREAD

**Issue by terrychen1122** [Azure/Communication#97]
I know we can know if a remote participant is speaking. Is there a way to get this info for the current user? our use case is to highlight the person who is speaking regardless of local or remote

**Comment by ProbablePrime** [comment]
@raosanat are you able to answer this question or should we find an appropriate owner?

**Comment by mariusu-msft** [comment]
@terrychen1122 "speaking" currently just means unmuted.

For local call you can just check if you are locally muted or not.

We do not have actual "speaking" detection.

Can you use local mute flag to drive the UI per your requirements?

**Comment by rkprasad-ks** [comment]
@terrychen1122 can you clarify the use case on what you need this for our benefit?

**Comment by terrychen1122** [comment]
This is not a hard requirement as for the priority of this ask. 
@rkprasad-ks we need this to indicate the current user is speaking which will show an indicator. Since we will show indicator on anyone who is currently speaking, it would be nice to include the current user as well, as we want to have some visual feedback to let the user know that their voice is being sent out
@mariusu-msft for this, mute/unmute isn't the same as "speaking" as you can tell from the scenario I describe above.

**Comment by ProbablePrime** [comment]
@mariusu-msft Is there an update available for this issue?

**Comment by ProbablePrime** [comment]
Closing due to lack of response
