### ISSUE TITLE
No push notifications received on iOS

### ISSUE THREAD

**Issue by nielscup** [Azure/Communication#98]
**Describe the bug**
No push notifications received on iOS.

**To Reproduce**
1. Set up pushnotifications according to [this documentation ](https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/voice-video-calling/calling-client-samples?pivots=platform-ios#push-notification)
2. Make a call to an (iOS) device

**Expected behavior**
Incoming pushnotification

**Actual behaviour**
No pushnotification received

**Additional context**
App successfully registers for pushnotifications `callAgent.registerPushNotifications(deviceToken, ...` I have used a similar setup for Twilio backend where pushnotifications are received correctly.

Is there a working example somewhere that I can check to see if I am missing something?

**Comment by raosanat** [comment]
Hi @nielscup can you please attach the logs from the device? You can download it from the apps container and in Library/Caches folder you will see a file `acs_sdk.blog`

**Comment by nielscup** [comment]
Issue is probably caused by Notification Hub not set correctly for ACS in Azure

**Comment by nielscup** [comment]
Did anyone manage to receive push notifications on iOS for an incoming call? I would like to implement CallKit (Native dialer experience). I went through all the docs again below and it even says _Use APNS VOIP through Notification Hubs **(not officially supported)**_ So I would like to know if it is even possible to get a push notification through ACS?

1. https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/voice-video-calling/calling-client-samples?pivots=platform-ios#push-notification
2. https://docs.microsoft.com/en-us/azure/communication-services/concepts/notifications#deliver-push-notifications-via-azure-notification-hubs
3. https://docs.microsoft.com/en-us/azure/notification-hubs/voip-apns

**Comment by mariusu-msft** [comment]
Hi @nielscup,

Yes it’s possible to receive VoIP push notifications for iOS.

Have you gone through all the steps and linked your ANN resource to the ACS resource?

If not sensitive, please share you ANH and ACS resource names.

Thanks,
Marius

**Comment by razvansalajan** [comment]
Is the Anh hub linked to the Acs resource configured for the apns platform using [certificate authentication mode](https://docs.microsoft.com/en-us/azure/notification-hubs/configure-apple-push-notification-service#configure-apple-push-notification-service) ? 
The hub should be configured using token authentication mode as mentioned in the link above: https://docs.microsoft.com/en-us/azure/notification-hubs/voip-apns.

**Comment by nielscup** [comment]
> Hi @nielscup,
> 
> Yes it’s possible to receive VoIP push notifications for iOS.
> 
> Have you gone through all the steps and linked your ANN resource to the ACS resource?
> 
> If not sensitive, please share you ANH and ACS resource names.
> 
> Thanks,
> Marius

Yes I have gone through all steps and docs as described in my earlier post and notificationhub is successfully linked to ACS according to the activity log. I am also using Token authentication.

I have checked certificates and provisioning profile setup by using RegisterForRemoteNotifications in AppDelegate for the same notificationhub and using Test Send in Azure. Notifications are received. Is there an iOS code sample that I can have a look at?

**Comment by mariusu-msft** [comment]
1. we are working on a sample for this scenario, but we don’t have an ETA for publishing. I’ll check when we can share it and get back to you.

2. We are sending the notification when a call is placed to an user which is registered for notifications. It you have set everything up, we should investigate what is going wrong.

Could you provide us with a couple of details so we can investigate?
a) When you place a call which has no push notification delivered - please share the ID property of the Call Object

https://docs.microsoft.com/en-us/azure/communication-services/concepts/troubleshooting-info?tabs=csharp%2Cios%2Cdotnet#access-your-call-id

b) please share your ACS ARM resource id

c) collect logs from the client not receiving notification
https://docs.microsoft.com/en-us/azure/communication-services/concepts/troubleshooting-info?tabs=csharp%2Cjavascript%2Cdotnet#enable-and-access-call-logs

We can start with a) and b) first.

**Comment by nielscup** [comment]
a) CallId: 9c85bcb5-f148-4152-9373-84b0e4b74a40
b) /subscriptions/6ed61357-5248-446a-9afe-68bf49ef97ec/resourceGroups/WSPCommunicationServicesResourceGroup/providers/Microsoft.Communication/CommunicationServices/WSPCommunicationServices

**Comment by raosanat** [comment]
Can you please provide client side logs ? 

c) collect logs from the client not receiving notification
https://docs.microsoft.com/en-us/azure/communication-services/concepts/troubleshooting-info?tabs=csharp%2Cjavascript%2Cdotnet#enable-and-access-call-logs

**Comment by mariusu-msft** [comment]
Thanks for the details Niels.

Based on ACS\ANH telemetry we saw the following progress:
- ANH hub was not linked
- ANH configuration was using cert-based auth, which is incompatible with APNS Push
- (and currently) we see APNS accepting our push notifications

Based on current state, this looks properly set up, and expecting this to work now. We're looking to make the provisioning story better in the future, to highlight any issues in the portal.

Would you be able to share a snippet of code on how you are handling the push notification? How are you determining that the push notification did not arrive?

Please also share logs as @raosanat suggested, telemetry indicates all is fine with registration, this will help us double check that.

**Comment by razvansalajan** [comment]
Hi Niels,

Have you looked in [Anh hub metrics](https://docs.microsoft.com/en-us/azure/notification-hubs/notification-hubs-push-notification-fixer#azure-portal-2) to see if Anh has successfully delivered to notifications to Apns ? There are detailed metrics for different types of errors that Anh could receive from Apns in case of an unsuccessful delivery.

The "Incoming Messages" metric should say the number of notifications sent by Acs (and others if the hub is shared) through the linked hub.

**Comment by nielscup** [comment]
Thanks for the advise. I currently see the following ANH metrics:

1. **Incoming messages:** When I make a call from 1 device to another, an _Incoming messages_ appears. This tells me that ACS is sending messages correctly to ANH
2. **APNS Successful Notifications:**  When I make a call from 1 device to another, _APNS Successful Notifications_ do not appear. This tells me that ANH is not sending the APNS message to the registered devices when receiving a message from ACS. 
3. When I use "_Test send_", I see the _APNS Successful Notifications_ appearing 

See screenshot below: 

- 1st spike is an incoming message **without** APNS notification, triggered by calling device
- 2nd spike is an incoming message **with** APNS notifications, triggered by "Test send"

<img width="1164" alt="Screenshot 2020-11-16 at 11 50 52" src="https://user-images.githubusercontent.com/3483085/99244210-0f7fa000-2802-11eb-80b2-ee395bcb444d.png">


This is my code:

```
        public override bool FinishedLaunching(UIApplication app, NSDictionary options)
        {
                ...
                RequestPushNotificationPermissions();
                ...
        }     

        void RequestPushNotificationPermissions()
        {
            Debug.WriteLine($"1 RequestPushNotificationPermissions");
            if (UIDevice.CurrentDevice.CheckSystemVersion(10, 0))
            {
                UNUserNotificationCenter.Current.RequestAuthorization(UNAuthorizationOptions.Alert | UNAuthorizationOptions.Badge | UNAuthorizationOptions.Sound,
                                                                        (granted, error) => InvokeOnMainThread(UIApplication.SharedApplication.RegisterForRemoteNotifications));
            }
            else if (UIDevice.CurrentDevice.CheckSystemVersion(8, 0))
            {
                var pushSettings = UIUserNotificationSettings.GetSettingsForTypes(
                        UIUserNotificationType.Alert | UIUserNotificationType.Badge | UIUserNotificationType.Sound,
                        new NSSet());

                UIApplication.SharedApplication.RegisterUserNotificationSettings(pushSettings);
                UIApplication.SharedApplication.RegisterForRemoteNotifications();
            }
            else
            {
                UIRemoteNotificationType notificationTypes = UIRemoteNotificationType.Alert | UIRemoteNotificationType.Badge | UIRemoteNotificationType.Sound;
                UIApplication.SharedApplication.RegisterForRemoteNotificationTypes(notificationTypes);
            }
        }

        // https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/voice-video-calling/calling-client-samples?pivots=platform-ios
        public override void RegisteredForRemoteNotifications(UIApplication application, NSData deviceToken)
        {
            Debug.WriteLine($"2 RegisteredForRemoteNotifications. DeviceToken:{deviceToken}");
            RegisterVoip();
        }

        void RegisterVoip()
        {
            Debug.WriteLine($"3 RegisterVoip");

            var mainQueue = DispatchQueue.MainQueue;
            PKPushRegistry voipRegistry = new PKPushRegistry(mainQueue);
            voipRegistry.Delegate = this;
            voipRegistry.DesiredPushTypes = new NSSet(new string[] { PushKit.PKPushType.Voip });
        }

        public void DidUpdatePushCredentials(PKPushRegistry registry, PKPushCredentials credentials, string type)
        {
            Debug.WriteLine($"4 DidUpdatePushCredentials");

            if (registry != null)
            {
                CallingManager.DeviceToken = registry?.PushToken(PKPushType.Voip);
                //TwilioService.DeviceToken = deviceToken;
            }
        }

        public void DidReceiveIncomingPush(PKPushRegistry registry, PKPushPayload payload, string type)
        {
            Console.WriteLine("DidReceiveIncomingPush");
            if (payload != null)
            {
                CallingManager.HandlePusNotification(payload);
                //TwilioService.Setnotification(payload);
            }
        }

        [Export("pushRegistry:didReceiveIncomingPushWithPayload:forType:withCompletionHandler:")]
        public void DidReceiveIncomingPush(PKPushRegistry registry, PKPushPayload payload, string type, Action completion)
        {
            Debug.WriteLine("DidReceiveIncomingPush with completion");

            CallingManager.HandlePusNotification(payload);
            //CallProviderDelegate.ReportIncomingCall(TwilioVoiceHelper.activeCallUuid, "iPad calling...");
        }
```

I will share logging in a moment...

**Comment by mariusu-msft** [comment]
@nielscup I see you are using Xamarin? Are you using this project here?https://github.com/Laerdal/Xamarin.AzureCommunicationCalling

Please check the metrics Razvan is pointing too and let us know. Meanwhile, we will investigate if this works as expected in Xamarin.

**Comment by mariusu-msft** [comment]
@nielscup We're still investigating if this is Xamarin related. We are not able to reproduce on a Swift or Obj-C app. 

We'll keep you posted. @raosanat and @razvansalajan are investigating

-Marius

**Comment by nielscup** [comment]
There are channel errors. Any ideas on what they are and why they occur?
![Screenshot 2020-11-17 at 08 35 42](https://user-images.githubusercontent.com/3483085/99360446-e10cce00-28b0-11eb-83f9-6d3cb99ebf74.png)

I would expect to see any errors in the anh overview when they occur, but that is not the case apparently:
![Screenshot 2020-11-17 at 08 37 23](https://user-images.githubusercontent.com/3483085/99360168-7a87b000-28b0-11eb-8d20-10251dfd1446.png)
There is also a button "Drill into logs" but it doesn't display any errors. Is there a simple list of all errors that have occurred, including the platform specific error message or do I need to select each error manually to see if any have occurred?

**Comment by nielscup** [comment]
Hi Marius,

Can you send me the swift app project? This problem is either ANH related
or I am missing a step in my code. To rule out the latter, I would like to
cross check with a working example. I see Channel errors in ANH,  but I
can't find any documentation on this. Any ideas?

Kind regards,

Niels Cup.

**Comment by nielscup** [comment]
> @nielscup We're still investigating if this is Xamarin related. We are not able to reproduce on a Swift or Obj-C app.
> 
> We'll keep you posted. @raosanat and @razvansalajan are investigating
> 
> -Marius

Can you send me the swift app project? I may be missing a step in my code. To rule this out, I would like to
cross check with a working example.

**Comment by mariusu-msft** [comment]
@nielscup those errors occur when the push token provided is not valid.

Can you double check if you are using the same bundleId as your provisioned ANH hub?

**Comment by nielscup** [comment]
App bundleId is the same as bundlId provided in ANH. Anything wrong with the ANH name perhaps? I read in the docs that the ANH name should be BundleId + .voip, so mine is net.cupit.testapp1.voip.

**Comment by mariusu-msft** [comment]
Great! Happy to hear something is happening.

**Comment by nielscup** [comment]
@mariusu-msft  Could you please share your swift project?

**Comment by mariusu-msft** [comment]
@nielscup we’re unable to send the project as is right now. We’re planning to have a push notification E2E sample on GitHub in the next few months.

Do you still have issues with push notifications?

Let me know which part you are having trouble with and I’ll try to see if we can extract some code bits to share.

**Comment by nielscup** [comment]
1) CallAgent.HandlePushNotification() returns an error: "failed".
2) Another problem I have is that the CallId coming from the voip notification is different from the CallId I see in the ACSDelegate. This makes it difficult to manage callkit. Is this by design?

**Comment by raosanat** [comment]
Having logs will help to investigate further. We have sent instructions on how to fetch the logs in previous comments.

**Comment by nielscup** [comment]
@raosanat Logs: https://1drv.ms/u/s!Ar7iCD_v5seIltFWkUrP-WZnOLjQBA?e=YL05ns

**Comment by raosanat** [comment]
@nielscup thanks for the logs. I see that call to API `handlePushNotification` is failing  because a `Call` object for that payload was already created. When are you calling the API `handlePushNotification` ? 

Also before reproducing the issue again:

1. Uninstall the app.
2. Reproduce the issue again.
3. Attach the blogs again here.

**Comment by nielscup** [comment]
> we’re unable to send the project as is right now. We’re planning to have a push notification E2E sample on GitHub in the next few months.

Does this mean ACS is not working on your end as well? Otherwise making an example shouldn't take a few months. If so I will continue with something else because this is taking too long.

**Comment by raosanat** [comment]
From the logs it looks like delegate on ACSCallClient should have got the incoming call event notification . The false returned from handlePushNotification is an incorrect one, we should return True, that’s the bug on our side.
 But functionality wise incoming call notification , at-least according to the logs, should be working as expected.

**Comment by nielscup** [comment]
I receive the voip notification, so that works. HandlePushNotification fails, as mentioned above.

How about point 2 from my previous post? 

> Another problem I have is that on the receiving device, the CallId in the voip notification is different from the CallId coming from ACS (in ACSCallDelegate.OnRemoteParticipantsUpdated). The callId on the calling device is the same as the callId in the voip notification on the receiving device.

**Comment by raosanat** [comment]
1. If your app is in foreground and when there is incoming call , are you receiving  incoming call notification event (without making the registerPushNotification or handlePushNotification API calls) ? 

2. Also please can you send us the logs after uninstalling the app and reproducing the scenario? In the previous link you sent there were multiple logs and it is difficult to say which logs corresponds to the issue that you are facing.

**Comment by nielscup** [comment]
Were there any updates today? I cant even make a call anymore. Device is ringing but as soon as I answer the call, callstate is updated to None from ACSCallDelegate  and participant is removed. This was working fine this morning.

**Comment by nielscup** [comment]
I recieve a voip notification as well as the event from ACS in OnRemoteParticipantUpdated when running the app in foreground. The pushnotification triggers callkit, which is required by apple otherwise the app is killed by iOS. So the Callkit is triggered with a different callId than the one is coming in via OnRemoteParticipantUpdated.

I am unable to make a second call: Immediately after answering the second call I get a callstateChange in ACSCallDelegate and callstate changes to None and participant is removed. Is this a known issue?

**Comment by mariusu-msft** [comment]
Hi @nielscup,

Any reason you are looking at OnRemoteParticipantUpdated for callId?

Call Id is best to get from the Id property of the Call object, and use OnCallsUpdated event to be notified of new calls.

Regarding the failure when you answer, that is not a expected. Seems there are two issues here:
1) when you process HandlePushNotification; you get back Failed, this is due to a race condition, we will fix it in next release
2) when you process HandlePushNotification you are seeing that call goes to disconnected. This is not expected. Please provide call Id or logs.

A workaround for 1) would be this:

1) get push notification
2) extract CallId from payload
3) look for the call with same id on Calls property of the CallAgent
4) if call found discard the push notification
5) if call not found call HandlePushNotification

There’s a holiday here in US and office is closed, there may be delays in responses until Monday.

Thanks,
Marius

**Comment by nielscup** [comment]
Thanks, I ll try using `OnCallsUpdated`. The reason I use `OnRemoteParticipantUpdated` because `OnCallsUpdated` doesn't fire when joining group, `OnRemoteParticipantUpdated` does.

Another thing I noticed: in `call?.Hangup(hangupOptions, OnHangup);` `Onhangup` is not fired when callState = `ringing`.

**Comment by nielscup** [comment]
Another issue when I use hangup while ringing: `call.Hangup(hangupOptions, OnHangup);`
The call is ended on both devices but `OnHangup` does not fire. I can work around this by firing `OnHangup` manually when call state is ringing, but if I do this a second time, hangup does not work anymore, the (ringing) call is not ended at all.

Maybe related to this issue?: https://github.com/Azure/Communication/issues/126

**Comment by RinaRish** [comment]
Hi @nielscup! Very sorry for the late reply. The issue that you mentioned in your last comment was resolved. Please let us know if you have any other problems. thanks!

**Comment by ProbablePrime** [comment]
Closing with lack of response
